import { upsertCategoryAndSentences } from './seed-helper.mjs';

export const category = {
  "slug": "ai",
  "label": "Artificial Intelligence",
  "icon": "🤖",
  "description": "Neural networks, autonomous agents, and synthetic minds",
  "display_order": 22
};

export const sentences = {
  "easy": [
    "Machines learn from data",
    "Neural nets recognize patterns",
    "Prompts steer language models",
    "Robots navigate warehouse floors",
    "Algorithms optimize complex routes",
    "Compute scales intelligence up",
    "Weights update during training",
    "Loss function minimizes errors",
    "Embeddings capture semantic meaning",
    "Transformers attend to tokens",
    "Fine tune pretrained models",
    "Diffusion generates photorealistic images",
    "Reinforcement learning optimizes rewards",
    "Agents collaborate to solve",
    "Compute gradients with backpropagation",
    "GPUs accelerate matrix calculations",
    "Computer vision detects tumors",
    "Speech models transcribe audio",
    "Evaluate benchmark test accuracy",
    "Deploy inference at edge",
    "converge the neural neuron",
    "neural neuron converge machine intelligence",
    "neuron brings neural machine intelligence",
    "Always converge neural neuron",
    "Every neuron can converge",
    "synthesize the algorithmic tensor",
    "algorithmic tensor synthesize neural architecture",
    "tensor brings algorithmic neural architecture",
    "Always synthesize algorithmic tensor",
    "Every tensor can synthesize",
    "optimize the autonomous gradient",
    "autonomous gradient optimize gradient descent",
    "gradient brings autonomous gradient descent",
    "Always optimize autonomous gradient",
    "Every gradient can optimize",
    "generalize the generative token",
    "generative token generalize foundation model",
    "token brings generative foundation model",
    "Always generalize generative token",
    "Every token can generalize",
    "classify the predictive embedding",
    "predictive embedding classify autonomous agent",
    "embedding brings predictive autonomous agent",
    "Always classify predictive embedding",
    "Every embedding can classify",
    "backpropagate the synthetic transformer",
    "synthetic transformer backpropagate deep learning",
    "transformer brings synthetic deep learning",
    "Always backpropagate synthetic transformer",
    "Every transformer can backpropagate",
    "predict the probabilistic dataset",
    "probabilistic dataset predict machine intelligence",
    "dataset brings probabilistic machine intelligence",
    "Always predict probabilistic dataset",
    "Every dataset can predict",
    "align the intelligent parameter",
    "intelligent parameter align neural architecture",
    "parameter brings intelligent neural architecture",
    "Always align intelligent parameter",
    "Every parameter can align",
    "fine-tune the scalable inference",
    "scalable inference fine-tune gradient descent",
    "inference brings scalable gradient descent",
    "Always fine-tune scalable inference",
    "Every inference can fine-tune",
    "quantize the latent latency",
    "latent latency quantize foundation model",
    "latency brings latent foundation model",
    "Always quantize latent latency",
    "Every latency can quantize",
    "neural neuron converge autonomous agent",
    "neuron brings neural autonomous agent",
    "algorithmic tensor synthesize deep learning",
    "tensor brings algorithmic deep learning",
    "autonomous gradient optimize machine intelligence",
    "gradient brings autonomous machine intelligence",
    "generative token generalize neural architecture",
    "token brings generative neural architecture",
    "predictive embedding classify gradient descent",
    "embedding brings predictive gradient descent",
    "synthetic transformer backpropagate foundation model",
    "transformer brings synthetic foundation model",
    "probabilistic dataset predict autonomous agent",
    "dataset brings probabilistic autonomous agent",
    "intelligent parameter align deep learning",
    "parameter brings intelligent deep learning",
    "scalable inference fine-tune machine intelligence",
    "inference brings scalable machine intelligence",
    "latent latency quantize neural architecture",
    "latency brings latent neural architecture",
    "neural neuron converge gradient descent",
    "neuron brings neural gradient descent",
    "algorithmic tensor synthesize foundation model",
    "tensor brings algorithmic foundation model",
    "autonomous gradient optimize autonomous agent",
    "gradient brings autonomous autonomous agent",
    "generative token generalize deep learning",
    "token brings generative deep learning",
    "predictive embedding classify machine intelligence",
    "embedding brings predictive machine intelligence"
  ],
  "normal": [
    "Deep learning models process billions of statistical parameters effortlessly",
    "Reinforcement learning trains autonomous agents through iterative feedback rewards",
    "Transformer architecture revolutionized natural language processing capabilities globally worldwide",
    "Autonomous vehicles interpret lidar and camera vision streams in realtime",
    "Synthetic intelligence assists researchers in folding complex biological proteins",
    "Computer vision detects microscopic cellular tumors faster than human doctors",
    "Large language models synthesize vast repositories of human written knowledge",
    "Neural networks learn hierarchical feature representations directly from raw data",
    "Prompt engineering guides foundation models toward producing structured verifiable outputs",
    "Ethical AI governance ensures fairness accountability and transparency across deployments",
    "The neural neuron will greatly converge our machine intelligence today",
    "Every neural neuron must converge carefully across the entire machine",
    "Learning how to converge neural neuron inspires deep machine intelligence",
    "Our dedicated team will converge the neural neuron for machine",
    "The algorithmic tensor will greatly synthesize our neural architecture today",
    "Every algorithmic tensor must synthesize carefully across the entire neural",
    "Learning how to synthesize algorithmic tensor inspires deep neural architecture",
    "Our dedicated team will synthesize the algorithmic tensor for neural",
    "The autonomous gradient will greatly optimize our gradient descent today",
    "Every autonomous gradient must optimize carefully across the entire gradient",
    "Learning how to optimize autonomous gradient inspires deep gradient descent",
    "Our dedicated team will optimize the autonomous gradient for gradient",
    "The generative token will greatly generalize our foundation model today",
    "Every generative token must generalize carefully across the entire foundation",
    "Learning how to generalize generative token inspires deep foundation model",
    "Our dedicated team will generalize the generative token for foundation",
    "The predictive embedding will greatly classify our autonomous agent today",
    "Every predictive embedding must classify carefully across the entire autonomous",
    "Learning how to classify predictive embedding inspires deep autonomous agent",
    "Our dedicated team will classify the predictive embedding for autonomous",
    "The synthetic transformer will greatly backpropagate our deep learning today",
    "Every synthetic transformer must backpropagate carefully across the entire deep",
    "Learning how to backpropagate synthetic transformer inspires deep deep learning",
    "Our dedicated team will backpropagate the synthetic transformer for deep",
    "The probabilistic dataset will greatly predict our machine intelligence today",
    "Every probabilistic dataset must predict carefully across the entire machine",
    "Learning how to predict probabilistic dataset inspires deep machine intelligence",
    "Our dedicated team will predict the probabilistic dataset for machine",
    "The intelligent parameter will greatly align our neural architecture today",
    "Every intelligent parameter must align carefully across the entire neural",
    "Learning how to align intelligent parameter inspires deep neural architecture",
    "Our dedicated team will align the intelligent parameter for neural",
    "The scalable inference will greatly fine-tune our gradient descent today",
    "Every scalable inference must fine-tune carefully across the entire gradient",
    "Learning how to fine-tune scalable inference inspires deep gradient descent",
    "Our dedicated team will fine-tune the scalable inference for gradient",
    "The latent latency will greatly quantize our foundation model today",
    "Every latent latency must quantize carefully across the entire foundation",
    "Learning how to quantize latent latency inspires deep foundation model",
    "Our dedicated team will quantize the latent latency for foundation",
    "The neural neuron will greatly converge our autonomous agent today",
    "Every neural neuron must converge carefully across the entire autonomous",
    "Learning how to converge neural neuron inspires deep autonomous agent",
    "Our dedicated team will converge the neural neuron for autonomous",
    "The algorithmic tensor will greatly synthesize our deep learning today",
    "Every algorithmic tensor must synthesize carefully across the entire deep",
    "Learning how to synthesize algorithmic tensor inspires deep deep learning",
    "Our dedicated team will synthesize the algorithmic tensor for deep",
    "The autonomous gradient will greatly optimize our machine intelligence today",
    "Every autonomous gradient must optimize carefully across the entire machine",
    "Learning how to optimize autonomous gradient inspires deep machine intelligence",
    "Our dedicated team will optimize the autonomous gradient for machine",
    "The generative token will greatly generalize our neural architecture today",
    "Every generative token must generalize carefully across the entire neural",
    "Learning how to generalize generative token inspires deep neural architecture",
    "Our dedicated team will generalize the generative token for neural",
    "The predictive embedding will greatly classify our gradient descent today",
    "Every predictive embedding must classify carefully across the entire gradient",
    "Learning how to classify predictive embedding inspires deep gradient descent",
    "Our dedicated team will classify the predictive embedding for gradient"
  ],
  "hard": [
    "Can machines think was the famous provocative question posed by Alan Turing at dawn of modern digital computation",
    "Large language models predict upcoming tokens based on probabilities learned from trillions of written words across global internet",
    "Aligning advanced artificial intelligence with human values remains one of the most critical and challenging tasks of century",
    "Diffusion models generate photorealistic artwork by reversing a gradual process of adding Gaussian noise to pristine training images",
    "Edge computing enables lightweight neural networks to perform inference directly on consumer smartphones without requiring cloud server roundtrips",
    "When confronting complex challenges in machine intelligence one must converge every neural neuron with rigorous discipline and patient determination",
    "The integration of neural neuron within modern machine intelligence enables practitioners to converge critical milestones without sacrificing enduring quality",
    "Throughout the evolution of machine intelligence master practitioners learned to converge the most intricate neural neuron through persistent dedicated effort",
    "Developing comprehensive understanding of machine intelligence demands that professionals converge each neural neuron with profound analytical rigor and integrity",
    "When confronting complex challenges in neural architecture one must synthesize every algorithmic tensor with rigorous discipline and patient determination",
    "The integration of algorithmic tensor within modern neural architecture enables practitioners to synthesize critical milestones without sacrificing enduring quality",
    "Throughout the evolution of neural architecture master practitioners learned to synthesize the most intricate algorithmic tensor through persistent dedicated effort",
    "Developing comprehensive understanding of neural architecture demands that professionals synthesize each algorithmic tensor with profound analytical rigor and integrity",
    "When confronting complex challenges in gradient descent one must optimize every autonomous gradient with rigorous discipline and patient determination",
    "The integration of autonomous gradient within modern gradient descent enables practitioners to optimize critical milestones without sacrificing enduring quality",
    "Throughout the evolution of gradient descent master practitioners learned to optimize the most intricate autonomous gradient through persistent dedicated effort",
    "Developing comprehensive understanding of gradient descent demands that professionals optimize each autonomous gradient with profound analytical rigor and integrity",
    "When confronting complex challenges in foundation model one must generalize every generative token with rigorous discipline and patient determination",
    "The integration of generative token within modern foundation model enables practitioners to generalize critical milestones without sacrificing enduring quality",
    "Throughout the evolution of foundation model master practitioners learned to generalize the most intricate generative token through persistent dedicated effort",
    "Developing comprehensive understanding of foundation model demands that professionals generalize each generative token with profound analytical rigor and integrity",
    "When confronting complex challenges in autonomous agent one must classify every predictive embedding with rigorous discipline and patient determination",
    "The integration of predictive embedding within modern autonomous agent enables practitioners to classify critical milestones without sacrificing enduring quality",
    "Throughout the evolution of autonomous agent master practitioners learned to classify the most intricate predictive embedding through persistent dedicated effort",
    "Developing comprehensive understanding of autonomous agent demands that professionals classify each predictive embedding with profound analytical rigor and integrity",
    "When confronting complex challenges in deep learning one must backpropagate every synthetic transformer with rigorous discipline and patient determination",
    "The integration of synthetic transformer within modern deep learning enables practitioners to backpropagate critical milestones without sacrificing enduring quality",
    "Throughout the evolution of deep learning master practitioners learned to backpropagate the most intricate synthetic transformer through persistent dedicated effort",
    "Developing comprehensive understanding of deep learning demands that professionals backpropagate each synthetic transformer with profound analytical rigor and integrity",
    "When confronting complex challenges in machine intelligence one must predict every probabilistic dataset with rigorous discipline and patient determination"
  ]
};

export async function seed() {
  return await upsertCategoryAndSentences(category, sentences);
}

if (process.argv[1]?.endsWith('ai.mjs')) {
  seed().catch(console.error);
}
