import { upsertCategoryAndSentences } from './seed-helper.mjs';

export const category = {
  "slug": "architecture",
  "label": "Architecture & Design",
  "icon": "📐",
  "description": "Skyscrapers, brutalism, Bauhaus, and spatial harmony",
  "display_order": 23
};

export const sentences = {
  "easy": [
    "Form follows intended function",
    "Arches distribute heavy loads",
    "Concrete and steel rise",
    "Skylights flood rooms sunshine",
    "Minimalism embraces clean space",
    "Blueprints guide the builders",
    "Columns support marble roof",
    "Cantilevers extend over cliffs",
    "Timber beams span ceilings",
    "Glass facades reflect clouds",
    "Geometric symmetry pleases eye",
    "Atrium brings natural light",
    "Staircases spiral toward sky",
    "Vaulted ceilings echo footsteps",
    "Brutalist concrete shows texture",
    "Gothic arches reach high",
    "Flying buttresses support walls",
    "Domes distribute stress evenly",
    "Sustainable design saves energy",
    "Renovate historic brick buildings",
    "construct the geometric facade",
    "geometric facade construct spatial design",
    "facade brings geometric spatial design",
    "Always construct geometric facade",
    "Every facade can construct",
    "engineer the structural cantilever",
    "structural cantilever engineer urban planning",
    "cantilever brings structural urban planning",
    "Always engineer structural cantilever",
    "Every cantilever can engineer",
    "sculpt the brutalist arch",
    "brutalist arch sculpt structural engineering",
    "arch brings brutalist structural engineering",
    "Always sculpt brutalist arch",
    "Every arch can sculpt",
    "articulate the minimalist blueprint",
    "minimalist blueprint articulate monumental craft",
    "blueprint brings minimalist monumental craft",
    "Always articulate minimalist blueprint",
    "Every blueprint can articulate",
    "balance the gothic scaffold",
    "gothic scaffold balance bauhaus design",
    "scaffold brings gothic bauhaus design",
    "Always balance gothic scaffold",
    "Every scaffold can balance",
    "renovate the monumental column",
    "monumental column renovate modernist form",
    "column brings monumental modernist form",
    "Always renovate monumental column",
    "Every column can renovate",
    "elevate the sustainable atrium",
    "sustainable atrium elevate spatial design",
    "atrium brings sustainable spatial design",
    "Always elevate sustainable atrium",
    "Every atrium can elevate",
    "proportion the spatial dome",
    "spatial dome proportion urban planning",
    "dome brings spatial urban planning",
    "Always proportion spatial dome",
    "Every dome can proportion",
    "integrate the cantilevered pediment",
    "cantilevered pediment integrate structural engineering",
    "pediment brings cantilevered structural engineering",
    "Always integrate cantilevered pediment",
    "Every pediment can integrate",
    "harmonize the ornate colonnade",
    "ornate colonnade harmonize monumental craft",
    "colonnade brings ornate monumental craft",
    "Always harmonize ornate colonnade",
    "Every colonnade can harmonize",
    "geometric facade construct bauhaus design",
    "facade brings geometric bauhaus design",
    "structural cantilever engineer modernist form",
    "cantilever brings structural modernist form",
    "brutalist arch sculpt spatial design",
    "arch brings brutalist spatial design",
    "minimalist blueprint articulate urban planning",
    "blueprint brings minimalist urban planning",
    "gothic scaffold balance structural engineering",
    "scaffold brings gothic structural engineering",
    "monumental column renovate monumental craft",
    "column brings monumental monumental craft",
    "sustainable atrium elevate bauhaus design",
    "atrium brings sustainable bauhaus design",
    "spatial dome proportion modernist form",
    "dome brings spatial modernist form",
    "cantilevered pediment integrate spatial design",
    "pediment brings cantilevered spatial design",
    "ornate colonnade harmonize urban planning",
    "colonnade brings ornate urban planning",
    "geometric facade construct structural engineering",
    "facade brings geometric structural engineering",
    "structural cantilever engineer monumental craft",
    "cantilever brings structural monumental craft",
    "brutalist arch sculpt bauhaus design",
    "arch brings brutalist bauhaus design",
    "minimalist blueprint articulate modernist form",
    "blueprint brings minimalist modernist form",
    "gothic scaffold balance spatial design",
    "scaffold brings gothic spatial design"
  ],
  "normal": [
    "Good architectural design is as little design as possible",
    "Flying buttresses allowed gothic cathedrals soaring stained glass windows",
    "Natural ambient lighting transforms the emotional quality of interior spaces",
    "Brutalist buildings showcase raw exposed textured poured architectural concrete",
    "Sustainable architecture incorporates passive solar heating and natural cross ventilation",
    "Cantilever balconies appear to defy gravity over steep cliffside drops",
    "The Bauhaus movement unified fine craftsmanship with industrial mass manufacturing",
    "Urban architects design pedestrian friendly plazas to foster community connection",
    "Acoustic design ensures sound distributes warmly throughout concert hall auditoriums",
    "Proportion scale and rhythm define the architectural character of structures",
    "The geometric facade will greatly construct our spatial design today",
    "Every geometric facade must construct carefully across the entire spatial",
    "Learning how to construct geometric facade inspires deep spatial design",
    "Our dedicated team will construct the geometric facade for spatial",
    "The structural cantilever will greatly engineer our urban planning today",
    "Every structural cantilever must engineer carefully across the entire urban",
    "Learning how to engineer structural cantilever inspires deep urban planning",
    "Our dedicated team will engineer the structural cantilever for urban",
    "The brutalist arch will greatly sculpt our structural engineering today",
    "Every brutalist arch must sculpt carefully across the entire structural",
    "Learning how to sculpt brutalist arch inspires deep structural engineering",
    "Our dedicated team will sculpt the brutalist arch for structural",
    "The minimalist blueprint will greatly articulate our monumental craft today",
    "Every minimalist blueprint must articulate carefully across the entire monumental",
    "Learning how to articulate minimalist blueprint inspires deep monumental craft",
    "Our dedicated team will articulate the minimalist blueprint for monumental",
    "The gothic scaffold will greatly balance our bauhaus design today",
    "Every gothic scaffold must balance carefully across the entire bauhaus",
    "Learning how to balance gothic scaffold inspires deep bauhaus design",
    "Our dedicated team will balance the gothic scaffold for bauhaus",
    "The monumental column will greatly renovate our modernist form today",
    "Every monumental column must renovate carefully across the entire modernist",
    "Learning how to renovate monumental column inspires deep modernist form",
    "Our dedicated team will renovate the monumental column for modernist",
    "The sustainable atrium will greatly elevate our spatial design today",
    "Every sustainable atrium must elevate carefully across the entire spatial",
    "Learning how to elevate sustainable atrium inspires deep spatial design",
    "Our dedicated team will elevate the sustainable atrium for spatial",
    "The spatial dome will greatly proportion our urban planning today",
    "Every spatial dome must proportion carefully across the entire urban",
    "Learning how to proportion spatial dome inspires deep urban planning",
    "Our dedicated team will proportion the spatial dome for urban",
    "The cantilevered pediment will greatly integrate our structural engineering today",
    "Every cantilevered pediment must integrate carefully across the entire structural",
    "Learning how to integrate cantilevered pediment inspires deep structural engineering",
    "Our dedicated team will integrate the cantilevered pediment for structural",
    "The ornate colonnade will greatly harmonize our monumental craft today",
    "Every ornate colonnade must harmonize carefully across the entire monumental",
    "Learning how to harmonize ornate colonnade inspires deep monumental craft",
    "Our dedicated team will harmonize the ornate colonnade for monumental",
    "The geometric facade will greatly construct our bauhaus design today",
    "Every geometric facade must construct carefully across the entire bauhaus",
    "Learning how to construct geometric facade inspires deep bauhaus design",
    "Our dedicated team will construct the geometric facade for bauhaus",
    "The structural cantilever will greatly engineer our modernist form today",
    "Every structural cantilever must engineer carefully across the entire modernist",
    "Learning how to engineer structural cantilever inspires deep modernist form",
    "Our dedicated team will engineer the structural cantilever for modernist",
    "The brutalist arch will greatly sculpt our spatial design today",
    "Every brutalist arch must sculpt carefully across the entire spatial",
    "Learning how to sculpt brutalist arch inspires deep spatial design",
    "Our dedicated team will sculpt the brutalist arch for spatial",
    "The minimalist blueprint will greatly articulate our urban planning today",
    "Every minimalist blueprint must articulate carefully across the entire urban",
    "Learning how to articulate minimalist blueprint inspires deep urban planning",
    "Our dedicated team will articulate the minimalist blueprint for urban",
    "The gothic scaffold will greatly balance our structural engineering today",
    "Every gothic scaffold must balance carefully across the entire structural",
    "Learning how to balance gothic scaffold inspires deep structural engineering",
    "Our dedicated team will balance the gothic scaffold for structural"
  ],
  "hard": [
    "Architecture is frozen music composed of physical proportions materials shadows and the subtle interplay of natural ambient light",
    "The Bauhaus movement unified fine craftsmanship with industrial mass production to create functional elegant objects for everyday human life",
    "Urban planners design walkable neighborhoods with green parks to foster healthy social connections among diverse metropolitan city residents",
    "Geodesic domes distribute stress evenly across interlocking triangular facets creating incredibly strong and lightweight structural building enclosures",
    "Restoring historic brick facades preserves cultural heritage while integrating modern energy efficient thermal insulation within ancient masonry walls",
    "When confronting complex challenges in spatial design one must construct every geometric facade with rigorous discipline and patient determination",
    "The integration of geometric facade within modern spatial design enables practitioners to construct critical milestones without sacrificing enduring quality",
    "Throughout the evolution of spatial design master practitioners learned to construct the most intricate geometric facade through persistent dedicated effort",
    "Developing comprehensive understanding of spatial design demands that professionals construct each geometric facade with profound analytical rigor and integrity",
    "When confronting complex challenges in urban planning one must engineer every structural cantilever with rigorous discipline and patient determination",
    "The integration of structural cantilever within modern urban planning enables practitioners to engineer critical milestones without sacrificing enduring quality",
    "Throughout the evolution of urban planning master practitioners learned to engineer the most intricate structural cantilever through persistent dedicated effort",
    "Developing comprehensive understanding of urban planning demands that professionals engineer each structural cantilever with profound analytical rigor and integrity",
    "When confronting complex challenges in structural engineering one must sculpt every brutalist arch with rigorous discipline and patient determination",
    "The integration of brutalist arch within modern structural engineering enables practitioners to sculpt critical milestones without sacrificing enduring quality",
    "Throughout the evolution of structural engineering master practitioners learned to sculpt the most intricate brutalist arch through persistent dedicated effort",
    "Developing comprehensive understanding of structural engineering demands that professionals sculpt each brutalist arch with profound analytical rigor and integrity",
    "When confronting complex challenges in monumental craft one must articulate every minimalist blueprint with rigorous discipline and patient determination",
    "The integration of minimalist blueprint within modern monumental craft enables practitioners to articulate critical milestones without sacrificing enduring quality",
    "Throughout the evolution of monumental craft master practitioners learned to articulate the most intricate minimalist blueprint through persistent dedicated effort",
    "Developing comprehensive understanding of monumental craft demands that professionals articulate each minimalist blueprint with profound analytical rigor and integrity",
    "When confronting complex challenges in bauhaus design one must balance every gothic scaffold with rigorous discipline and patient determination",
    "The integration of gothic scaffold within modern bauhaus design enables practitioners to balance critical milestones without sacrificing enduring quality",
    "Throughout the evolution of bauhaus design master practitioners learned to balance the most intricate gothic scaffold through persistent dedicated effort",
    "Developing comprehensive understanding of bauhaus design demands that professionals balance each gothic scaffold with profound analytical rigor and integrity",
    "When confronting complex challenges in modernist form one must renovate every monumental column with rigorous discipline and patient determination",
    "The integration of monumental column within modern modernist form enables practitioners to renovate critical milestones without sacrificing enduring quality",
    "Throughout the evolution of modernist form master practitioners learned to renovate the most intricate monumental column through persistent dedicated effort",
    "Developing comprehensive understanding of modernist form demands that professionals renovate each monumental column with profound analytical rigor and integrity",
    "When confronting complex challenges in spatial design one must elevate every sustainable atrium with rigorous discipline and patient determination"
  ]
};

export async function seed() {
  return await upsertCategoryAndSentences(category, sentences);
}

if (process.argv[1]?.endsWith('architecture.mjs')) {
  seed().catch(console.error);
}
