import { upsertCategoryAndSentences } from './seed-helper.mjs';

export const category = {
  "slug": "business",
  "label": "Business & Startups",
  "icon": "💼",
  "description": "Venture capital, pitch decks, leadership, and market strategy",
  "display_order": 17
};

export const sentences = {
  "easy": [
    "Customers always come first",
    "Validate your product idea",
    "Scale operations with care",
    "Cash flow keeps doors",
    "Hire for culture fit",
    "Deliver value every day",
    "Pitch to angel investors",
    "Close the funding round",
    "Build minimum viable product",
    "Listen to customer feedback",
    "Iterate based on metrics",
    "Track key performance indicators",
    "Reduce customer churn rate",
    "Improve lifetime customer value",
    "Launch marketing campaign today",
    "Expand into new markets",
    "Optimize sales conversion funnel",
    "Negotiate partnership deal terms",
    "Protect intellectual property assets",
    "Lead with transparent integrity",
    "validate the profitable strategy",
    "profitable strategy validate venture capital",
    "strategy brings profitable venture capital",
    "Always validate profitable strategy",
    "Every strategy can validate",
    "scale the scalable founder",
    "scalable founder scale market expansion",
    "founder brings scalable market expansion",
    "Always scale scalable founder",
    "Every founder can scale",
    "pivot the strategic revenue",
    "strategic revenue pivot startup velocity",
    "revenue brings strategic startup velocity",
    "Always pivot strategic revenue",
    "Every revenue can pivot",
    "accelerate the innovative metric",
    "innovative metric accelerate enterprise growth",
    "metric brings innovative enterprise growth",
    "Always accelerate innovative metric",
    "Every metric can accelerate",
    "negotiate the disruptive milestone",
    "disruptive milestone negotiate board governance",
    "milestone brings disruptive board governance",
    "Always negotiate disruptive milestone",
    "Every milestone can negotiate",
    "execute the sustainable equity",
    "sustainable equity execute product strategy",
    "equity brings sustainable product strategy",
    "Always execute sustainable equity",
    "Every equity can execute",
    "streamline the lucrative roadmap",
    "lucrative roadmap streamline venture capital",
    "roadmap brings lucrative venture capital",
    "Always streamline lucrative roadmap",
    "Every roadmap can streamline",
    "optimize the agile partnership",
    "agile partnership optimize market expansion",
    "partnership brings agile market expansion",
    "Always optimize agile partnership",
    "Every partnership can optimize",
    "fundraise the fiduciary market",
    "fiduciary market fundraise startup velocity",
    "market brings fiduciary startup velocity",
    "Always fundraise fiduciary market",
    "Every market can fundraise",
    "diversify the resilient dividend",
    "resilient dividend diversify enterprise growth",
    "dividend brings resilient enterprise growth",
    "Always diversify resilient dividend",
    "Every dividend can diversify",
    "profitable strategy validate board governance",
    "strategy brings profitable board governance",
    "scalable founder scale product strategy",
    "founder brings scalable product strategy",
    "strategic revenue pivot venture capital",
    "revenue brings strategic venture capital",
    "innovative metric accelerate market expansion",
    "metric brings innovative market expansion",
    "disruptive milestone negotiate startup velocity",
    "milestone brings disruptive startup velocity",
    "sustainable equity execute enterprise growth",
    "equity brings sustainable enterprise growth",
    "lucrative roadmap streamline board governance",
    "roadmap brings lucrative board governance",
    "agile partnership optimize product strategy",
    "partnership brings agile product strategy",
    "fiduciary market fundraise venture capital",
    "market brings fiduciary venture capital",
    "resilient dividend diversify market expansion",
    "dividend brings resilient market expansion",
    "profitable strategy validate startup velocity",
    "strategy brings profitable startup velocity",
    "scalable founder scale enterprise growth",
    "founder brings scalable enterprise growth",
    "strategic revenue pivot board governance",
    "revenue brings strategic board governance",
    "innovative metric accelerate product strategy",
    "metric brings innovative product strategy",
    "disruptive milestone negotiate venture capital",
    "milestone brings disruptive venture capital"
  ],
  "normal": [
    "Focus relentlessly on solving a real urgent problem for users",
    "A minimum viable product accelerates empirical learning from real customers",
    "Product market fit is the true engine of sustainable growth",
    "Great company culture attracts and retains exceptional world class talent",
    "Early customer feedback prevents teams from building unwanted software features",
    "Unit economics must turn positive before scaling paid acquisition marketing",
    "Delegating authority empowers team leads to make fast autonomous decisions",
    "Strategic positioning distinguishes your offering in crowded competitive consumer markets",
    "Cash flow management ensures startups survive unexpected macroeconomic winter downturns",
    "Building trust with enterprise clients requires delivering reliable consistent value",
    "The profitable strategy will greatly validate our venture capital today",
    "Every profitable strategy must validate carefully across the entire venture",
    "Learning how to validate profitable strategy inspires deep venture capital",
    "Our dedicated team will validate the profitable strategy for venture",
    "The scalable founder will greatly scale our market expansion today",
    "Every scalable founder must scale carefully across the entire market",
    "Learning how to scale scalable founder inspires deep market expansion",
    "Our dedicated team will scale the scalable founder for market",
    "The strategic revenue will greatly pivot our startup velocity today",
    "Every strategic revenue must pivot carefully across the entire startup",
    "Learning how to pivot strategic revenue inspires deep startup velocity",
    "Our dedicated team will pivot the strategic revenue for startup",
    "The innovative metric will greatly accelerate our enterprise growth today",
    "Every innovative metric must accelerate carefully across the entire enterprise",
    "Learning how to accelerate innovative metric inspires deep enterprise growth",
    "Our dedicated team will accelerate the innovative metric for enterprise",
    "The disruptive milestone will greatly negotiate our board governance today",
    "Every disruptive milestone must negotiate carefully across the entire board",
    "Learning how to negotiate disruptive milestone inspires deep board governance",
    "Our dedicated team will negotiate the disruptive milestone for board",
    "The sustainable equity will greatly execute our product strategy today",
    "Every sustainable equity must execute carefully across the entire product",
    "Learning how to execute sustainable equity inspires deep product strategy",
    "Our dedicated team will execute the sustainable equity for product",
    "The lucrative roadmap will greatly streamline our venture capital today",
    "Every lucrative roadmap must streamline carefully across the entire venture",
    "Learning how to streamline lucrative roadmap inspires deep venture capital",
    "Our dedicated team will streamline the lucrative roadmap for venture",
    "The agile partnership will greatly optimize our market expansion today",
    "Every agile partnership must optimize carefully across the entire market",
    "Learning how to optimize agile partnership inspires deep market expansion",
    "Our dedicated team will optimize the agile partnership for market",
    "The fiduciary market will greatly fundraise our startup velocity today",
    "Every fiduciary market must fundraise carefully across the entire startup",
    "Learning how to fundraise fiduciary market inspires deep startup velocity",
    "Our dedicated team will fundraise the fiduciary market for startup",
    "The resilient dividend will greatly diversify our enterprise growth today",
    "Every resilient dividend must diversify carefully across the entire enterprise",
    "Learning how to diversify resilient dividend inspires deep enterprise growth",
    "Our dedicated team will diversify the resilient dividend for enterprise",
    "The profitable strategy will greatly validate our board governance today",
    "Every profitable strategy must validate carefully across the entire board",
    "Learning how to validate profitable strategy inspires deep board governance",
    "Our dedicated team will validate the profitable strategy for board",
    "The scalable founder will greatly scale our product strategy today",
    "Every scalable founder must scale carefully across the entire product",
    "Learning how to scale scalable founder inspires deep product strategy",
    "Our dedicated team will scale the scalable founder for product",
    "The strategic revenue will greatly pivot our venture capital today",
    "Every strategic revenue must pivot carefully across the entire venture",
    "Learning how to pivot strategic revenue inspires deep venture capital",
    "Our dedicated team will pivot the strategic revenue for venture",
    "The innovative metric will greatly accelerate our market expansion today",
    "Every innovative metric must accelerate carefully across the entire market",
    "Learning how to accelerate innovative metric inspires deep market expansion",
    "Our dedicated team will accelerate the innovative metric for market",
    "The disruptive milestone will greatly negotiate our startup velocity today",
    "Every disruptive milestone must negotiate carefully across the entire startup",
    "Learning how to negotiate disruptive milestone inspires deep startup velocity",
    "Our dedicated team will negotiate the disruptive milestone for startup"
  ],
  "hard": [
    "Move fast and iterate quickly while listening attentively to candid criticism and feedback from your earliest passionate adopters",
    "The most successful entrepreneurs embrace calculated risks and view painful initial setbacks as valuable educational data for pivoting",
    "Sustainable competitive advantage stems from proprietary technology strong network effects or enduring brand loyalty developed over decades",
    "Pitch decks must clearly articulate market size customer pain points unique differentiation and transparent path toward profitable scalability",
    "Delegating authority empowers talented team members to solve ambiguous organizational challenges without creating bureaucratic executive bottlenecks",
    "When confronting complex challenges in venture capital one must validate every profitable strategy with rigorous discipline and patient determination",
    "The integration of profitable strategy within modern venture capital enables practitioners to validate critical milestones without sacrificing enduring quality",
    "Throughout the evolution of venture capital master practitioners learned to validate the most intricate profitable strategy through persistent dedicated effort",
    "Developing comprehensive understanding of venture capital demands that professionals validate each profitable strategy with profound analytical rigor and integrity",
    "When confronting complex challenges in market expansion one must scale every scalable founder with rigorous discipline and patient determination",
    "The integration of scalable founder within modern market expansion enables practitioners to scale critical milestones without sacrificing enduring quality",
    "Throughout the evolution of market expansion master practitioners learned to scale the most intricate scalable founder through persistent dedicated effort",
    "Developing comprehensive understanding of market expansion demands that professionals scale each scalable founder with profound analytical rigor and integrity",
    "When confronting complex challenges in startup velocity one must pivot every strategic revenue with rigorous discipline and patient determination",
    "The integration of strategic revenue within modern startup velocity enables practitioners to pivot critical milestones without sacrificing enduring quality",
    "Throughout the evolution of startup velocity master practitioners learned to pivot the most intricate strategic revenue through persistent dedicated effort",
    "Developing comprehensive understanding of startup velocity demands that professionals pivot each strategic revenue with profound analytical rigor and integrity",
    "When confronting complex challenges in enterprise growth one must accelerate every innovative metric with rigorous discipline and patient determination",
    "The integration of innovative metric within modern enterprise growth enables practitioners to accelerate critical milestones without sacrificing enduring quality",
    "Throughout the evolution of enterprise growth master practitioners learned to accelerate the most intricate innovative metric through persistent dedicated effort",
    "Developing comprehensive understanding of enterprise growth demands that professionals accelerate each innovative metric with profound analytical rigor and integrity",
    "When confronting complex challenges in board governance one must negotiate every disruptive milestone with rigorous discipline and patient determination",
    "The integration of disruptive milestone within modern board governance enables practitioners to negotiate critical milestones without sacrificing enduring quality",
    "Throughout the evolution of board governance master practitioners learned to negotiate the most intricate disruptive milestone through persistent dedicated effort",
    "Developing comprehensive understanding of board governance demands that professionals negotiate each disruptive milestone with profound analytical rigor and integrity",
    "When confronting complex challenges in product strategy one must execute every sustainable equity with rigorous discipline and patient determination",
    "The integration of sustainable equity within modern product strategy enables practitioners to execute critical milestones without sacrificing enduring quality",
    "Throughout the evolution of product strategy master practitioners learned to execute the most intricate sustainable equity through persistent dedicated effort",
    "Developing comprehensive understanding of product strategy demands that professionals execute each sustainable equity with profound analytical rigor and integrity",
    "When confronting complex challenges in venture capital one must streamline every lucrative roadmap with rigorous discipline and patient determination"
  ]
};

export async function seed() {
  return await upsertCategoryAndSentences(category, sentences);
}

if (process.argv[1]?.endsWith('business.mjs')) {
  seed().catch(console.error);
}
