import { upsertCategoryAndSentences } from './seed-helper.mjs';

export const category = {
  "slug": "casual",
  "label": "Casual Daily",
  "icon": "☀️",
  "description": "Everyday phrases, polite greetings, and common chatter",
  "display_order": 1
};

export const sentences = {
  "easy": [
    "Good morning everyone",
    "How are you today",
    "See you tomorrow morning",
    "Take care of yourself",
    "Keep in touch often",
    "Call me back later",
    "Time to wake up",
    "Dinner is ready now",
    "Enjoy your fresh meal",
    "Catch you later friend",
    "Thanks for your help",
    "Nice to meet you",
    "Have a nice flight",
    "Please wait outside here",
    "I need some water",
    "The bus is here",
    "Let us eat lunch",
    "What a wonderful day",
    "Sounds good to me",
    "Turn on the lights",
    "Sleep well tonight friend",
    "Have fun this evening",
    "Keep up good work",
    "Coffee smells so good",
    "Welcome to our neighborhood",
    "Grab your warm coat",
    "The sun is shining",
    "Let me know soon",
    "I am feeling great",
    "Walk with me today",
    "Put on your shoes",
    "Open the front window",
    "Pack your school bag",
    "Wash your hands first",
    "Turn off the television",
    "The weather is nice",
    "I need some groceries",
    "Let me check schedule",
    "Pass the salt please",
    "I will arrive soon",
    "Have a great weekend",
    "Where did you park",
    "Finished my morning coffee",
    "Grab lunch together soon",
    "The train arrives soon",
    "Close the wooden door",
    "Forgot my small umbrella",
    "Meeting starts right now",
    "Can we reschedule tomorrow",
    "Running a bit late",
    "Store closes at nine",
    "Take shortcut through park",
    "See the morning news",
    "Head home right now",
    "Traffic was very bad",
    "Carry these paper bags",
    "Left phone on counter",
    "Movie starts at seven",
    "Pizza arrives any minute",
    "Charge my laptop battery",
    "Remember her special birthday",
    "Kids playing in yard",
    "Dentist appointment this afternoon",
    "Try that new restaurant",
    "Lock the garage door",
    "Bake fresh berry muffins",
    "Pour another cup tea",
    "Wipe the kitchen table",
    "Fold the clean clothes",
    "Sweep the front porch",
    "Feed the hungry puppy",
    "Water the red flowers",
    "Turn on garden sprinkler",
    "Listen to radio show",
    "Read the daily newspaper",
    "Check the mailbox outside",
    "Pick up fresh bread",
    "Buy some sweet apples",
    "Chop the fresh carrots",
    "Heat the vegetable soup",
    "Set the dining table",
    "Clear the dirty dishes",
    "Dry the wet towels",
    "Make your cozy bed",
    "Iron your clean shirt",
    "Tie your sneaker laces",
    "Brush your teeth well",
    "Comb your messy hair",
    "Check the bus schedule",
    "Look at morning sky",
    "Feel the gentle breeze",
    "Watch the sunset glow",
    "Stars shine bright tonight",
    "Turn off night lamp",
    "Set the morning alarm",
    "Rest your tired eyes",
    "Dreams come true always",
    "Peaceful night to all",
    "Wake with joyful heart",
    "Ready for new day"
  ],
  "normal": [
    "I am going to the grocery store right now",
    "Could you please send me that recipe later",
    "Let me know when you arrive at the station",
    "We are planning a small picnic this coming Saturday",
    "I forgot to turn off the kitchen lights downstairs",
    "Do you prefer drinking hot tea or iced coffee",
    "It looks like it might rain later this afternoon",
    "Can you pick up some fresh milk on your way",
    "I need to take the dog out for a walk",
    "Let us meet at the coffee shop around noon",
    "She recommended a really great book for me to read",
    "How was your trip to the coast last weekend",
    "Please remember to lock the front door when leaving",
    "I had a really productive afternoon at the office",
    "What time does the movie start at the cinema",
    "I think I left my keys on the counter",
    "We should order takeout for dinner tonight instead of cooking",
    "The train was surprisingly on time during morning rush",
    "My phone battery is running low so charge it",
    "Let me check what we have in the refrigerator",
    "I am looking forward to seeing everyone this holiday",
    "He baked homemade chocolate chip cookies for the party",
    "Could you turn down the volume just a bit",
    "I usually take a quick walk during lunch break",
    "The morning air feels remarkably crisp and refreshing today",
    "Don’t forget your warm jacket because it gets chilly",
    "We spent the entire evening chatting on the porch",
    "Can someone help me move this heavy wooden table",
    "I finally finished folding all of the clean laundry",
    "That was one of the funniest stories I heard",
    "I need to buy a birthday card this afternoon",
    "Did anyone remember to water the house plants today",
    "Let us take the stairs instead of the elevator",
    "I hope you have a relaxing and peaceful Sunday",
    "It took twenty minutes to find a parking spot",
    "Can you grab an extra napkin from the dispenser",
    "We should catch up properly over dinner next week",
    "The flowers in the garden are starting to bloom",
    "I always enjoy listening to gentle acoustic guitar music",
    "Everything went according to the original plan this morning",
    "Can you help me carry these heavy grocery bags inside",
    "The kids are having fun building castles in the sandbox",
    "I will call you back as soon as I finish",
    "There is a brand new coffee shop opening down street",
    "We decided to watch a comedy film after dinner tonight",
    "She bought a beautiful blue dress for the wedding reception",
    "Remember to put on sunscreen before walking to the beach",
    "I prefer taking public transit rather than driving during rush",
    "The smell of freshly brewed coffee filled the entire room",
    "He always takes his time cooking a wholesome weekend breakfast",
    "Could you grab an umbrella in case it rains today",
    "Our flight was delayed by thirty minutes due to weather",
    "They spent the afternoon wandering through the local farmers market",
    "Please make sure the cat has fresh water and food",
    "I love taking quiet morning strolls before the city wakes",
    "We enjoyed a delicious homemade dinner with our close friends",
    "Can we stop by the pharmacy on our way home",
    "She received a heartwarming postcard from her grandparents in Italy",
    "The autumn leaves are turning vibrant shades of red gold",
    "I need to schedule an appointment with the dentist soon",
    "Let us sit outside and enjoy this pleasant sunny weather",
    "He forgot his reading glasses on his office writing desk",
    "They are planning a weekend camping trip near the lake",
    "Please wipe the dining table after you finish your meal",
    "I listened to an inspiring podcast during my daily commute",
    "She always shares the most wonderful homemade baking treats with us",
    "We stopped by the bakery to pick up warm croissants",
    "It is always a pleasure catching up with old friends",
    "Could you turn on the porch light before it darkens",
    "I am looking forward to sleeping in late tomorrow morning"
  ],
  "hard": [
    "I was thinking we could invite our neighbors over for a casual backyard barbecue this weekend",
    "If you have some free time this afternoon could you help me assemble this new bookshelf",
    "The grocery store was completely out of ripe avocados so I had to buy green ones instead",
    "Whenever the weather gets this warm I love sitting on the balcony reading a good novel",
    "Make sure you set your alarm clock fifteen minutes earlier so you do not miss the bus",
    "We had to wait in line for nearly forty minutes just to order our morning coffee",
    "I ran into an old high school friend while shopping at the supermarket yesterday afternoon",
    "Could you please double check if the garage door is completely closed before you go to sleep",
    "After walking through the botanical gardens all morning we stopped at a quiet little noodle place",
    "It has been such a hectic week at work that I cannot wait to sleep in tomorrow",
    "I promised my sister I would water her houseplants and feed her cat while she is away",
    "The local farmers market on Saturday mornings always has the sweetest fresh strawberries and homemade pastries",
    "We decided to take the scenic coastal highway instead of rushing down the crowded toll road",
    "Before we head out for the day let us make sure we packed sunscreen and water bottles",
    "She spent the rainy afternoon organizing old family photo albums and sipping hot peppermint tea",
    "If everyone chips in to clean up the kitchen we will finish in no time at all",
    "I usually try to stretch for ten minutes right after waking up to get my energy going",
    "The neighborhood bakery down the street opens at sunrise and fills the entire block with fresh bread aromas",
    "We should probably leave twenty minutes ahead of schedule to account for potential highway construction delays",
    "It was so relaxing to sit by the open window and listen to the gentle evening rain",
    "Can you remind me to pick up the dry cleaning tomorrow morning on the way to work",
    "Cooking a hearty homemade soup from scratch takes patience but the delicious flavor is always worth the effort",
    "Everyone gathered in the cozy living room with warm mugs of cider to play board games together",
    "After spending all day unpacking cardboard boxes we finally settled down to enjoy our very first home dinner",
    "Taking a slow evening stroll around the quiet neighborhood block helps clear my head before heading to sleep",
    "We spent hours sitting around the campfire telling funny childhood stories under a canopy of twinkling stars",
    "She spent the entire morning searching through drawers looking for her favorite pair of silver earrings",
    "Having a warm cup of herbal chamomile tea before bedtime is my favorite way to unwind completely",
    "The children were so excited about the upcoming family vacation that they could barely fall asleep last night",
    "A quiet weekend afternoon spent tending the garden brings more peace than any crowded downtown shopping mall"
  ]
};

export async function seed() {
  return await upsertCategoryAndSentences(category, sentences);
}

if (process.argv[1]?.endsWith('casual.mjs')) {
  seed().catch(console.error);
}
