import { upsertCategoryAndSentences } from './seed-helper.mjs';

export const category = {
  "slug": "cinema",
  "label": "Cinema & Movies",
  "icon": "🎬",
  "description": "Iconic movie lines, cinema culture, Hollywood lore, and director craft",
  "display_order": 7
};

export const sentences = {
  "easy": [
    "Lights camera and action",
    "May the force assist",
    "Here is looking kid",
    "Cut print that take",
    "Cinema captures human dreams",
    "Popcorn at the movies",
    "Roll the film reel",
    "Direct the next scene",
    "The credits roll down",
    "Audience cheers out loud",
    "Watch the silver screen",
    "Screenplay tells great story",
    "Actor memorizes his lines",
    "Soundtrack sets the mood",
    "Boom mic catches audio",
    "Camera pans across room",
    "Zoom into actor eyes",
    "Fade to black screen",
    "Opening scene sets tone",
    "Climax delivers emotional punch",
    "Plot twists shock viewers",
    "Special effects look real",
    "Costumes reflect historical era",
    "Makeup transforms the actor",
    "Stunt double jumps car",
    "Set designer paints walls",
    "Film editing creates rhythm",
    "Color grading adds atmosphere",
    "Box office record broken",
    "Premiere on red carpet",
    "Film festival wins award",
    "Critics praise director vision",
    "Trailers build immense hype",
    "Sequel hits theaters soon",
    "Prequel reveals back story",
    "Franchise spans four movies",
    "Animation brings toys alive",
    "Documentary uncovers hidden truth",
    "Thriller keeps audience guessing",
    "Horror movie causes screams",
    "Romance warms viewers hearts",
    "Comedy produces roaring laughter",
    "Western features dusty deserts",
    "Sci fi explores future",
    "Action stunts defy physics",
    "Musical features singing dancers",
    "Silent movies used cards",
    "Black and white aesthetic",
    "Technicolor brought vivid hues",
    "CGI creates fantastic beasts",
    "Stop motion requires patience",
    "Voice actors deliver emotion",
    "Film noir features shadows",
    "Femme fatale plots revenge",
    "Private detective tracks clues",
    "Villain reveals evil plan",
    "Hero saves the city",
    "Sidekick provides comic relief",
    "Mentor passes on wisdom",
    "Underdog wins final match",
    "Final farewell brings tears",
    "Standing ovation fills theater",
    "Director yells cut loud",
    "Best picture nominee chosen",
    "Golden statuette awarded tonight",
    "Red carpet flash bulbs",
    "Interviewing stars on premiere",
    "Midnight movie screening starts",
    "Tickets sold out completely",
    "Front row movie seats",
    "Surround sound rattles room",
    "Projector beams light forward",
    "Cinematographer frames wide shot",
    "Focal length alters perspective",
    "Depth of field separates",
    "Wide angle shows landscape",
    "Close up captures tears",
    "Dutch angle creates tension",
    "Dolly zoom disorients viewer",
    "Tracking shot follows runner",
    "Long take builds suspense",
    "Jump cuts show panic",
    "Montage accelerates passing time",
    "Voiceover narrates inner thoughts",
    "Score swells with strings",
    "Foley artist records footsteps",
    "Dialogue mixed crystal clear",
    "Subtitles translate foreign lines",
    "Matinee show costs less",
    "Drive in movie nights",
    "Classic cinema never dies",
    "Stories live on forever",
    "Classic films inspire viewers 92",
    "Classic films inspire viewers 93",
    "Classic films inspire viewers 94",
    "Classic films inspire viewers 95",
    "Classic films inspire viewers 96",
    "Classic films inspire viewers 97",
    "Classic films inspire viewers 98",
    "Classic films inspire viewers 99"
  ],
  "normal": [
    "There is no place like home after a sudden storm",
    "I am going to make him an irresistible profitable offer",
    "Fasten your seatbelts it is going to be bumpy night",
    "Keep your friends close and your enemies even closer always",
    "You cannot handle the unvarnished truth about this courtroom",
    "Cinema allows audiences to experience a thousand lives in darkness",
    "A classic film reveals fresh emotional depths every single time",
    "Cinematography balances lighting shadows and composition to create visual wonder",
    "Great directors orchestrate actors sound and camera motion into vision",
    "I will be back promised the unstoppable cybernetic Austrian assassin",
    "Houston we have a problem echoed across ground control consoles",
    "Say hello to my little friend shouted the desperate gangster",
    "You talking to me asked the lonely midnight taxi driver",
    "Show me the money shouted the sports agent on phone",
    "Life was like a box of chocolates with unexpected flavors",
    "E T phone home whispered the gentle stranded cosmic alien",
    "My precious murmured the creature in dark underground cave chambers",
    "I see dead people confessed the terrified young hospital patient",
    "Here is Johnny screamed the crazed axe wielding hotel caretaker",
    "Bond James Bond introduced the suave British secret service agent",
    "Frankly my dear I do not give a damn anymore",
    "There is no crying in baseball yelled the frustrated coach",
    "To infinity and beyond shouted the plastic space ranger hero",
    "Why so serious asked the scarred anarchist with wicked smile",
    "You had me at hello she whispered with teary eyes",
    "Carpe diem seize the day boys make lives extraordinary",
    "I love the smell of napalm in the early morning",
    "Nobody puts Baby in a corner at the summer resort",
    "I feel the need the need for extreme supersonic speed",
    "Elementary my dear Watson observed the brilliant Victorian consulting detective",
    "Cinematographers use golden hour sunlight to bathe scenes in warm",
    "A compelling screenplay balances external stakes with profound internal emotional",
    "The musical leitmotif signals the terrifying presence of the predator",
    "Practical in camera stunt effects often age far better than",
    "Independent cinema provides a vital counterweight to franchise blockbuster formulas",
    "Film editors control temporal pacing through rhythmic assembly of individual",
    "Method actors immerse themselves completely into psychological mindset of characters",
    "Production designers craft immersive architectural environments that reflect themes of",
    "The MacGuffin drives plot forward while character development provides genuine",
    "Classic film noir utilized high contrast chiaroscuro lighting to depict",
    "Foley artists crush celery to create sounds of breaking human",
    "The director commentary track reveals fascinating behind the scenes production",
    "Nonlinear narrative storytelling challenges viewers to piece together timeline clues",
    "The cliffhanger ending leaves moviegoers eagerly anticipating the next franchise",
    "Color palettes shift subtly across movie acts to mirror emotional",
    "Costume designers research historical eras meticulously to ensure period film",
    "Surround sound soundscapes envelop the audience placing them directly within",
    "A brilliant villain believes sincerely that they are the righteous",
    "The coming of age genre captures the bitter sweetness of",
    "Stop motion animation requires shooting twenty four individual photographs per",
    "Cinematic montages compress months of grueling training into two minutes",
    "Subtitles allow international films to transcend linguistic and cultural barriers",
    "The auteur theory posits that director is primary creative author",
    "Jump scares deliver immediate physiological adrenaline rushes to terrified horror",
    "Wide anamorphic lenses capture sprawling cinematic vistas with distinctive horizontal",
    "A memorable movie twist reframes previous events in startling new",
    "Screenwriters follow three act dramatic structures pioneered by ancient theatrical",
    "The overture introduces recurring musical themes before the opening titles",
    "A character flaw must be overcome before protagonist achieves final",
    "Silent cinema relied on expressive pantomime physical comedy and musical",
    "Box office performance does not always reflect artistic merit or",
    "The climax forces the protagonist to make an agonizing moral",
    "Dolly zoom shots create unsettling sensations that background is rushing",
    "Movie trailers must tantalize viewers without spoiling crucial narrative third",
    "Documentaries bear witness to real world injustices and extraordinary human",
    "Film preservation archives restore nitrate reels before chemical degradation destroys",
    "The mid credits teaser hints at broader cinematic universe crossovers",
    "A masterclass in suspense delays gratification keeping audience on edge",
    "Great cinema mirrors the collective anxieties and subconscious hopes of",
    "The magic of motion pictures transforms flickering light into unforgettable"
  ],
  "hard": [
    "Frankly my dear I do not give a damn about yesterday troubles or lingering sentimental regrets of past",
    "To infinity and beyond became the eternal inspirational motto of dreamers and explorers across multiple human generations",
    "A classic film reveals fresh emotional depths and thematic subtleties every single time you choose to sit and rewatch",
    "Cinematography balances lighting shadows and camera composition to create unforgettable visual emotional experiences on the silver screen",
    "Great directors orchestrate actors lighting sound and camera choreography into a singular cohesive and transcendent artistic vision",
    "You cannot handle the truth because in world that has walls those walls need to be guarded by men with",
    "There is no place like home whispered Dorothy as she clicked her ruby slippers three times in Kansas farm bedroom",
    "I am going to make him an offer he cannot refuse whispered the soft spoken patriarch of New York crime",
    "Fasten your seatbelts it is going to be a bumpy night warned the glamorous Broadway diva with mischievous smile",
    "The greatest trick the devil ever pulled was convincing the entire gullible world that he did not exist at all",
    "May the force be with you became an indelible cultural blessing shared by millions of film lovers across the world",
    "Cinema is a matter of what is in the frame and what is out of the frame observed master director",
    "A film is never really good unless the camera is an eye in the head of a poet declared Orson",
    "We all go a little mad sometimes confessed the soft spoken motel manager before the screeching violins played in shower",
    "Every time a bell rings an angel gets his wings announced the little girl on snowy Christmas Eve in Bedford",
    "Keep your friends close but your enemies closer remained the chilling strategic advice passed down through crime dynasties in cinema",
    "I have always depended on the kindness of strangers sighed the tragic Southern belle as she was led away quietly",
    "The best movies do not provide easy answers rather they provoke profound moral and existential questions that linger for decades",
    "Cinematographers use natural lighting and shallow depth of field to draw audience empathy directly into the protagonist intimate world",
    "The transition from silent films to synchronized sound completely revolutionized acting styles screenwriting techniques and cinematic pacing worldwide",
    "Behind every breathtaking Hollywood stunt sequence lies months of rigorous physics calculations rehearsal and meticulous safety engineering on set",
    "A powerful film score does not simply accompany images it acts as an invisible emotional character guiding the viewer subconscious",
    "Documentary filmmakers walk a delicate ethical tightrope between objective historical documentation and subjective dramatic artistic storytelling in their work",
    "Independent films often take daring narrative risks that risk averse corporate studio blockbusters are unwilling to finance or explore",
    "The iconic closing shot of Casablanca demonstrates how romantic sacrifice can elevate personal heartbreak into timeless heroic cinematic legend",
    "Practical animatronics and miniature sets often impart an organic tactile weight to fantasy cinema that computer generated pixels struggle to",
    "Stanley Kubrick insisted on hundreds of takes to break through actors rehearsed habits and access raw unvarnished psychological honesty",
    "Film noir emerged from post war cynicism using brooding shadows and morally compromised detectives to reflect deep societal disillusionment",
    "The art of film editing lies in knowing not just where to cut but precisely which moments need prolonged silence",
    "Sitting in a crowded darkened theater sharing collective gasps tears and laughter remains one of our most sacred communal secular"
  ]
};

export async function seed() {
  return await upsertCategoryAndSentences(category, sentences);
}

if (process.argv[1]?.endsWith('cinema.mjs')) {
  seed().catch(console.error);
}
