import { upsertCategoryAndSentences } from './seed-helper.mjs';

export const category = {
  "slug": "culinary",
  "label": "Culinary Arts",
  "icon": "🍳",
  "description": "Gourmet cooking, secret recipes, aromatic spices, and baking",
  "display_order": 14
};

export const sentences = {
  "easy": [
    "Season food with love",
    "Bake bread until golden",
    "Sharp knives prevent accidents",
    "Simmer soup on low",
    "Fresh herbs elevate taste",
    "Taste dishes while cooking",
    "Whisk eggs until fluffy",
    "Knead sourdough dough well",
    "Caramelize onions with butter",
    "Sear steak on iron",
    "Roast vegetables with rosemary",
    "Steam dumplings over water",
    "Chop garlic very finely",
    "Dice sweet yellow onions",
    "Grate fresh parmesan cheese",
    "Zest lemon for aroma",
    "Melt dark chocolate slowly",
    "Sift flour before baking",
    "Proof yeast with sugar",
    "Chill pastry in fridge",
    "simmer the savory recipe",
    "savory recipe simmer culinary craft",
    "recipe brings savory culinary craft",
    "Always simmer savory recipe",
    "Every recipe can simmer",
    "caramelize the aromatic spice",
    "aromatic spice caramelize baking science",
    "spice brings aromatic baking science",
    "Always caramelize aromatic spice",
    "Every spice can caramelize",
    "whisk the crispy sauce",
    "crispy sauce whisk flavor profile",
    "sauce brings crispy flavor profile",
    "Always whisk crispy sauce",
    "Every sauce can whisk",
    "garnish the gourmet dough",
    "gourmet dough garnish kitchen prep",
    "dough brings gourmet kitchen prep",
    "Always garnish gourmet dough",
    "Every dough can garnish",
    "infuse the delicious skillet",
    "delicious skillet infuse gourmet banquet",
    "skillet brings delicious gourmet banquet",
    "Always infuse delicious skillet",
    "Every skillet can infuse",
    "roast the wholesome flavor",
    "wholesome flavor roast rustic feast",
    "flavor brings wholesome rustic feast",
    "Always roast wholesome flavor",
    "Every flavor can roast",
    "sauté the tender herb",
    "tender herb sauté culinary craft",
    "herb brings tender culinary craft",
    "Always sauté tender herb",
    "Every herb can sauté",
    "braise the golden pastry",
    "golden pastry braise baking science",
    "pastry brings golden baking science",
    "Always braise golden pastry",
    "Every pastry can braise",
    "season the velvety broth",
    "velvety broth season flavor profile",
    "broth brings velvety flavor profile",
    "Always season velvety broth",
    "Every broth can season",
    "emulsify the fluffy marinade",
    "fluffy marinade emulsify kitchen prep",
    "marinade brings fluffy kitchen prep",
    "Always emulsify fluffy marinade",
    "Every marinade can emulsify",
    "savory recipe simmer gourmet banquet",
    "recipe brings savory gourmet banquet",
    "aromatic spice caramelize rustic feast",
    "spice brings aromatic rustic feast",
    "crispy sauce whisk culinary craft",
    "sauce brings crispy culinary craft",
    "gourmet dough garnish baking science",
    "dough brings gourmet baking science",
    "delicious skillet infuse flavor profile",
    "skillet brings delicious flavor profile",
    "wholesome flavor roast kitchen prep",
    "flavor brings wholesome kitchen prep",
    "tender herb sauté gourmet banquet",
    "herb brings tender gourmet banquet",
    "golden pastry braise rustic feast",
    "pastry brings golden rustic feast",
    "velvety broth season culinary craft",
    "broth brings velvety culinary craft",
    "fluffy marinade emulsify baking science",
    "marinade brings fluffy baking science",
    "savory recipe simmer flavor profile",
    "recipe brings savory flavor profile",
    "aromatic spice caramelize kitchen prep",
    "spice brings aromatic kitchen prep",
    "crispy sauce whisk gourmet banquet",
    "sauce brings crispy gourmet banquet",
    "gourmet dough garnish rustic feast",
    "dough brings gourmet rustic feast",
    "delicious skillet infuse culinary craft",
    "skillet brings delicious culinary craft"
  ],
  "normal": [
    "The secret to crispy pastry is keeping butter cold throughout",
    "Caramelizing onions requires gentle heat and steady quiet kitchen patience",
    "A pinch of sea salt balances bitter rich dark chocolate",
    "Proper knife technique speeds up kitchen preparation remarkably and safely",
    "Cast iron skillets retain heat for perfect golden steak sears",
    "Fresh sourdough relies on wild yeast and slow cold fermentation",
    "Emulsifying olive oil and vinegar creates a velvety salad vinaigrette",
    "Toasting whole spices in dry pan unlocks vibrant aromatic essential",
    "Resting cooked meat allows savory flavorful juices to redistribute evenly",
    "Fresh herbs should be added at the end of cooking",
    "The savory recipe will greatly simmer our culinary craft today",
    "Every savory recipe must simmer carefully across the entire culinary",
    "Learning how to simmer savory recipe inspires deep culinary craft",
    "Our dedicated team will simmer the savory recipe for culinary",
    "The aromatic spice will greatly caramelize our baking science today",
    "Every aromatic spice must caramelize carefully across the entire baking",
    "Learning how to caramelize aromatic spice inspires deep baking science",
    "Our dedicated team will caramelize the aromatic spice for baking",
    "The crispy sauce will greatly whisk our flavor profile today",
    "Every crispy sauce must whisk carefully across the entire flavor",
    "Learning how to whisk crispy sauce inspires deep flavor profile",
    "Our dedicated team will whisk the crispy sauce for flavor",
    "The gourmet dough will greatly garnish our kitchen prep today",
    "Every gourmet dough must garnish carefully across the entire kitchen",
    "Learning how to garnish gourmet dough inspires deep kitchen prep",
    "Our dedicated team will garnish the gourmet dough for kitchen",
    "The delicious skillet will greatly infuse our gourmet banquet today",
    "Every delicious skillet must infuse carefully across the entire gourmet",
    "Learning how to infuse delicious skillet inspires deep gourmet banquet",
    "Our dedicated team will infuse the delicious skillet for gourmet",
    "The wholesome flavor will greatly roast our rustic feast today",
    "Every wholesome flavor must roast carefully across the entire rustic",
    "Learning how to roast wholesome flavor inspires deep rustic feast",
    "Our dedicated team will roast the wholesome flavor for rustic",
    "The tender herb will greatly sauté our culinary craft today",
    "Every tender herb must sauté carefully across the entire culinary",
    "Learning how to sauté tender herb inspires deep culinary craft",
    "Our dedicated team will sauté the tender herb for culinary",
    "The golden pastry will greatly braise our baking science today",
    "Every golden pastry must braise carefully across the entire baking",
    "Learning how to braise golden pastry inspires deep baking science",
    "Our dedicated team will braise the golden pastry for baking",
    "The velvety broth will greatly season our flavor profile today",
    "Every velvety broth must season carefully across the entire flavor",
    "Learning how to season velvety broth inspires deep flavor profile",
    "Our dedicated team will season the velvety broth for flavor",
    "The fluffy marinade will greatly emulsify our kitchen prep today",
    "Every fluffy marinade must emulsify carefully across the entire kitchen",
    "Learning how to emulsify fluffy marinade inspires deep kitchen prep",
    "Our dedicated team will emulsify the fluffy marinade for kitchen",
    "The savory recipe will greatly simmer our gourmet banquet today",
    "Every savory recipe must simmer carefully across the entire gourmet",
    "Learning how to simmer savory recipe inspires deep gourmet banquet",
    "Our dedicated team will simmer the savory recipe for gourmet",
    "The aromatic spice will greatly caramelize our rustic feast today",
    "Every aromatic spice must caramelize carefully across the entire rustic",
    "Learning how to caramelize aromatic spice inspires deep rustic feast",
    "Our dedicated team will caramelize the aromatic spice for rustic",
    "The crispy sauce will greatly whisk our culinary craft today",
    "Every crispy sauce must whisk carefully across the entire culinary",
    "Learning how to whisk crispy sauce inspires deep culinary craft",
    "Our dedicated team will whisk the crispy sauce for culinary",
    "The gourmet dough will greatly garnish our baking science today",
    "Every gourmet dough must garnish carefully across the entire baking",
    "Learning how to garnish gourmet dough inspires deep baking science",
    "Our dedicated team will garnish the gourmet dough for baking",
    "The delicious skillet will greatly infuse our flavor profile today",
    "Every delicious skillet must infuse carefully across the entire flavor",
    "Learning how to infuse delicious skillet inspires deep flavor profile",
    "Our dedicated team will infuse the delicious skillet for flavor"
  ],
  "hard": [
    "Cooking is an art while baking is an exact chemical science requiring precise measurements and temperature controls",
    "Mastering the five French mother sauces unlocks the foundational culinary grammar for thousands of classic gourmet kitchen recipes",
    "Freshly ground whole spices toasted in browned butter release vibrant aromatic volatile oils that transform ordinary sauces completely",
    "A master chef sharpens knives daily because clean effortless cuts preserve cellular texture and moisture of delicate ingredients",
    "The inviting aroma of simmering garlic rosemary and extra virgin olive oil fills the kitchen with timeless Mediterranean warmth",
    "When confronting complex challenges in culinary craft one must simmer every savory recipe with rigorous discipline and patient determination",
    "The integration of savory recipe within modern culinary craft enables practitioners to simmer critical milestones without sacrificing enduring quality",
    "Throughout the evolution of culinary craft master practitioners learned to simmer the most intricate savory recipe through persistent dedicated effort",
    "Developing comprehensive understanding of culinary craft demands that professionals simmer each savory recipe with profound analytical rigor and integrity",
    "When confronting complex challenges in baking science one must caramelize every aromatic spice with rigorous discipline and patient determination",
    "The integration of aromatic spice within modern baking science enables practitioners to caramelize critical milestones without sacrificing enduring quality",
    "Throughout the evolution of baking science master practitioners learned to caramelize the most intricate aromatic spice through persistent dedicated effort",
    "Developing comprehensive understanding of baking science demands that professionals caramelize each aromatic spice with profound analytical rigor and integrity",
    "When confronting complex challenges in flavor profile one must whisk every crispy sauce with rigorous discipline and patient determination",
    "The integration of crispy sauce within modern flavor profile enables practitioners to whisk critical milestones without sacrificing enduring quality",
    "Throughout the evolution of flavor profile master practitioners learned to whisk the most intricate crispy sauce through persistent dedicated effort",
    "Developing comprehensive understanding of flavor profile demands that professionals whisk each crispy sauce with profound analytical rigor and integrity",
    "When confronting complex challenges in kitchen prep one must garnish every gourmet dough with rigorous discipline and patient determination",
    "The integration of gourmet dough within modern kitchen prep enables practitioners to garnish critical milestones without sacrificing enduring quality",
    "Throughout the evolution of kitchen prep master practitioners learned to garnish the most intricate gourmet dough through persistent dedicated effort",
    "Developing comprehensive understanding of kitchen prep demands that professionals garnish each gourmet dough with profound analytical rigor and integrity",
    "When confronting complex challenges in gourmet banquet one must infuse every delicious skillet with rigorous discipline and patient determination",
    "The integration of delicious skillet within modern gourmet banquet enables practitioners to infuse critical milestones without sacrificing enduring quality",
    "Throughout the evolution of gourmet banquet master practitioners learned to infuse the most intricate delicious skillet through persistent dedicated effort",
    "Developing comprehensive understanding of gourmet banquet demands that professionals infuse each delicious skillet with profound analytical rigor and integrity",
    "When confronting complex challenges in rustic feast one must roast every wholesome flavor with rigorous discipline and patient determination",
    "The integration of wholesome flavor within modern rustic feast enables practitioners to roast critical milestones without sacrificing enduring quality",
    "Throughout the evolution of rustic feast master practitioners learned to roast the most intricate wholesome flavor through persistent dedicated effort",
    "Developing comprehensive understanding of rustic feast demands that professionals roast each wholesome flavor with profound analytical rigor and integrity",
    "When confronting complex challenges in culinary craft one must sauté every tender herb with rigorous discipline and patient determination"
  ]
};

export async function seed() {
  return await upsertCategoryAndSentences(category, sentences);
}

if (process.argv[1]?.endsWith('culinary.mjs')) {
  seed().catch(console.error);
}
