import { upsertCategoryAndSentences } from './seed-helper.mjs';

export const category = {
  "slug": "cybersecurity",
  "label": "Cybersecurity & Infosec",
  "icon": "🛡️",
  "description": "Cryptography, firewalls, zero days, threat hunting, and defense",
  "display_order": 13
};

export const sentences = {
  "easy": [
    "Always use strong passwords",
    "Patch vulnerabilities right away",
    "Verify before you trust",
    "Firewalls block malicious traffic",
    "Encrypt your sensitive data",
    "Phishing links trick users",
    "Two factor authentication enabled",
    "Monitor suspicious server logins",
    "Backup critical database files",
    "Scan code for exploits",
    "Audit user access permissions",
    "Enforce least privilege access",
    "Inspect network packet headers",
    "Isolate compromised virtual hosts",
    "Hash passwords with salt",
    "Revoke compromised API keys",
    "Rotate cryptographic secret certs",
    "Zero trust architecture protects",
    "Deploy web application firewall",
    "Block distributed denial attacks",
    "encrypt the cryptographic firewall",
    "cryptographic firewall encrypt cyber defense",
    "firewall brings cryptographic cyber defense",
    "Always encrypt cryptographic firewall",
    "Every firewall can encrypt",
    "authenticate the resilient encryption",
    "resilient encryption authenticate network integrity",
    "encryption brings resilient network integrity",
    "Always authenticate resilient encryption",
    "Every encryption can authenticate",
    "defend the secure cipher",
    "secure cipher defend data privacy",
    "cipher brings secure data privacy",
    "Always defend secure cipher",
    "Every cipher can defend",
    "neutralize the anomalous token",
    "anomalous token neutralize threat hunting",
    "token brings anomalous threat hunting",
    "Always neutralize anomalous token",
    "Every token can neutralize",
    "inspect the malicious exploit",
    "malicious exploit inspect endpoint security",
    "exploit brings malicious endpoint security",
    "Always inspect malicious exploit",
    "Every exploit can inspect",
    "isolate the defensive sandbox",
    "defensive sandbox isolate cloud posture",
    "sandbox brings defensive cloud posture",
    "Always isolate defensive sandbox",
    "Every sandbox can isolate",
    "audit the proactive credential",
    "proactive credential audit cyber defense",
    "credential brings proactive cyber defense",
    "Always audit proactive credential",
    "Every credential can audit",
    "mitigate the hardened protocol",
    "hardened protocol mitigate network integrity",
    "protocol brings hardened network integrity",
    "Always mitigate hardened protocol",
    "Every protocol can mitigate",
    "decrypt the immutable payload",
    "immutable payload decrypt data privacy",
    "payload brings immutable data privacy",
    "Always decrypt immutable payload",
    "Every payload can decrypt",
    "sanitize the encrypted vulnerability",
    "encrypted vulnerability sanitize threat hunting",
    "vulnerability brings encrypted threat hunting",
    "Always sanitize encrypted vulnerability",
    "Every vulnerability can sanitize",
    "cryptographic firewall encrypt endpoint security",
    "firewall brings cryptographic endpoint security",
    "resilient encryption authenticate cloud posture",
    "encryption brings resilient cloud posture",
    "secure cipher defend cyber defense",
    "cipher brings secure cyber defense",
    "anomalous token neutralize network integrity",
    "token brings anomalous network integrity",
    "malicious exploit inspect data privacy",
    "exploit brings malicious data privacy",
    "defensive sandbox isolate threat hunting",
    "sandbox brings defensive threat hunting",
    "proactive credential audit endpoint security",
    "credential brings proactive endpoint security",
    "hardened protocol mitigate cloud posture",
    "protocol brings hardened cloud posture",
    "immutable payload decrypt cyber defense",
    "payload brings immutable cyber defense",
    "encrypted vulnerability sanitize network integrity",
    "vulnerability brings encrypted network integrity",
    "cryptographic firewall encrypt data privacy",
    "firewall brings cryptographic data privacy",
    "resilient encryption authenticate threat hunting",
    "encryption brings resilient threat hunting",
    "secure cipher defend endpoint security",
    "cipher brings secure endpoint security",
    "anomalous token neutralize cloud posture",
    "token brings anomalous cloud posture",
    "malicious exploit inspect cyber defense",
    "exploit brings malicious cyber defense"
  ],
  "normal": [
    "Two factor authentication dramatically reduces account takeover risks for employees",
    "Zero day exploits target vulnerabilities before developers create security patches",
    "Ransomware encrypts critical files until victims pay demanded extortion fees",
    "Public wireless networks require encrypted virtual private network connection tunnels",
    "Security is an ongoing continuous process not a finished product",
    "Buffer overflow vulnerabilities allow arbitrary malicious remote code execution exploits",
    "Social engineering attacks manipulate human trust rather than cracking software",
    "Security analysts monitor real time telemetry feeds for anomalous traffic",
    "Automated penetration testing identifies weaknesses before malicious black hat hackers",
    "Defense in depth combines physical network and application security layers",
    "The cryptographic firewall will greatly encrypt our cyber defense today",
    "Every cryptographic firewall must encrypt carefully across the entire cyber",
    "Learning how to encrypt cryptographic firewall inspires deep cyber defense",
    "Our dedicated team will encrypt the cryptographic firewall for cyber",
    "The resilient encryption will greatly authenticate our network integrity today",
    "Every resilient encryption must authenticate carefully across the entire network",
    "Learning how to authenticate resilient encryption inspires deep network integrity",
    "Our dedicated team will authenticate the resilient encryption for network",
    "The secure cipher will greatly defend our data privacy today",
    "Every secure cipher must defend carefully across the entire data",
    "Learning how to defend secure cipher inspires deep data privacy",
    "Our dedicated team will defend the secure cipher for data",
    "The anomalous token will greatly neutralize our threat hunting today",
    "Every anomalous token must neutralize carefully across the entire threat",
    "Learning how to neutralize anomalous token inspires deep threat hunting",
    "Our dedicated team will neutralize the anomalous token for threat",
    "The malicious exploit will greatly inspect our endpoint security today",
    "Every malicious exploit must inspect carefully across the entire endpoint",
    "Learning how to inspect malicious exploit inspires deep endpoint security",
    "Our dedicated team will inspect the malicious exploit for endpoint",
    "The defensive sandbox will greatly isolate our cloud posture today",
    "Every defensive sandbox must isolate carefully across the entire cloud",
    "Learning how to isolate defensive sandbox inspires deep cloud posture",
    "Our dedicated team will isolate the defensive sandbox for cloud",
    "The proactive credential will greatly audit our cyber defense today",
    "Every proactive credential must audit carefully across the entire cyber",
    "Learning how to audit proactive credential inspires deep cyber defense",
    "Our dedicated team will audit the proactive credential for cyber",
    "The hardened protocol will greatly mitigate our network integrity today",
    "Every hardened protocol must mitigate carefully across the entire network",
    "Learning how to mitigate hardened protocol inspires deep network integrity",
    "Our dedicated team will mitigate the hardened protocol for network",
    "The immutable payload will greatly decrypt our data privacy today",
    "Every immutable payload must decrypt carefully across the entire data",
    "Learning how to decrypt immutable payload inspires deep data privacy",
    "Our dedicated team will decrypt the immutable payload for data",
    "The encrypted vulnerability will greatly sanitize our threat hunting today",
    "Every encrypted vulnerability must sanitize carefully across the entire threat",
    "Learning how to sanitize encrypted vulnerability inspires deep threat hunting",
    "Our dedicated team will sanitize the encrypted vulnerability for threat",
    "The cryptographic firewall will greatly encrypt our endpoint security today",
    "Every cryptographic firewall must encrypt carefully across the entire endpoint",
    "Learning how to encrypt cryptographic firewall inspires deep endpoint security",
    "Our dedicated team will encrypt the cryptographic firewall for endpoint",
    "The resilient encryption will greatly authenticate our cloud posture today",
    "Every resilient encryption must authenticate carefully across the entire cloud",
    "Learning how to authenticate resilient encryption inspires deep cloud posture",
    "Our dedicated team will authenticate the resilient encryption for cloud",
    "The secure cipher will greatly defend our cyber defense today",
    "Every secure cipher must defend carefully across the entire cyber",
    "Learning how to defend secure cipher inspires deep cyber defense",
    "Our dedicated team will defend the secure cipher for cyber",
    "The anomalous token will greatly neutralize our network integrity today",
    "Every anomalous token must neutralize carefully across the entire network",
    "Learning how to neutralize anomalous token inspires deep network integrity",
    "Our dedicated team will neutralize the anomalous token for network",
    "The malicious exploit will greatly inspect our data privacy today",
    "Every malicious exploit must inspect carefully across the entire data",
    "Learning how to inspect malicious exploit inspires deep data privacy",
    "Our dedicated team will inspect the malicious exploit for data"
  ],
  "hard": [
    "Defense in depth combines multiple defensive layers so single point failures do not compromise critical enterprise infrastructure",
    "End to end encryption ensures that only communicating users can read exchanged private messages across untrusted public networks",
    "Social engineering attacks exploit human psychology rather than software vulnerabilities to breach sophisticated corporate security defenses",
    "Penetration testers simulate adversary techniques to discover critical vulnerabilities before malicious foreign threat actors exploit them in wild",
    "Hardware security keys provide phishing resistant multi factor authentication for high value administrative credentials across enterprise cloud environments",
    "When confronting complex challenges in cyber defense one must encrypt every cryptographic firewall with rigorous discipline and patient determination",
    "The integration of cryptographic firewall within modern cyber defense enables practitioners to encrypt critical milestones without sacrificing enduring quality",
    "Throughout the evolution of cyber defense master practitioners learned to encrypt the most intricate cryptographic firewall through persistent dedicated effort",
    "Developing comprehensive understanding of cyber defense demands that professionals encrypt each cryptographic firewall with profound analytical rigor and integrity",
    "When confronting complex challenges in network integrity one must authenticate every resilient encryption with rigorous discipline and patient determination",
    "The integration of resilient encryption within modern network integrity enables practitioners to authenticate critical milestones without sacrificing enduring quality",
    "Throughout the evolution of network integrity master practitioners learned to authenticate the most intricate resilient encryption through persistent dedicated effort",
    "Developing comprehensive understanding of network integrity demands that professionals authenticate each resilient encryption with profound analytical rigor and integrity",
    "When confronting complex challenges in data privacy one must defend every secure cipher with rigorous discipline and patient determination",
    "The integration of secure cipher within modern data privacy enables practitioners to defend critical milestones without sacrificing enduring quality",
    "Throughout the evolution of data privacy master practitioners learned to defend the most intricate secure cipher through persistent dedicated effort",
    "Developing comprehensive understanding of data privacy demands that professionals defend each secure cipher with profound analytical rigor and integrity",
    "When confronting complex challenges in threat hunting one must neutralize every anomalous token with rigorous discipline and patient determination",
    "The integration of anomalous token within modern threat hunting enables practitioners to neutralize critical milestones without sacrificing enduring quality",
    "Throughout the evolution of threat hunting master practitioners learned to neutralize the most intricate anomalous token through persistent dedicated effort",
    "Developing comprehensive understanding of threat hunting demands that professionals neutralize each anomalous token with profound analytical rigor and integrity",
    "When confronting complex challenges in endpoint security one must inspect every malicious exploit with rigorous discipline and patient determination",
    "The integration of malicious exploit within modern endpoint security enables practitioners to inspect critical milestones without sacrificing enduring quality",
    "Throughout the evolution of endpoint security master practitioners learned to inspect the most intricate malicious exploit through persistent dedicated effort",
    "Developing comprehensive understanding of endpoint security demands that professionals inspect each malicious exploit with profound analytical rigor and integrity",
    "When confronting complex challenges in cloud posture one must isolate every defensive sandbox with rigorous discipline and patient determination",
    "The integration of defensive sandbox within modern cloud posture enables practitioners to isolate critical milestones without sacrificing enduring quality",
    "Throughout the evolution of cloud posture master practitioners learned to isolate the most intricate defensive sandbox through persistent dedicated effort",
    "Developing comprehensive understanding of cloud posture demands that professionals isolate each defensive sandbox with profound analytical rigor and integrity",
    "When confronting complex challenges in cyber defense one must audit every proactive credential with rigorous discipline and patient determination"
  ]
};

export async function seed() {
  return await upsertCategoryAndSentences(category, sentences);
}

if (process.argv[1]?.endsWith('cybersecurity.mjs')) {
  seed().catch(console.error);
}
