import { upsertCategoryAndSentences } from './seed-helper.mjs';

export const category = {
  "slug": "finance",
  "label": "Finance & Economics",
  "icon": "📈",
  "description": "Capital markets, compound interest, assets, and wealth",
  "display_order": 24
};

export const sentences = {
  "easy": [
    "Compound interest builds wealth",
    "Diversify your investment portfolio",
    "Save before you spend",
    "Inflation erodes purchasing power",
    "Assets generate passive income",
    "Budget every single dollar",
    "Stocks represent business ownership",
    "Bonds yield steady interest",
    "Reinvest dividend cash payments",
    "Dollar cost average monthly",
    "Emergency fund brings security",
    "Live below your means",
    "Pay down high debt",
    "Track net worth growth",
    "Automate monthly retirement savings",
    "Index funds beat stockpicking",
    "Bull markets climb walls",
    "Bear markets test conviction",
    "Compound interest eighth wonder",
    "Patience pays massive dividends",
    "compound the fiduciary dividend",
    "fiduciary dividend compound capital markets",
    "dividend brings fiduciary capital markets",
    "Always compound fiduciary dividend",
    "Every dividend can compound",
    "diversify the liquid portfolio",
    "liquid portfolio diversify asset allocation",
    "portfolio brings liquid asset allocation",
    "Always diversify liquid portfolio",
    "Every portfolio can diversify",
    "invest the fiscal asset",
    "fiscal asset invest wealth generation",
    "asset brings fiscal wealth generation",
    "Always invest fiscal asset",
    "Every asset can invest",
    "rebalance the compound equity",
    "compound equity rebalance economic policy",
    "equity brings compound economic policy",
    "Always rebalance compound equity",
    "Every equity can rebalance",
    "allocate the equitable yield",
    "equitable yield allocate portfolio yield",
    "yield brings equitable portfolio yield",
    "Always allocate equitable yield",
    "Every yield can allocate",
    "accrue the lucrative capital",
    "lucrative capital accrue fiscal discipline",
    "capital brings lucrative fiscal discipline",
    "Always accrue lucrative capital",
    "Every capital can accrue",
    "hedge the diversified index",
    "diversified index hedge capital markets",
    "index brings diversified capital markets",
    "Always hedge diversified index",
    "Every index can hedge",
    "audit the solvent valuation",
    "solvent valuation audit asset allocation",
    "valuation brings solvent asset allocation",
    "Always audit solvent valuation",
    "Every valuation can audit",
    "appreciate the monetary ledger",
    "monetary ledger appreciate wealth generation",
    "ledger brings monetary wealth generation",
    "Always appreciate monetary ledger",
    "Every ledger can appreciate",
    "amortize the prudent balance",
    "prudent balance amortize economic policy",
    "balance brings prudent economic policy",
    "Always amortize prudent balance",
    "Every balance can amortize",
    "fiduciary dividend compound portfolio yield",
    "dividend brings fiduciary portfolio yield",
    "liquid portfolio diversify fiscal discipline",
    "portfolio brings liquid fiscal discipline",
    "fiscal asset invest capital markets",
    "asset brings fiscal capital markets",
    "compound equity rebalance asset allocation",
    "equity brings compound asset allocation",
    "equitable yield allocate wealth generation",
    "yield brings equitable wealth generation",
    "lucrative capital accrue economic policy",
    "capital brings lucrative economic policy",
    "diversified index hedge portfolio yield",
    "index brings diversified portfolio yield",
    "solvent valuation audit fiscal discipline",
    "valuation brings solvent fiscal discipline",
    "monetary ledger appreciate capital markets",
    "ledger brings monetary capital markets",
    "prudent balance amortize asset allocation",
    "balance brings prudent asset allocation",
    "fiduciary dividend compound wealth generation",
    "dividend brings fiduciary wealth generation",
    "liquid portfolio diversify economic policy",
    "portfolio brings liquid economic policy",
    "fiscal asset invest portfolio yield",
    "asset brings fiscal portfolio yield",
    "compound equity rebalance fiscal discipline",
    "equity brings compound fiscal discipline",
    "equitable yield allocate capital markets",
    "yield brings equitable capital markets"
  ],
  "normal": [
    "Do not put all your financial eggs in one basket",
    "Index funds provide low cost broad market diversification for investors",
    "Supply and demand dictate market equilibrium pricing levels across industries",
    "Liquidity allows prudent investors to convert assets to cash quickly",
    "Time in the market beats timing the volatile stock market",
    "Central banks raise interest rates to cool overheating economic inflation",
    "A disciplined budget provides freedom and eliminates lingering financial anxiety",
    "Compound interest accelerates asset growth dramatically over long multi decades",
    "Real estate investment provides tangible collateral and recurring rental yields",
    "Diversification mitigates idiosyncratic portfolio risk without sacrificing long term returns",
    "The fiduciary dividend will greatly compound our capital markets today",
    "Every fiduciary dividend must compound carefully across the entire capital",
    "Learning how to compound fiduciary dividend inspires deep capital markets",
    "Our dedicated team will compound the fiduciary dividend for capital",
    "The liquid portfolio will greatly diversify our asset allocation today",
    "Every liquid portfolio must diversify carefully across the entire asset",
    "Learning how to diversify liquid portfolio inspires deep asset allocation",
    "Our dedicated team will diversify the liquid portfolio for asset",
    "The fiscal asset will greatly invest our wealth generation today",
    "Every fiscal asset must invest carefully across the entire wealth",
    "Learning how to invest fiscal asset inspires deep wealth generation",
    "Our dedicated team will invest the fiscal asset for wealth",
    "The compound equity will greatly rebalance our economic policy today",
    "Every compound equity must rebalance carefully across the entire economic",
    "Learning how to rebalance compound equity inspires deep economic policy",
    "Our dedicated team will rebalance the compound equity for economic",
    "The equitable yield will greatly allocate our portfolio yield today",
    "Every equitable yield must allocate carefully across the entire portfolio",
    "Learning how to allocate equitable yield inspires deep portfolio yield",
    "Our dedicated team will allocate the equitable yield for portfolio",
    "The lucrative capital will greatly accrue our fiscal discipline today",
    "Every lucrative capital must accrue carefully across the entire fiscal",
    "Learning how to accrue lucrative capital inspires deep fiscal discipline",
    "Our dedicated team will accrue the lucrative capital for fiscal",
    "The diversified index will greatly hedge our capital markets today",
    "Every diversified index must hedge carefully across the entire capital",
    "Learning how to hedge diversified index inspires deep capital markets",
    "Our dedicated team will hedge the diversified index for capital",
    "The solvent valuation will greatly audit our asset allocation today",
    "Every solvent valuation must audit carefully across the entire asset",
    "Learning how to audit solvent valuation inspires deep asset allocation",
    "Our dedicated team will audit the solvent valuation for asset",
    "The monetary ledger will greatly appreciate our wealth generation today",
    "Every monetary ledger must appreciate carefully across the entire wealth",
    "Learning how to appreciate monetary ledger inspires deep wealth generation",
    "Our dedicated team will appreciate the monetary ledger for wealth",
    "The prudent balance will greatly amortize our economic policy today",
    "Every prudent balance must amortize carefully across the entire economic",
    "Learning how to amortize prudent balance inspires deep economic policy",
    "Our dedicated team will amortize the prudent balance for economic",
    "The fiduciary dividend will greatly compound our portfolio yield today",
    "Every fiduciary dividend must compound carefully across the entire portfolio",
    "Learning how to compound fiduciary dividend inspires deep portfolio yield",
    "Our dedicated team will compound the fiduciary dividend for portfolio",
    "The liquid portfolio will greatly diversify our fiscal discipline today",
    "Every liquid portfolio must diversify carefully across the entire fiscal",
    "Learning how to diversify liquid portfolio inspires deep fiscal discipline",
    "Our dedicated team will diversify the liquid portfolio for fiscal",
    "The fiscal asset will greatly invest our capital markets today",
    "Every fiscal asset must invest carefully across the entire capital",
    "Learning how to invest fiscal asset inspires deep capital markets",
    "Our dedicated team will invest the fiscal asset for capital",
    "The compound equity will greatly rebalance our asset allocation today",
    "Every compound equity must rebalance carefully across the entire asset",
    "Learning how to rebalance compound equity inspires deep asset allocation",
    "Our dedicated team will rebalance the compound equity for asset",
    "The equitable yield will greatly allocate our wealth generation today",
    "Every equitable yield must allocate carefully across the entire wealth",
    "Learning how to allocate equitable yield inspires deep wealth generation",
    "Our dedicated team will allocate the equitable yield for wealth"
  ],
  "hard": [
    "Compound interest is the eighth wonder of the world he who understands it earns it pays it",
    "Dollar cost averaging reduces the psychological stress of investing by purchasing shares at regular disciplined intervals regardless of volatility",
    "A bull market climbs a wall of worry while bear markets test the emotional conviction and discipline of prudent investors",
    "Emergency funds covering six months of essential living expenses protect households from sudden unexpected economic shocks or employment disruptions",
    "Understanding balance sheets cash flow statements and income reports is fundamental to analyzing the intrinsic long term health of businesses",
    "When confronting complex challenges in capital markets one must compound every fiduciary dividend with rigorous discipline and patient determination",
    "The integration of fiduciary dividend within modern capital markets enables practitioners to compound critical milestones without sacrificing enduring quality",
    "Throughout the evolution of capital markets master practitioners learned to compound the most intricate fiduciary dividend through persistent dedicated effort",
    "Developing comprehensive understanding of capital markets demands that professionals compound each fiduciary dividend with profound analytical rigor and integrity",
    "When confronting complex challenges in asset allocation one must diversify every liquid portfolio with rigorous discipline and patient determination",
    "The integration of liquid portfolio within modern asset allocation enables practitioners to diversify critical milestones without sacrificing enduring quality",
    "Throughout the evolution of asset allocation master practitioners learned to diversify the most intricate liquid portfolio through persistent dedicated effort",
    "Developing comprehensive understanding of asset allocation demands that professionals diversify each liquid portfolio with profound analytical rigor and integrity",
    "When confronting complex challenges in wealth generation one must invest every fiscal asset with rigorous discipline and patient determination",
    "The integration of fiscal asset within modern wealth generation enables practitioners to invest critical milestones without sacrificing enduring quality",
    "Throughout the evolution of wealth generation master practitioners learned to invest the most intricate fiscal asset through persistent dedicated effort",
    "Developing comprehensive understanding of wealth generation demands that professionals invest each fiscal asset with profound analytical rigor and integrity",
    "When confronting complex challenges in economic policy one must rebalance every compound equity with rigorous discipline and patient determination",
    "The integration of compound equity within modern economic policy enables practitioners to rebalance critical milestones without sacrificing enduring quality",
    "Throughout the evolution of economic policy master practitioners learned to rebalance the most intricate compound equity through persistent dedicated effort",
    "Developing comprehensive understanding of economic policy demands that professionals rebalance each compound equity with profound analytical rigor and integrity",
    "When confronting complex challenges in portfolio yield one must allocate every equitable yield with rigorous discipline and patient determination",
    "The integration of equitable yield within modern portfolio yield enables practitioners to allocate critical milestones without sacrificing enduring quality",
    "Throughout the evolution of portfolio yield master practitioners learned to allocate the most intricate equitable yield through persistent dedicated effort",
    "Developing comprehensive understanding of portfolio yield demands that professionals allocate each equitable yield with profound analytical rigor and integrity",
    "When confronting complex challenges in fiscal discipline one must accrue every lucrative capital with rigorous discipline and patient determination",
    "The integration of lucrative capital within modern fiscal discipline enables practitioners to accrue critical milestones without sacrificing enduring quality",
    "Throughout the evolution of fiscal discipline master practitioners learned to accrue the most intricate lucrative capital through persistent dedicated effort",
    "Developing comprehensive understanding of fiscal discipline demands that professionals accrue each lucrative capital with profound analytical rigor and integrity",
    "When confronting complex challenges in capital markets one must hedge every diversified index with rigorous discipline and patient determination"
  ]
};

export async function seed() {
  return await upsertCategoryAndSentences(category, sentences);
}

if (process.argv[1]?.endsWith('finance.mjs')) {
  seed().catch(console.error);
}
