import { upsertCategoryAndSentences } from './seed-helper.mjs';

export const category = {
  "slug": "gaming",
  "label": "Video Games",
  "icon": "🎮",
  "description": "Legendary gaming lore, arcade culture, and gamer vernacular",
  "display_order": 12
};

export const sentences = {
  "easy": [
    "Press start to play",
    "The cake is lie",
    "Stay awhile and listen",
    "Victory royale secured today",
    "Insert coin to continue",
    "Save points prevent loss",
    "Level up your hero",
    "Defeat the final boss",
    "Collect all gold coins",
    "Unlock the secret door",
    "Equip legendary glowing sword",
    "Check your inventory slots",
    "Heal with health potion",
    "Mana restores magical spells",
    "Dodge incoming boss attacks",
    "Roll away from danger",
    "Combo multiplier reached maximum",
    "Speedrun set world record",
    "Respawn at nearest checkpoint",
    "Explore the ancient dungeon",
    "Loot the treasure chest",
    "Craft powerful new armor",
    "Enchant your wooden bow",
    "Upgrade weapon damage stats",
    "Defend the home base",
    "Capture the enemy flag",
    "Guild raids start tonight",
    "Voice chat with squad",
    "conquer the legendary controller",
    "legendary controller conquer gaming lore",
    "controller brings legendary gaming lore",
    "Always conquer legendary controller",
    "Every controller can conquer",
    "navigate the retro joystick",
    "retro joystick navigate arcade glory",
    "joystick brings retro arcade glory",
    "Always navigate retro joystick",
    "Every joystick can navigate",
    "defeat the mythic pixel",
    "mythic pixel defeat speedrun route",
    "pixel brings mythic speedrun route",
    "Always defeat mythic pixel",
    "Every pixel can defeat",
    "unlock the stealthy avatar",
    "stealthy avatar unlock boss encounter",
    "avatar brings stealthy boss encounter",
    "Always unlock stealthy avatar",
    "Every avatar can unlock",
    "master the epic dungeon",
    "epic dungeon master multiplayer lobby",
    "dungeon brings epic multiplayer lobby",
    "Always master epic dungeon",
    "Every dungeon can master",
    "explore the pixelated quest",
    "pixelated quest explore fantasy realm",
    "quest brings pixelated fantasy realm",
    "Always explore pixelated quest",
    "Every quest can explore",
    "upgrade the challenging checkpoint",
    "challenging checkpoint upgrade gaming lore",
    "checkpoint brings challenging gaming lore",
    "Always upgrade challenging checkpoint",
    "Every checkpoint can upgrade",
    "dodge the dynamic boss",
    "dynamic boss dodge arcade glory",
    "boss brings dynamic arcade glory",
    "Always dodge dynamic boss",
    "Every boss can dodge",
    "execute the tactical powerup",
    "tactical powerup execute speedrun route",
    "powerup brings tactical speedrun route",
    "Always execute tactical powerup",
    "Every powerup can execute",
    "achieve the heroic glitch",
    "heroic glitch achieve boss encounter",
    "glitch brings heroic boss encounter",
    "Always achieve heroic glitch",
    "Every glitch can achieve",
    "legendary controller conquer multiplayer lobby",
    "controller brings legendary multiplayer lobby",
    "retro joystick navigate fantasy realm",
    "joystick brings retro fantasy realm",
    "mythic pixel defeat gaming lore",
    "pixel brings mythic gaming lore",
    "stealthy avatar unlock arcade glory",
    "avatar brings stealthy arcade glory",
    "epic dungeon master speedrun route",
    "dungeon brings epic speedrun route",
    "pixelated quest explore boss encounter",
    "quest brings pixelated boss encounter",
    "challenging checkpoint upgrade multiplayer lobby",
    "checkpoint brings challenging multiplayer lobby",
    "dynamic boss dodge fantasy realm",
    "boss brings dynamic fantasy realm",
    "tactical powerup execute gaming lore",
    "powerup brings tactical gaming lore",
    "heroic glitch achieve arcade glory",
    "glitch brings heroic arcade glory",
    "legendary controller conquer speedrun route",
    "controller brings legendary speedrun route"
  ],
  "normal": [
    "It is dangerous to go alone take this sword with",
    "War never changes across ruined post apocalyptic desert wastelands",
    "Praise the radiant sun during dark and punishing boss battles",
    "A true hero need not speak when deeds shake the",
    "Your beloved princess is unfortunately in another distant stone castle",
    "Stealth gameplay rewards patient scouts and quiet careful shadows",
    "Protocol three protect the pilot became an unforgettable mech line",
    "Speedrunners dissect game physics down to individual frames for records",
    "Exploring sprawling fantasy maps with trusted friends creates lasting memories",
    "Classic arcade cabinets required quick reflexes and pocketfuls of quarters",
    "The legendary controller will greatly conquer our gaming lore today",
    "Every legendary controller must conquer carefully across the entire gaming",
    "Learning how to conquer legendary controller inspires deep gaming lore",
    "Our dedicated team will conquer the legendary controller for gaming",
    "The retro joystick will greatly navigate our arcade glory today",
    "Every retro joystick must navigate carefully across the entire arcade",
    "Learning how to navigate retro joystick inspires deep arcade glory",
    "Our dedicated team will navigate the retro joystick for arcade",
    "The mythic pixel will greatly defeat our speedrun route today",
    "Every mythic pixel must defeat carefully across the entire speedrun",
    "Learning how to defeat mythic pixel inspires deep speedrun route",
    "Our dedicated team will defeat the mythic pixel for speedrun",
    "The stealthy avatar will greatly unlock our boss encounter today",
    "Every stealthy avatar must unlock carefully across the entire boss",
    "Learning how to unlock stealthy avatar inspires deep boss encounter",
    "Our dedicated team will unlock the stealthy avatar for boss",
    "The epic dungeon will greatly master our multiplayer lobby today",
    "Every epic dungeon must master carefully across the entire multiplayer",
    "Learning how to master epic dungeon inspires deep multiplayer lobby",
    "Our dedicated team will master the epic dungeon for multiplayer",
    "The pixelated quest will greatly explore our fantasy realm today",
    "Every pixelated quest must explore carefully across the entire fantasy",
    "Learning how to explore pixelated quest inspires deep fantasy realm",
    "Our dedicated team will explore the pixelated quest for fantasy",
    "The challenging checkpoint will greatly upgrade our gaming lore today",
    "Every challenging checkpoint must upgrade carefully across the entire gaming",
    "Learning how to upgrade challenging checkpoint inspires deep gaming lore",
    "Our dedicated team will upgrade the challenging checkpoint for gaming",
    "The dynamic boss will greatly dodge our arcade glory today",
    "Every dynamic boss must dodge carefully across the entire arcade",
    "Learning how to dodge dynamic boss inspires deep arcade glory",
    "Our dedicated team will dodge the dynamic boss for arcade",
    "The tactical powerup will greatly execute our speedrun route today",
    "Every tactical powerup must execute carefully across the entire speedrun",
    "Learning how to execute tactical powerup inspires deep speedrun route",
    "Our dedicated team will execute the tactical powerup for speedrun",
    "The heroic glitch will greatly achieve our boss encounter today",
    "Every heroic glitch must achieve carefully across the entire boss",
    "Learning how to achieve heroic glitch inspires deep boss encounter",
    "Our dedicated team will achieve the heroic glitch for boss",
    "The legendary controller will greatly conquer our multiplayer lobby today",
    "Every legendary controller must conquer carefully across the entire multiplayer",
    "Learning how to conquer legendary controller inspires deep multiplayer lobby",
    "Our dedicated team will conquer the legendary controller for multiplayer",
    "The retro joystick will greatly navigate our fantasy realm today",
    "Every retro joystick must navigate carefully across the entire fantasy",
    "Learning how to navigate retro joystick inspires deep fantasy realm",
    "Our dedicated team will navigate the retro joystick for fantasy",
    "The mythic pixel will greatly defeat our gaming lore today",
    "Every mythic pixel must defeat carefully across the entire gaming",
    "Learning how to defeat mythic pixel inspires deep gaming lore",
    "Our dedicated team will defeat the mythic pixel for gaming",
    "The stealthy avatar will greatly unlock our arcade glory today",
    "Every stealthy avatar must unlock carefully across the entire arcade",
    "Learning how to unlock stealthy avatar inspires deep arcade glory",
    "Our dedicated team will unlock the stealthy avatar for arcade",
    "The epic dungeon will greatly master our speedrun route today",
    "Every epic dungeon must master carefully across the entire speedrun",
    "Learning how to master epic dungeon inspires deep speedrun route",
    "Our dedicated team will master the epic dungeon for speedrun"
  ],
  "hard": [
    "Did I ever tell you what the definition of insanity is in modern high stakes video games",
    "Stand in the ashes of a trillion dead souls and ask the ghosts if honor still matters today",
    "Speedrunners dissect game physics down to individual frames to achieve unbelievable world record times across competitive communities",
    "Exploring sprawling open world fantasy maps with friends creates unforgettable memories that outlast any single multiplayer campaign",
    "A masterpiece video game seamlessly marries intuitive tactile controller mechanics with gripping narrative storytelling and emotive musical composition",
    "When confronting complex challenges in gaming lore one must conquer every legendary controller with rigorous discipline and patient determination",
    "The integration of legendary controller within modern gaming lore enables practitioners to conquer critical milestones without sacrificing enduring quality",
    "Throughout the evolution of gaming lore master practitioners learned to conquer the most intricate legendary controller through persistent dedicated effort",
    "Developing comprehensive understanding of gaming lore demands that professionals conquer each legendary controller with profound analytical rigor and integrity",
    "When confronting complex challenges in arcade glory one must navigate every retro joystick with rigorous discipline and patient determination",
    "The integration of retro joystick within modern arcade glory enables practitioners to navigate critical milestones without sacrificing enduring quality",
    "Throughout the evolution of arcade glory master practitioners learned to navigate the most intricate retro joystick through persistent dedicated effort",
    "Developing comprehensive understanding of arcade glory demands that professionals navigate each retro joystick with profound analytical rigor and integrity",
    "When confronting complex challenges in speedrun route one must defeat every mythic pixel with rigorous discipline and patient determination",
    "The integration of mythic pixel within modern speedrun route enables practitioners to defeat critical milestones without sacrificing enduring quality",
    "Throughout the evolution of speedrun route master practitioners learned to defeat the most intricate mythic pixel through persistent dedicated effort",
    "Developing comprehensive understanding of speedrun route demands that professionals defeat each mythic pixel with profound analytical rigor and integrity",
    "When confronting complex challenges in boss encounter one must unlock every stealthy avatar with rigorous discipline and patient determination",
    "The integration of stealthy avatar within modern boss encounter enables practitioners to unlock critical milestones without sacrificing enduring quality",
    "Throughout the evolution of boss encounter master practitioners learned to unlock the most intricate stealthy avatar through persistent dedicated effort",
    "Developing comprehensive understanding of boss encounter demands that professionals unlock each stealthy avatar with profound analytical rigor and integrity",
    "When confronting complex challenges in multiplayer lobby one must master every epic dungeon with rigorous discipline and patient determination",
    "The integration of epic dungeon within modern multiplayer lobby enables practitioners to master critical milestones without sacrificing enduring quality",
    "Throughout the evolution of multiplayer lobby master practitioners learned to master the most intricate epic dungeon through persistent dedicated effort",
    "Developing comprehensive understanding of multiplayer lobby demands that professionals master each epic dungeon with profound analytical rigor and integrity",
    "When confronting complex challenges in fantasy realm one must explore every pixelated quest with rigorous discipline and patient determination",
    "The integration of pixelated quest within modern fantasy realm enables practitioners to explore critical milestones without sacrificing enduring quality",
    "Throughout the evolution of fantasy realm master practitioners learned to explore the most intricate pixelated quest through persistent dedicated effort",
    "Developing comprehensive understanding of fantasy realm demands that professionals explore each pixelated quest with profound analytical rigor and integrity",
    "When confronting complex challenges in gaming lore one must upgrade every challenging checkpoint with rigorous discipline and patient determination"
  ]
};

export async function seed() {
  return await upsertCategoryAndSentences(category, sentences);
}

if (process.argv[1]?.endsWith('gaming.mjs')) {
  seed().catch(console.error);
}
