import { writeCategorySeedFile } from './builder.mjs';

// ══════════════════════════════════════════════════════════════
// 7. PHILOSOPHY & WISDOM (philosophy)
// ══════════════════════════════════════════════════════════════
const philosophy = {
  cat: {
    slug: 'philosophy',
    label: 'Philosophy & Wisdom',
    icon: '🏛️',
    description: 'Stoicism, existentialism, ethics, and timeless meditations',
    display_order: 8,
  },
  data: {
    easy: [
      'I think therefore exist', 'Know yourself deeply first', 'Virtue is its reward', 'Time heals all wounds',
      'Silence is often golden', 'Seek wisdom not riches', 'Patience yields true peace', 'Question all your beliefs',
      'Reason guides moral action', 'Truth requires honest courage', 'Life is constant change', 'Accept what comes naturally',
      'Desire causes human suffering', 'Freedom requires personal discipline', 'Death gives life meaning', 'Character shapes personal destiny',
      'Moderation is golden mean', 'Live in this moment', 'Peace begins with understanding', 'Justice protects the vulnerable',
      'Courage conquers hidden fear', 'Wisdom outlasts all gold', 'Mind creates own reality', 'Forgiveness heals bitter hearts',
      'Nature teaches simple humility', 'Kindness requires quiet strength', 'Honor your daily word', 'Curiosity leads to insight',
      'Doubt precedes true understanding', 'Solitude brings profound clarity', 'Embrace your mortal limits', 'Cherish the passing seasons',
      'Listen before you judge', 'Act without selfish expectation', 'Self control is power', 'Be content with simplicity',
      'Observe without hasty judgment', 'Choose compassion over anger', 'Gratitude transforms ordinary days', 'Harmony resides within peace',
      'Virtuous deeds outlive empires', 'Seek knowledge with humility', 'Accept your honest fate', 'Live with calm purpose',
      'Speak only truthful words', 'Master your inner impulses', 'Every dawn brings renewal', 'Kindness is highest wisdom',
      'Reflection reveals inner truth', 'Balance leads to serenity', 'Walk the righteous path', 'Let go of attachments',
      'Simplicity fosters deep joy', 'Conquer yourself each day', 'Quiet minds see clearly', 'Honor the common good',
      'Patience overcomes heavy burdens', 'Inner virtue cannot perish', 'Respect every living creature', 'Truth stands on itself',
      'Stand firm in virtue', 'Embrace the stoic mindset', 'Guard your mental fortress', 'Cultivate an honest spirit',
      'Time flows like water', 'Wisdom guides moral choice', 'Dwell in peaceful thoughts', 'Judge actions not words',
      'Control your own reactions', 'Happiness is internal state', 'Accept inevitable life changes', 'Live according to nature',
      'Seek virtue above wealth', 'Practice daily self examination', 'Fear nothing except dishonor', 'Strength lies in composure',
      'Be grateful for breath', 'Wisdom is eternal light', 'Tolerate other human faults', 'Hold fast to truth',
      'Choose duty over desire', 'Calm waves mirror sky', 'Quiet heart hears wisdom', 'Refrain from idle gossip',
      'Every hardship teaches lessons', 'Kindness softens stubborn minds', 'Endure with noble patience', 'Treat all with dignity',
      'True wealth is contentment', 'Live simply speak kindly', 'Self mastery brings victory', 'Focus on present duty',
      'Embrace the unfolding universe', 'Light shines in darkness', 'Act with good conscience', 'Peace is highest virtue',
      'Seek harmony in all', 'Wisdom guides righteous feet', 'Purity of intent matters', 'Endure and renounce attachments',
    ],
    normal: [
      'We suffer more often in imagination than in reality',
      'The unexamined life is truly not worth living for humans',
      'Waste no more time arguing what a good person should be',
      'Happiness depends entirely upon the quality of your inner thoughts',
      'You have power over your mind not outside worldly events',
      'He who has a why to live can bear almost any how',
      'Man is condemned to be free because he is fully responsible',
      'The only true wisdom is in knowing you know almost nothing',
      'When you arise think what a precious privilege it is to live',
      'Do not explain your philosophy rather embody its core virtues daily',
      'He who overcomes his desires is braver than him who conquers',
      'It is not death a man should fear but never beginning to live',
      'Very little is needed to make a happy peaceful life',
      'If it is not right do not do it immediately',
      'Dwell on the beauty of life watch the stars and run',
      'The soul becomes dyed with the color of its frequent thoughts',
      'No man is free who is not master of himself completely',
      'First say to yourself what you would be and then act',
      'Wealth consists not in having great possessions but having few wants',
      'Freedom is the only worthy goal in human earthly existence',
      'He who laughs at himself never runs out of things to laugh',
      'To be evenminded is the greatest virtue and wisdom in life',
      'Character is both a long standing habit and a destiny',
      'There is nothing permanent in this world except constant ongoing change',
      'The key is to keep company only with people who uplift',
      'Be kind for everyone you meet is fighting a harder battle',
      'To live is the rarest thing in the entire world today',
      'Better a little which is well done than a great deal imperfectly',
      'He who is not contented with what he has would not be',
      'The greatest remedy for anger is delay and careful thoughtful reflection',
      'A man who suffers before it is necessary suffers more than necessary',
      'True happiness is to enjoy the present without anxious dependence on future',
      'Difficulty shows what men truly are beneath the polished surface',
      'Know how to listen and you will profit even from those who speak',
      'It is a rough road that leads to the heights of greatness',
      'Silence is a lesson learned through life many painful trials',
      'He who fears death will never do anything worthy of a man',
      'To conquer oneself is a greater task than conquering others in battle',
      'Do not spoil what you have by desiring what you have not',
      'The more you know the more you realize you know nothing at all',
      'Live your life as an exclamation rather than an ongoing explanation',
      'The art of living is more like wrestling than dancing in rhythm',
      'Things do not touch the soul for they are external and motionless',
      'If someone is able to show me that what I think is wrong',
      'Receive wealth or prosperity without arrogance and be ready to let it go',
      'How much trouble he avoids who does not look to see what',
      'Never let the future disturb you you will meet it with the same',
      'Look within within is the fountain of good and it will ever bubble',
      'The best revenge is to be unlike him who performed the injury',
      'Loss is nothing else but change and change is Nature delight',
      'Each day provides its own gifts if we choose to notice them',
      'Patience is the companion of wisdom throughout all human history',
      'Associate with people who are likely to improve you as a person',
      'Virtue is sufficient of itself for human happiness and peace of mind',
      'No evil can happen to a good man either in life or',
      'The mind that is anxious about future events is miserable beforehand',
      'It is quality rather than quantity that matters in human achievements',
      'He who wishes to be obeyed must know how to command himself',
      'Wisdom ceases to be wisdom when it becomes too proud to weep',
      'The greatest obstacle to living is expectancy which hangs upon tomorrow',
      'Every night before going to sleep ask yourself what virtue have I improved',
      'Do every act of your life as though it were the very last',
      'A ship should not ride on a single anchor nor life on single',
      'Nothing can harm you except what makes you a worse moral person',
      'Practice what you preach before attempting to teach it to other people',
      'Serenity comes when you trade expectations for deep and heartfelt gratitude',
      'A disciplined mind brings happiness while an undisciplined mind produces suffering',
      'Treat people as if they were what they ought to be in life',
      'The unexamined thought is often the root of all unnecessary human sorrow',
      'Live in harmony with the cosmos and you will never lack contentment',
    ],
    hard: [
      'Man is condemned to be free because once thrown into the world he is responsible for everything he does',
      'The only true wisdom is in knowing you know absolutely nothing about the boundless and mysterious cosmos around us',
      'When you arise in the morning think of what a precious privilege it is to breathe think and love',
      'Do not explain your philosophy rather embody its core virtues in your daily actions and interactions with all people',
      'He who overcomes his desires is braver than him who conquers his formidable enemies for hardest victory is over self',
      'You have power over your mind not outside events realize this and you will find immense and enduring inner strength',
      'It is not that we have a short time to live but that we waste a great deal of it needlessly',
      'If anyone can refute me show me I am making a mistake or looking at things from wrong perspective I will gladly change',
      'The happiness of your life depends upon the quality of your thoughts therefore guard accordingly and take care of your mind',
      'Waste no more time arguing about what a good man should be simply go forth and be one in daily practice',
      'He who fears death will never do anything worthy of a man who is truly alive and pursuing noble ideals',
      'Never esteem anything as of advantage to you that will make you break your word or lose your self respect',
      'Dwell on the beauty of life watch the twinkling stars and see yourself running alongside them in cosmic harmony',
      'The mind that is free from turbulent passions is a citadel for man has no fortress more secure to shelter within',
      'Choose rather to be strong of soul than strong of body for inner resilience outlasts any physical worldly power',
      'We are more often frightened than hurt and we suffer more from our anxious imaginations than from reality itself',
      'Everything we hear is an opinion not a fact and everything we see is a perspective not the absolute truth',
      'Accept the things to which fate binds you and love the people with whom fate brings you together with heart',
      'To live a good life we have the potential for it if we can learn to be indifferent to what makes difference',
      'Begin each morning by telling yourself today I shall meet with the meddling ungrateful arrogant dishonest and envious people',
      'Do not act as if you were going to live ten thousand years death hangs over you while you live be good',
      'Whatever anyone does or says I must be emerald and keep my color declared the emperor regarding personal integrity',
      'Look back over the past with its changing empires that rose and fell and you can foresee the future also clearly',
      'It is not the man who has too little but the man who craves more that is truly poor and impoverished',
      'How ridiculous and strange to be surprised at anything which happens in life since nature governs all things with necessity',
      'If you are distressed by anything external the pain is not due to thing itself but to your own estimate of it',
      'A man cannot lose either the past or the future for what a man cannot have how can anyone take away',
      'External things are not the problem it is your assessment of them which you can erase this very moment with clarity',
      'The soul becomes dyed with the color of its thoughts so bathe it frequently in courageous generous and benevolent reflections',
      'Life is neither good nor evil in itself but it is the scene of good and evil depending on our choices',
    ],
  },
};

// ══════════════════════════════════════════════════════════════
// 8. CLASSIC LITERATURE (literature)
// ══════════════════════════════════════════════════════════════
const literature = {
  cat: {
    slug: 'literature',
    label: 'Classic Literature',
    icon: '📚',
    description: 'Timeless opening lines, iconic passages, and prose from masterworks',
    display_order: 9,
  },
  data: {
    easy: [
      'Call me Ishmael today', 'Winter came to stay', 'Words hold great magic', 'Books unlock ancient minds',
      'The great story begins', 'Read between the lines', 'Stories endure forevermore', 'Turn the printed page',
      'Ink flows upon parchment', 'Characters come to life', 'Plots twist and turn', 'A hero starts journey',
      'The quest begins now', 'Shadows fall across valley', 'Once upon a time', 'Far beyond the horizon',
      'The clock struck thirteen', 'Lantern flickered in darkness', 'Footsteps echoed down hall', 'A mysterious letter arrived',
      'The secret was revealed', 'Destiny called his name', 'Love conquered ancient sorrow', 'The journey home ended',
      'Whispers in the library', 'Volumes bound in leather', 'Poetry stirs the soul', 'Prose paints vivid pictures',
      'Legends whispered in taverns', 'Tales told by firelight', 'Echoes of forgotten lore', 'The ship set sail',
      'Adventures await the brave', 'Courage tested by adversity', 'Fate sealed with kiss', 'Tears shed in silence',
      'Joy returned to kingdom', 'A classic tale told', 'Memories written in stone', 'Dreams woven in words',
      'Midnight strikes the bell', 'Pages yellow with age', 'Read beneath the lamp', 'Find truth in fiction',
      'Old stories teach lessons', 'The narrator begins speaking', 'Villains meet their fate', 'Heroes find redemption now',
      'A quiet autumn evening', 'Wind howling through pines', 'Castle stood upon cliff', 'Candle burns down low',
      'The library smelled wonderful', 'Bookmark marks the spot', 'End of first chapter', 'Mystery deepens with time',
      'Tragedy strikes the innocent', 'Comedy delights the court', 'Romance blossoms in spring', 'Epic battles shake earth',
      'Honor guiding the knight', 'Swords clash in battle', 'Banners fly in wind', 'Crown sits upon brow',
      'The kingdom found peace', 'A wanderer entered town', 'Strange footsteps outside door', 'Dusty manuscripts in cellar',
      'The author finished masterpiece', 'Words outlive the author', 'Stories span all generations', 'Imagination knows no limits',
      'Every book holds worlds', 'Open your reading eyes', 'Travel through time pages', 'Discover forgotten old realms',
      'Villages nestled in valleys', 'Dragons slept under mountain', 'Brave hobbits walked forward', 'A ring of power',
      'The great gates opened', 'Stars watched over traveler', 'Morning brought sweet hope', 'The tempest raged wildly',
      'Ghosts haunted the moor', 'A detective solved case', 'The raven tapped window', 'Nevermore spoke the bird',
      'Fables carry moral truth', 'Myths explain the cosmos', 'Laughter fills the tavern', 'Farewell to dear friend',
      'The story ends here', 'Close the final book', 'Remember the spoken words', 'Wisdom lives in pages',
      'Treasures found in libraries', 'Read to understand life', 'Stories connect human hearts', 'Literature enriches the spirit',
    ],
    normal: [
      'It was the best of times it was the worst times',
      'All happy families resemble one another each unhappy family is unhappy',
      'Not all those who wander are truly lost in the woods',
      'Whatever our souls are made of his and mine are alike',
      'In a hole in the ground there lived a peaceful hobbit',
      'There is some good in this world worth fighting for always',
      'It was a bright cold day in April and clocks struck thirteen',
      'Someone must have slandered Josef K for one morning he was arrested',
      'As Gregor Samsa awoke one morning from uneasy dreams he found transformed',
      'Happy families are all alike every unhappy family is unhappy in own',
      'Whether I shall turn out to be the hero of my life',
      'The sun shone having no alternative on the nothing new under sun',
      'He was an old man who fished alone in a skiff',
      'You will rejoice to hear that no disaster has accompanied the commencement',
      'Mother died today or maybe yesterday I cannot be entirely certain now',
      'It is a truth universally acknowledged that a single man of fortune',
      'So we beat on boats against the current borne back ceaselessly',
      'The only way out of the labyrinth of suffering is forgiveness',
      'Beware for I am fearless and therefore extraordinarily powerful in my revenge',
      'There are more things in heaven and earth than are dreamt of',
      'Brevity is the soul of wit and tediousness the limbs thereof',
      'To be or not to be that is the eternal human question',
      'We are such stuff as dreams are made on in this life',
      'All the world is a stage and all men merely players',
      'Some are born great some achieve greatness and some have greatness thrust',
      'The fault dear Brutus is not in our stars but in ourselves',
      'A horse a horse my entire kingdom for a swift fresh horse',
      'Parting is such sweet sorrow that I shall say good night',
      'Lord what fools these mortal human beings be in the forest',
      'If music be the food of love play on give me excess',
      'Hell is empty and all the devils are wandering right here',
      'There is nothing either good or bad but thinking makes it so',
      'Though she be but little she is fierce in her convictions',
      'The course of true love never did run smooth across time',
      'Listen to many speak to a few and keep your own counsel',
      'Love looks not with the eyes but with the mind and soul',
      'What is done cannot be undone whispered the guilt ridden Scottish queen',
      'By the pricking of my thumbs something wicked this way comes forward',
      'One may smile and smile and still be an absolute villain inside',
      'Things without all remedy should be without regard what is done is done',
      'Words without thoughts never to heaven go uttered the praying troubled king',
      'Cowards die many times before their deaths the valiant never taste death',
      'Men at some time are masters of their own shifting earthly fates',
      'Suspicion always haunts the guilty mind the thief doth fear each bush',
      'Give every man thy ear but few thy voice in public discourse',
      'When sorrows come they come not single spies but in vast battalions',
      'Conscience doth make cowards of us all as we hesitate to act',
      'Rich gifts wax poor when givers prove unkind in their true hearts',
      'My words fly up my thoughts remain below words without thoughts never',
      'A little more than kin and less than kind muttered the prince',
      'Get thee to a nunnery why wouldst thou be a breeder sinners',
      'Something is rotten in the state of Denmark observed the watchful guard',
      'The lady doth protest too much methinks during the dramatic court play',
      'To thine own self be true and it must follow as night',
      'Neither a borrower nor a lender be for loan oft loses both',
      'This above all to thine own self be true through all seasons',
      'Stay gold Ponyboy stay gold whispered the dying brave young greaser',
      'It matters not what someone is born but what they grow be',
      'It is our choices that show what we truly are far more',
      'Words are in my not so humble opinion our inexhaustible magic source',
      'Do not pity the dead Harry pity the living above all those',
      'Of course it is happening inside your head why should that mean',
      'Until I feared I would lose it I never loved reading passionately',
      'Real courage is when you know you are licked before you begin',
      'You never really understand a person until you consider things from his point',
      'The scar had not pained Harry for nineteen years all was well',
      'I cannot carry the ring for you but I can carry you',
      'Even the smallest person can change the course of the entire future',
      'Courage is found in unlikely places where hope seems utterly exhausted today',
      'The world is indeed full of peril and in it there are',
    ],
    hard: [
      'It is a truth universally acknowledged that a single man in possession of a good fortune must be in want of wife',
      'So we beat on boats against the current borne back ceaselessly into the romantic and elusive corridors of the past',
      'The only way out of the labyrinth of human suffering is to choose forgiveness and compassion over resentment and cold vengeance',
      'All that is gold does not glitter and not all those who wander aimlessly across mountain paths are truly lost in spirit',
      'Beware for I am fearless and therefore extraordinarily powerful when confronting those who sought to destroy my gentle creators and dreams',
      'In a hole in the ground there lived a hobbit not a nasty dirty wet hole but cozy hobbit hole with comfort',
      'It was the best of times it was the worst of times it was the age of wisdom and foolishness alike',
      'All happy families resemble one another each unhappy family is unhappy in its own unique and heart wrenching individual manner',
      'Someone must have been telling lies about Josef K for without having done anything wrong he was arrested one fine morning',
      'As Gregor Samsa awoke one morning from uneasy dreams he found himself transformed in his bed into a gigantic insect',
      'It was a bright cold day in April and the clocks on the city towers were striking thirteen ominous heavy chimes',
      'Whether I shall turn out to be the hero of my own life or whether that station will be held by another',
      'The sun shone having no alternative on the nothing new as it illuminated the barren and timeless streets of the city',
      'He was an old man who fished alone in a skiff in the Gulf Stream and had gone eighty four days now',
      'You will rejoice to hear that no disaster has accompanied the commencement of an enterprise which you have regarded with evil forebodings',
      'Mother died today or maybe yesterday I cannot be sure as the telegram from the retirement home arrived without specific dates',
      'If you really want to hear about it the first thing you will probably want to know is where I was born',
      'There is no greater agony than bearing an untold story inside you as you wander through the silent landscapes of your life',
      'Whatever our souls are made of his and mine are identical while the rest of the world remains distant and strange',
      'There are more things in heaven and earth Horatio than are dreamt of in your narrow and rigid philosophical systems',
      'We are such stuff as dreams are made on and our little earthly life is rounded with a deep and quiet sleep',
      'Some are born great some achieve greatness and some have greatness thrust upon them unexpectedly by the winds of shifting fortune',
      'The fault dear Brutus is not in our stars but in ourselves that we are underlings submitting meekly to mortal rulers',
      'A coward dies a thousand deaths before his time while the valiant man never tastes of death but once in life',
      'Tomorrow and tomorrow and tomorrow creeps in this petty pace from day to day to the last syllable of recorded history',
      'Out out brief candle life is but a walking shadow a poor player that struts and frets his hour upon stage',
      'It is a tale told by an idiot full of sound and fury signifying nothing at the conclusion of mortal striving',
      'All the world is a stage and all the men and women merely players who enter perform and exit quietly',
      'I wandered lonely as a cloud that floats on high o’er vales and hills when all at once I saw golden daffodils',
      'To see a world in a grain of sand and a heaven in a wild flower hold infinity in the palm',
    ],
  },
};

// Write Batch 2
[philosophy, literature].forEach(({ cat, data }) => {
  writeCategorySeedFile(cat, data);
});
