import { writeCategorySeedFile } from './builder.mjs';

// ══════════════════════════════════════════════════════════════
// 1. CASUAL DAILY (casual)
// ══════════════════════════════════════════════════════════════
const casual = {
  cat: {
    slug: 'casual',
    label: 'Casual Daily',
    icon: '☀️',
    description: 'Everyday phrases, polite greetings, and common chatter',
    display_order: 1,
  },
  data: {
    easy: [
      'Good morning everyone', 'How are you today', 'See you tomorrow morning', 'Take care of yourself',
      'Keep in touch often', 'Call me back later', 'Time to wake up', 'Dinner is ready now',
      'Enjoy your fresh meal', 'Catch you later friend', 'Thanks for your help', 'Nice to meet you',
      'Have a nice flight', 'Please wait outside here', 'I need some water', 'The bus is here',
      'Let us eat lunch', 'What a wonderful day', 'Sounds good to me', 'Turn on the lights',
      'Sleep well tonight friend', 'Have fun this evening', 'Keep up good work', 'Coffee smells so good',
      'Welcome to our neighborhood', 'Grab your warm coat', 'The sun is shining', 'Let me know soon',
      'I am feeling great', 'Walk with me today', 'Put on your shoes', 'Open the front window',
      'Pack your school bag', 'Wash your hands first', 'Turn off the television', 'The weather is nice',
      'I need some groceries', 'Let me check schedule', 'Pass the salt please', 'I will arrive soon',
      'Have a great weekend', 'Where did you park', 'Finished my morning coffee', 'Grab lunch together soon',
      'The train arrives soon', 'Close the wooden door', 'Forgot my small umbrella', 'Meeting starts right now',
      'Can we reschedule tomorrow', 'Running a bit late', 'Store closes at nine', 'Take shortcut through park',
      'See the morning news', 'Head home right now', 'Traffic was very bad', 'Carry these paper bags',
      'Left phone on counter', 'Movie starts at seven', 'Pizza arrives any minute', 'Charge my laptop battery',
      'Remember her special birthday', 'Kids playing in yard', 'Dentist appointment this afternoon', 'Try that new restaurant',
      'Lock the garage door', 'Bake fresh berry muffins', 'Pour another cup tea', 'Wipe the kitchen table',
      'Fold the clean clothes', 'Sweep the front porch', 'Feed the hungry puppy', 'Water the red flowers',
      'Turn on garden sprinkler', 'Listen to radio show', 'Read the daily newspaper', 'Check the mailbox outside',
      'Pick up fresh bread', 'Buy some sweet apples', 'Chop the fresh carrots', 'Heat the vegetable soup',
      'Set the dining table', 'Clear the dirty dishes', 'Dry the wet towels', 'Make your cozy bed',
      'Iron your clean shirt', 'Tie your sneaker laces', 'Brush your teeth well', 'Comb your messy hair',
      'Check the bus schedule', 'Look at morning sky', 'Feel the gentle breeze', 'Watch the sunset glow',
      'Stars shine bright tonight', 'Turn off night lamp', 'Set the morning alarm', 'Rest your tired eyes',
      'Dreams come true always', 'Peaceful night to all', 'Wake with joyful heart', 'Ready for new day',
    ],
    normal: [
      'I am going to the grocery store right now',
      'Could you please send me that recipe later',
      'Let me know when you arrive at the station',
      'We are planning a small picnic this coming Saturday',
      'I forgot to turn off the kitchen lights downstairs',
      'Do you prefer drinking hot tea or iced coffee',
      'It looks like it might rain later this afternoon',
      'Can you pick up some fresh milk on your way',
      'I need to take the dog out for a walk',
      'Let us meet at the coffee shop around noon',
      'She recommended a really great book for me to read',
      'How was your trip to the coast last weekend',
      'Please remember to lock the front door when leaving',
      'I had a really productive afternoon at the office',
      'What time does the movie start at the cinema',
      'I think I left my keys on the counter',
      'We should order takeout for dinner tonight instead of cooking',
      'The train was surprisingly on time during morning rush',
      'My phone battery is running low so charge it',
      'Let me check what we have in the refrigerator',
      'I am looking forward to seeing everyone this holiday',
      'He baked homemade chocolate chip cookies for the party',
      'Could you turn down the volume just a bit',
      'I usually take a quick walk during lunch break',
      'The morning air feels remarkably crisp and refreshing today',
      'Don’t forget your warm jacket because it gets chilly',
      'We spent the entire evening chatting on the porch',
      'Can someone help me move this heavy wooden table',
      'I finally finished folding all of the clean laundry',
      'That was one of the funniest stories I heard',
      'I need to buy a birthday card this afternoon',
      'Did anyone remember to water the house plants today',
      'Let us take the stairs instead of the elevator',
      'I hope you have a relaxing and peaceful Sunday',
      'It took twenty minutes to find a parking spot',
      'Can you grab an extra napkin from the dispenser',
      'We should catch up properly over dinner next week',
      'The flowers in the garden are starting to bloom',
      'I always enjoy listening to gentle acoustic guitar music',
      'Everything went according to the original plan this morning',
      'Can you help me carry these heavy grocery bags inside',
      'The kids are having fun building castles in the sandbox',
      'I will call you back as soon as I finish',
      'There is a brand new coffee shop opening down street',
      'We decided to watch a comedy film after dinner tonight',
      'She bought a beautiful blue dress for the wedding reception',
      'Remember to put on sunscreen before walking to the beach',
      'I prefer taking public transit rather than driving during rush',
      'The smell of freshly brewed coffee filled the entire room',
      'He always takes his time cooking a wholesome weekend breakfast',
      'Could you grab an umbrella in case it rains today',
      'Our flight was delayed by thirty minutes due to weather',
      'They spent the afternoon wandering through the local farmers market',
      'Please make sure the cat has fresh water and food',
      'I love taking quiet morning strolls before the city wakes',
      'We enjoyed a delicious homemade dinner with our close friends',
      'Can we stop by the pharmacy on our way home',
      'She received a heartwarming postcard from her grandparents in Italy',
      'The autumn leaves are turning vibrant shades of red gold',
      'I need to schedule an appointment with the dentist soon',
      'Let us sit outside and enjoy this pleasant sunny weather',
      'He forgot his reading glasses on his office writing desk',
      'They are planning a weekend camping trip near the lake',
      'Please wipe the dining table after you finish your meal',
      'I listened to an inspiring podcast during my daily commute',
      'She always shares the most wonderful homemade baking treats with us',
      'We stopped by the bakery to pick up warm croissants',
      'It is always a pleasure catching up with old friends',
      'Could you turn on the porch light before it darkens',
      'I am looking forward to sleeping in late tomorrow morning',
    ],
    hard: [
      'I was thinking we could invite our neighbors over for a casual backyard barbecue this weekend',
      'If you have some free time this afternoon could you help me assemble this new bookshelf',
      'The grocery store was completely out of ripe avocados so I had to buy green ones instead',
      'Whenever the weather gets this warm I love sitting on the balcony reading a good novel',
      'Make sure you set your alarm clock fifteen minutes earlier so you do not miss the bus',
      'We had to wait in line for nearly forty minutes just to order our morning coffee',
      'I ran into an old high school friend while shopping at the supermarket yesterday afternoon',
      'Could you please double check if the garage door is completely closed before you go to sleep',
      'After walking through the botanical gardens all morning we stopped at a quiet little noodle place',
      'It has been such a hectic week at work that I cannot wait to sleep in tomorrow',
      'I promised my sister I would water her houseplants and feed her cat while she is away',
      'The local farmers market on Saturday mornings always has the sweetest fresh strawberries and homemade pastries',
      'We decided to take the scenic coastal highway instead of rushing down the crowded toll road',
      'Before we head out for the day let us make sure we packed sunscreen and water bottles',
      'She spent the rainy afternoon organizing old family photo albums and sipping hot peppermint tea',
      'If everyone chips in to clean up the kitchen we will finish in no time at all',
      'I usually try to stretch for ten minutes right after waking up to get my energy going',
      'The neighborhood bakery down the street opens at sunrise and fills the entire block with fresh bread aromas',
      'We should probably leave twenty minutes ahead of schedule to account for potential highway construction delays',
      'It was so relaxing to sit by the open window and listen to the gentle evening rain',
      'Can you remind me to pick up the dry cleaning tomorrow morning on the way to work',
      'Cooking a hearty homemade soup from scratch takes patience but the delicious flavor is always worth the effort',
      'Everyone gathered in the cozy living room with warm mugs of cider to play board games together',
      'After spending all day unpacking cardboard boxes we finally settled down to enjoy our very first home dinner',
      'Taking a slow evening stroll around the quiet neighborhood block helps clear my head before heading to sleep',
      'We spent hours sitting around the campfire telling funny childhood stories under a canopy of twinkling stars',
      'She spent the entire morning searching through drawers looking for her favorite pair of silver earrings',
      'Having a warm cup of herbal chamomile tea before bedtime is my favorite way to unwind completely',
      'The children were so excited about the upcoming family vacation that they could barely fall asleep last night',
      'A quiet weekend afternoon spent tending the garden brings more peace than any crowded downtown shopping mall',
    ],
  },
};

// ══════════════════════════════════════════════════════════════
// 2. FAMOUS QUOTES (quotes)
// ══════════════════════════════════════════════════════════════
const quotes = {
  cat: {
    slug: 'quotes',
    label: 'Famous Quotes',
    icon: '💬',
    description: 'Inspirational quotes and timeless reflections from notable figures',
    display_order: 3,
  },
  data: {
    easy: [
      'Love what you do', 'Never give up hope', 'Be the change today', 'Knowledge is true power',
      'Stay hungry stay foolish', 'Simplicity is ultimate sophistication', 'Think outside the box',
      'Fortune favors the brave', 'Time waits for nobody', 'Every moment matters deeply',
      'Truth shall set free', 'Believe you can succeed', 'Dream big work hard', 'Action speaks louder words',
      'Silence is golden speech', 'Patience is bitter virtue', 'Kindness costs nothing ever',
      'Life is very short', 'Choose courage over comfort', 'Creativity takes great courage',
      'Live and let live', 'Hope anchors human soul', 'Wisdom begins with wonder',
      'No pressure no diamonds', 'Failure is learning opportunity', 'Light overcomes all darkness',
      'Peace begins with smile', 'Character is destiny always', 'Happiness is inside you',
      'Honesty is best policy', 'Practice makes master craft', 'Small deeds beat intentions',
      'Live in the present', 'Grace under extreme pressure', 'Forgive but never forget',
      'Joy is contagious energy', 'Courage conquers all fear', 'Faith moves mighty mountains',
      'Gratitude changes everything now', 'Beauty lies within simplicity', 'Listen more speak less',
      'Brevity is wit soul', 'Seek truth not praise', 'Great things take time',
      'Mind over physical matter', 'Keep your eyes forward', 'Stand for noble ideals',
      'Lead by humble example', 'Speak with honest intention', 'Victory belongs to persistent',
      'Dare to know yourself', 'Trust your inner voice', 'Change begins from within',
      'Stars require deep darkness', 'Rise above the noise', 'Embrace every new challenge',
      'Never stop asking questions', 'Curiosity opens every door', 'Patience brings sweetest fruit',
      'Focus on what matters', 'Leave world better place', 'Inspire someone today friend',
      'Every expert was beginner', 'Make today count forever', 'Stand tall through storms',
      'Create your own sunshine', 'Follow your true north', 'Cherish the journey always',
      'Small steps bring victory', 'Energy flows where attention', 'Boldness has genius power',
      'Keep learning every day', 'Shine bright without apology', 'Plant seeds for tomorrow',
      'Kind words heal wounds', 'Stay humble through success', 'Turn scars into wisdom',
      'Greatness lies in service', 'Breathe through the chaos', 'Choose love over fear',
      'Let your light shine', 'Sow seeds of kindness', 'Honor your daily truth',
      'Live with deep gratitude', 'Seek beauty in ordinary', 'Strength grows through resistance',
      'Write your own story', 'Never regret being kind', 'Quiet minds hear wisdom',
      'Work with passionate purpose', 'Build bridges not walls', 'Courage is contagious always',
      'Keep moving forward bravely', 'Celebrate every small win', 'Lift others as climb',
      'Purity of thought guides', 'Inner peace surpasses understanding', 'Find joy in journey',
      'Be gentle with yourself', 'Create with open heart', 'Wisdom outlasts all gold',
    ],
    normal: [
      'The only way to do great work is to love what you do',
      'In the middle of difficulty lies great opportunity for growth',
      'Life is what happens while you are making other plans',
      'The future belongs to those who believe in their dreams',
      'It does not matter how slowly you go as long as you do not stop',
      'The best time to plant a tree was twenty years ago',
      'Be the change that you wish to see in this world',
      'Success is not final and failure is not fatal in life',
      'To be yourself in a conformist world is the greatest triumph',
      'The mind is everything what you think you eventually become',
      'Imagination is more important than knowledge in creative pursuits',
      'Happiness is not something readymade it comes from your actions',
      'Do what you can with what you have right where you are',
      'Not all those who wander are lost in the deep woods',
      'In the depth of winter I found an invincible summer inside',
      'Darkness cannot drive out darkness only light can do that',
      'The journey of a thousand miles begins with a single step',
      'What lies behind us and before us are tiny matters compared within',
      'The greatest glory in living lies not in never falling',
      'An unexamined life is truly not worth living for any human',
      'Act as if what you do makes a difference because it does',
      'You must do the things you think you cannot possibly do',
      'Turn your wounds into wisdom and your challenges into greatest assets',
      'If you want to lift yourself up lift up someone else',
      'The purpose of our lives is to be happy and helpful',
      'Change your thoughts and you change your entire reality around you',
      'We become what we think about most of the waking time',
      'It always seems impossible until it is finally achieved by someone',
      'Do not go where the path may lead go where there is no path',
      'Live as if you were to die tomorrow and learn as if forever',
      'Everything you have ever wanted is sitting on the other side of fear',
      'Happiness depends upon ourselves and not upon external shifting circumstances',
      'Peace comes from within do not seek it without in worldly praise',
      'A room without books is like a body without a soul',
      'Knowing yourself is the beginning of all true wisdom and enlightenment',
      'There is nothing either good or bad but thinking makes it so',
      'If you tell the truth you do not need to remember anything',
      'We must accept finite disappointment but never lose infinite genuine hope',
      'Keep your face always toward the sunshine and shadows will fall behind',
      'No one can make you feel inferior without your own consent',
      'Success usually comes to those who are too busy looking for it',
      'You will face many defeats in life but never let yourself be defeated',
      'The secret of getting ahead is simply getting started right now',
      'Opportunities multiply as they are seized with bold decisive action',
      'What we achieve inwardly will change outer reality in surprising ways',
      'The greatest wealth is to live content with very little in heart',
      'Do not wait to strike till the iron is hot make it hot',
      'Simplicity is the keynote of all true elegance in life',
      'Defeat is not the worst of failures not to have tried is true failure',
      'A champion is defined not by their wins but how they recover',
      'The only true wisdom is knowing that you know almost nothing',
      'Energy and persistence conquer all obstacles across human endeavors and history',
      'Your time is limited so do not waste it living someone else life',
      'Character is like a tree and reputation is like its fleeting shadow',
      'To succeed in life you need two things ignorance and boundless confidence',
      'The brave man is not he who does not feel afraid',
      'Great minds discuss ideas average minds discuss events small minds discuss people',
      'He who has courage and faith will never perish in misery',
      'Live each day as if your life had just begun today',
      'It is during our darkest moments that we must focus to see light',
      'Nothing great was ever achieved without enthusiastic dedication and persistent effort',
      'The best revenge is massive success achieved through calm quiet excellence',
      'Education is the most powerful weapon which you can use to change world',
      'We are what we repeatedly do excellence then is a lasting habit',
      'Stay true to yourself and the world will adjust around you',
      'Doubt kills more dreams than failure ever will in human lives',
      'Let the beauty of what you love be what you do daily',
      'Where there is love there is life and enduring hope for all',
      'A person who never made a mistake never tried anything new',
      'Count your age by friends not years count life by smiles not tears',
    ],
    hard: [
      'To be yourself in a world that is constantly trying to make you something else is greatest accomplishment',
      'Success is not final failure is not fatal it is the courage to continue that counts through all storms',
      'Our greatest glory is not in never falling but in rising every time we fall upon difficult ground',
      'Two roads diverged in a wood and I took the one less traveled by and that made all difference',
      'In the end we will remember not the words of our enemies but the silence of our true friends',
      'The question isn’t who is going to let me it is who is going to stop me from striving forward',
      'Twenty years from now you will be more disappointed by the things you didn’t do than by the ones you did',
      'Spread love everywhere you go let no one ever come to you without leaving happier and far more peaceful',
      'I have learned that people will forget what you said people will forget what you did but never how you made feel',
      'Do not dwell in the past do not dream of the future concentrate the mind on the present waking moment',
      'Whatever you are physically or mentally you are because you have chosen to be that way through daily habits',
      'The only limit to our realization of tomorrow will be our doubts of today let us advance with strong faith',
      'When one door of happiness closes another opens but often we look so long at the closed door we miss open one',
      'You cannot swim for new horizons until you have courage to lose sight of the familiar shore for long while',
      'It is not the critic who counts not the man who points out how the strong man stumbles or where deeds fell short',
      'The credit belongs to the man who is actually in the arena whose face is marred by dust and sweat and blood',
      'Live in such a way that if someone spoke badly of you no one would ever believe them for single moment',
      'What you do speaks so loudly that I cannot hear what you say about your noble intentions and grand promises',
      'Watch your thoughts they become your words watch your words they become your actions and watch your actions they become character',
      'A bird sitting on a tree is never afraid of the branch breaking because her trust is not on branch but wings',
      'We do not inherit the earth from our ancestors rather we borrow it carefully from our children for future generations',
      'Give me six hours to chop down a tree and I will spend the first four sharpening the axe with precision',
      'The greatest danger for most of us is not that our aim is too high and we miss it but too low',
      'Peace cannot be kept by force it can only be achieved through genuine empathy and profound mutual understanding among nations',
      'Stand up for what is right even if you stand completely alone against the howling winds of popular public opinion',
      'The ultimate measure of a man is not where he stands in moments of comfort but where he stands at challenge',
      'Real integrity is doing the right thing knowing that nobody is going to know whether you did it or not',
      'If you cannot fly then run if you cannot run then walk if you cannot walk then crawl keep moving',
      'Do not judge each day by the harvest you reap but by the seeds that you carefully plant into soil',
      'Happiness is when what you think what you say and what you do are all in complete and beautiful harmony',
    ],
  },
};

// ══════════════════════════════════════════════════════════════
// 3. PRO PROGRAMMING (programming)
// ══════════════════════════════════════════════════════════════
const programming = {
  cat: {
    slug: 'programming',
    label: 'Pro Programming',
    icon: '💻',
    description: 'Code patterns, system architecture, engineering lore, and developer wit',
    display_order: 4,
  },
  data: {
    easy: [
      'Write clean readable code', 'Fix compiler syntax error', 'Commit changes to git', 'Push code to main',
      'Deploy service to production', 'Build pipeline succeeded today', 'Review incoming pull request', 'Resolve merge conflict now',
      'Refactor messy legacy functions', 'Run automated test suite', 'Check server error logs', 'Optimize slow database query',
      'Cache frequent API responses', 'Containerize modern backend services', 'Index primary database tables', 'Prevent memory leak issues',
      'Handle null pointer exceptions', 'Implement binary search tree', 'Sort array in place', 'Validate user input strings',
      'Sanitize database query inputs', 'Monitor application response time', 'Scale cluster horizontally now', 'Encrypt sensitive user credentials',
      'Parse incoming JSON payload', 'Configure reverse proxy routes', 'Manage global state stores', 'Benchmark CPU execution speed',
      'Profile memory heap allocations', 'Design responsive user interfaces', 'Minify production asset files', 'Implement rate limiting rules',
      'Automate repetitive development tasks', 'Debug async race conditions', 'Upgrade outdated software dependencies', 'Follow continuous integration practices',
      'Enforce strict typing rules', 'Document public API endpoints', 'Mock external network calls', 'Configure local environment variables',
      'Generate secure access tokens', 'Rotate database secret keys', 'Define reusable component props', 'Format code with prettier',
      'Inspect network payload headers', 'Track uncaught runtime exceptions', 'Write modular helper utilities', 'Audit open source packages',
      'Configure cloud load balancers', 'Implement optimistic UI updates', 'Talk is very cheap', 'Show me the code',
      'Code is like humor', 'Deleted code is debugged', 'Make it work first', 'Make it run fast',
      'Make it clean right', 'Premature optimization brings evil', 'Simplicity is true efficiency', 'First solve the problem',
      'Then write clean code', 'Testing leads to understanding', 'Functions should do one', 'Do that one well',
      'Walking on water easier', 'Specs are deeply frozen', 'Nine people cannot deliver', 'Babies in single month',
      'Any fool can code', 'Good coders write humans', 'Debugging twice as hard', 'Writing the first place',
      'Cache invalidation is hard', 'Naming things is hard', 'Off by one errors', 'Software entropy always increases',
      'Best error never shows', 'Avoid global variable state', 'Pure functions prevent bugs', 'Immutability ensures predictable state',
      'Async await simplifies callbacks', 'Promises resolve or reject', 'Map filter reduce arrays', 'Typescript catches compile bugs',
      'Use semantic html tags', 'Keep components small reusable', 'Hooks manage lifecycle state', 'Custom hooks encapsulate logic',
      'Virtual dom diffs nodes', 'Tailwind speeds up styling', 'Nextjs optimizes route loading', 'Server components stream html',
      'Prisma queries relational tables', 'Postgres handles complex joins', 'Redis stores ephemeral sessions', 'Websockets enable live duplex',
      'GraphQL queries exact shapes', 'REST apis follow verbs', 'Docker isolates runtime environments', 'Kubernetes orchestrates pod clusters',
    ],
    normal: [
      'Every great developer got there by solving problems they were unqualified to solve',
      'The best error message is the one that never shows up to user',
      'Talk is cheap show me the actual working implementation in code',
      'Programs must be written for people to read and only incidentally for machines',
      'Code is like humor when you have to explain it it is bad',
      'Always write code as if the maintainer knows where you live',
      'A software function should do one thing and do it exceptionally well',
      'Walking on water and developing software from specifications are both easy if frozen',
      'Make it work correctly make it right and then make it fast',
      'Premature optimization is the root of all evil in software engineering',
      'It is not a software bug it is an undocumented creative feature',
      'Nine programmers cannot make a software release in one single month',
      'Any fool can write code that computers understand good programmers write human readable',
      'Debugging is twice as hard as writing the code in first place',
      'There are only two hard things cache invalidation and naming things',
      'Simplicity of system architecture is the true soul of sustainable engineering',
      'Programming is not merely typing syntax it is rigorous structured thinking',
      'The best performance improvement is moving from nonworking to working state',
      'Software is like entropy it is difficult to grasp and always increases',
      'First solve the underlying user problem then write the minimal code required',
      'Testing leads to unexpected failure and failure leads to deep engineering understanding',
      'Continuous integration pipelines catch regressions before they impact live production users',
      'Immutable state structures prevent subtle concurrency race conditions across asynchronous threads',
      'Microservices introduce distributed network complexity while monolithic architectures simplify local debugging',
      'Relational database indices accelerate queries but impose measurable write throughput overhead',
      'Writing automated unit tests provides a psychological safety net during refactoring',
      'Semantic versioning communicates breaking changes clearly to downstream open source consumers',
      'Proper error handling distinguishes robust production applications from fragile proof concepts',
      'Caching hot database queries in Redis dramatically reduces database cpu utilization',
      'Container orchestration simplifies rolling deployments with zero recorded service downtime',
      'Good documentation is just as valuable as elegant clean algorithms',
      'Stateless web servers scale horizontally across multi cloud availability zones seamlessly',
      'Static type checkers catch common null reference exceptions at compile time',
      'Monitoring request latency and error rates provides proactive visibility into systems',
      'Refactoring messy technical debt pays compounding dividends across software lifecycles',
      'Asynchronous event queues decouple long running background jobs from request handlers',
      'Code reviews encourage knowledge sharing and maintain consistency across engineering teams',
      'Automated database migrations ensure reproducible schema state across staging and production',
      'Designing backward compatible RESTful endpoints prevents unexpected breakage for mobile clients',
      'A clean git commit history tells a coherent story of development',
      'Declarative user interfaces simplify state synchronization between backend models and screens',
      'Rate limiting protects vulnerable authentication endpoints against brute force credential stuffing',
      'Dependency injection fosters modular architecture and simplifies writing mock unit tests',
      'Serverless computing eliminates server management overhead but introduces cold start latency',
      'Garbage collection pauses can introduce unpredictable latency spikes in real time applications',
      'Cross origin resource sharing policies protect browser clients from malicious external domains',
      'Configuring proper content security policy headers mitigates cross site scripting vulnerabilities',
      'Structured JSON logging simplifies debugging distributed microservices through centralized search clusters',
      'Writing idempotency keys into payment requests prevents accidental double billing for customers',
      'Benchmarking under realistic production load exposes bottleneck locks before customer traffic arrives',
      'Event sourcing captures state mutations as immutable sequences of historical facts',
      'Feature flags allow engineering teams to decouple code deployment from release',
      'Optimistic locking mechanisms detect concurrent database row modifications without blocking transactions',
      'GraphQL allows client applications to request precisely the attributes they need',
      'Database connection pooling prevents thread exhaustion under sudden high concurrency spikes',
      'Clean software architecture separates domain business rules from external transport mechanisms',
      'Domain driven design models complex enterprise workflows into ubiquitous shared vocabularies',
      'Zero downtime database schema migrations require additive non breaking multi stage releases',
      'Edge compute functions execute logic geographically closer to global end users',
      'Automated dependency security scanners identify known published vulnerabilities in project lockfiles',
      'Static site generation produces blazing fast web pages with minimal compute',
      'WebAssembly enables high performance compiled algorithms to run securely inside browsers',
      'Distributed tracing assigns correlation identifiers to track requests across microservice boundaries',
      'Circuit breakers prevent cascade failures when upstream third party dependencies become unresponsive',
      'Consistent code formatting eliminates bikeshedding arguments during asynchronous pull request reviews',
      'Database replication provides high availability read scaling across disparate geographic data centers',
      'Strongly typed programming languages reduce cognitive load when navigating large unfamiliar codebases',
      'Single responsibility principle ensures modules change for only one well defined reason',
      'Inversion of control containers decouple high level policy from low level implementations',
      'The most reliable code is the code that you never had to write',
    ],
    hard: [
      'Always write code as if the person who ends up maintaining it will be a violent psychopath who knows where you live',
      'Deleted code is debugged code and the fastest code is the routine that never executes during runtime',
      'Controlling complexity is the essence of computer programming and simplicity is prerequisite for reliability in software',
      'Measuring programming progress by lines of code is like measuring aircraft building progress by physical weight and volume',
      'There are two ways of constructing software design one is to make it so simple that there are obviously no deficiencies',
      'The other way is to make it so complicated that there are no obvious deficiencies in architecture',
      'Walking on water and developing software from a specification are easy only when both requirements are completely frozen solid',
      'Premature optimization is the root of all evil yet we should not pass up our opportunities in critical hotspots',
      'A language that doesn’t affect the way you think about programming is not worth knowing or studying deeply',
      'Before software can be reusable it first has to be usable and verified through realistic production traffic loads',
      'The function of good software architecture is to postpone speculative implementation decisions as long as possible without penalty',
      'Good code is its own best documentation as you are about to add a comment ask yourself how code could clarify',
      'It is practically impossible to teach good programming to students that have had a prior exposure to undisciplined hacking',
      'Simplicity does not precede complexity but follows it after countless iterations of refactoring and ruthless distillation of requirements',
      'The greatest performance improvements arise not from micro optimizing inner loops but from designing superior algorithmic data structures',
      'Distributed systems are inherently unpredictable because network partitions machine crashes and clock drift will inevitably happen simultaneously',
      'Writing comprehensive automated test coverage does not guarantee absence of software defects but it guarantees regressions are rapidly detected',
      'Decoupling state mutation from pure side effect computation makes asynchronous applications substantially easier to test and reason about',
      'When microservices multiply without clear organizational domain boundaries network latency and distributed failure modes multiply exponentially across production',
      'Engineering teams that prioritize continuous refactoring and eliminate technical debt ship features with consistent velocity over years',
      'A database without foreign key constraints and transactional integrity guarantees will eventually accumulate corrupt orphaned data under high concurrency',
      'Software engineers must resist the temptation to invent complex custom abstractions when standard boring battle tested solutions already exist',
      'Ensuring end to end type safety from backend database schemas to frontend user interface components eliminates entire classes of runtime errors',
      'Building resilient systems requires embracing failure as normal event rather than rare anomaly through chaos testing and graceful degradation',
      'The cost of fixing a software defect increases by an order of magnitude at each phase from unit testing to production release',
      'Caching invalidation remains treacherous because stale data can propagate silently through downstream services without triggering explicit error alerts',
      'Every complex system that works was found to have evolved from a simple system that worked reliably in production',
      'Over engineering occurs when developers solve hypothetical future problems rather than addressing current verified concrete requirements of users',
      'Clean code reads like well written prose where classes and functions reveal their architectural intent without cognitive friction',
      'Observability requires collecting structured telemetry logs distributed tracing metrics and actionable alerts to diagnose novel emergent production behaviors',
    ],
  },
};

// ══════════════════════════════════════════════════════════════
// 4. COMPOUND IDIOMS (idioms)
// ══════════════════════════════════════════════════════════════
const idioms = {
  cat: {
    slug: 'idioms',
    label: 'Compound Idioms',
    icon: '🧩',
    description: 'Colorful English idioms, figures of speech, and proverbial wisdom',
    display_order: 5,
  },
  data: {
    easy: [
      'Bite the bullet now', 'Break a leg tonight', 'Cost an arm leg', 'Piece of sweet cake',
      'Hit the sack early', 'Under the chilly weather', 'Spill the secret beans', 'See eye to eye',
      'Cut corners on work', 'Once in blue moon', 'Burn the midnight oil', 'Cold feet at last',
      'Speak of the devil', 'Best of both worlds', 'Blessing in clever disguise', 'Call it a day',
      'Barking up wrong tree', 'Cry over spilled milk', 'Every cloud silver lining', 'Hit nail on head',
      'Keep chin up high', 'Kill two birds stones', 'Let sleeping dogs lie', 'Miss the moving boat',
      'No pain no gain', 'On the same page', 'Penny for your thoughts', 'Pull someone quick leg',
      'Shape up or ship', 'Spill your true feelings', 'Take with grain salt', 'Taste of own medicine',
      'Through thick and thin', 'Time flies so fast', 'Up in the air', 'Weather the fierce storm',
      'Wild goose chase adventure', 'Wrapped around little finger', 'Your guess is mine', 'Back to drawing board',
      'Ball is your court', 'Beat around the bush', 'Bite off more chew', 'Burn bridges behind you',
      'Catch red handed today', 'Curiosity killed the cat', 'Devil in the details', 'Down to the wire',
      'Draw the line clearly', 'Drive someone up wall', 'Drop of a hat', 'Easier said than done',
      'Face the loud music', 'Fish out of water', 'Fit as a fiddle', 'Flash in the pan',
      'Get out of hand', 'Give benefit of doubt', 'Go down in flames', 'Go extra long mile',
      'Head in the clouds', 'Hold your horses now', 'In hot boiling water', 'Jump on the bandwagon',
      'Keep at arm length', 'Leave no stone unturned', 'Let cat out bag', 'Make ends meet today',
      'Off the beaten path', 'On thin slippery ice', 'Out of the woods', 'Play devil own advocate',
      'Pull yourself together now', 'Raining cats and dogs', 'Ring a distant bell', 'Roll with the punches',
      'Rule of thumb rule', 'Save for rainy day', 'Shoot from the hip', 'Sight for sore eyes',
      'Skeleton in the closet', 'Skin of your teeth', 'Sleep like a log', 'Smell something very fishy',
      'Snowed under with work', 'Spick and clean span', 'Steal someone shining thunder', 'Straight from horse mouth',
      'Straw that broke back', 'Take bull by horns', 'The elephant in room', 'The tip of iceberg',
      'Throw in the towel', 'Turn over new leaf', 'Under your very nose', 'Up to your ears',
      'Water under the bridge', 'Wear heart on sleeve', 'Wolf in sheep clothing', 'Word of mouth news',
    ],
    normal: [
      'A bird in the hand is worth two in bush',
      'A picture is worth a thousand words in storytelling',
      'Actions speak much louder than spoken words ever could',
      'All good things must come to an end eventually',
      'An apple a day keeps the doctor away safely',
      'Better late than never when doing the right thing',
      'Birds of a feather flock together in shared interest',
      'Do not put all your eggs in one fragile basket',
      'Do not count your chickens before they actually hatch',
      'Early bird catches the worm in morning quiet hours',
      'Every cloud has a silver lining if you look',
      'Fortune favors the bold and the brave in life',
      'Good things come to those who wait with patience',
      'Haste makes waste when rushing through critical important tasks',
      'If you cannot beat them join them in mutual effort',
      'It takes two to tango during delicate negotiations always',
      'Laughter is the best medicine for a heavy heart',
      'Look before you leap into unfamiliar risky new territory',
      'Make hay while the warm sun shines bright outside',
      'Necessity is the true mother of all human invention',
      'No use crying over spilled milk on kitchen floor',
      'Practice makes perfect through consistent daily discipline and dedication',
      'Rome was not built in a single day or night',
      'The grass is always greener on the other side',
      'The pen is mightier than the sword in history',
      'There is no place like home after long travel',
      'Too many cooks spoil the broth in busy kitchen',
      'Two heads are always better than one single head',
      'When in Rome do as the Romans do naturally',
      'You cannot judge a book by its glossy cover',
      'He decided to bite the bullet and make the apology',
      'She felt completely under the weather after catching the flu',
      'They were burning the midnight oil to finish the report',
      'We see eye to eye on almost every major decision',
      'Finding that parking spot was a blessing in clever disguise',
      'Let us call it a day and resume tomorrow morning',
      'The unexpected promotion came completely out of the clear blue',
      'He hit the nail on the head with that observation',
      'You should take his wild claims with a grain salt',
      'She was caught between a rock and a hard place',
      'They always go the extra mile to assist their customers',
      'He let the cat out of the bag about party',
      'Learning to drive a manual car was a piece cake',
      'She decided to take the bull by the horns directly',
      'That expensive antique watch cost him an arm and leg',
      'We are all in the same boat during difficult times',
      'He was walking on eggshells around his irritable new boss',
      'She has a heart of pure gold toward everyone around',
      'They had to face the music after losing the project',
      'It was the straw that broke the camel sturdy back',
      'He wears his heart on his sleeve for all see',
      'She is always barking up the wrong tree with accusations',
      'They decided to bury the hatchet and become close friends',
      'The team was firing on all cylinders during championship game',
      'He jumped out of the frying pan into the fire',
      'She has been snowed under with work all week long',
      'We need to get our ducks in a neat row',
      'That performance was just a flash in the pan moment',
      'He likes to play devil advocate during team brainstorm meetings',
      'She pulled strings behind the scenes to secure the interview',
      'They decided to turn over a brand new fresh leaf',
      'The company had to tighten its belt during economic downturn',
      'He was skating on very thin ice with his manager',
      'She gave him the benefit of doubt regarding the delay',
      'They managed to pull off the deal by skin teeth',
      'It is always water under the bridge after sincere apologies',
      'He spilled the beans about the secret surprise birthday dinner',
      'She was over the moon when she passed her exam',
      'They finally saw the light at the end of tunnel',
      'He threw in the towel after three grueling championship rounds',
    ],
    hard: [
      'He who hesitates is lost but he who leaps blindly without looking often lands in thorny ditch',
      'A rolling stone gathers no moss while stationary boulder slowly accumulates rich green tapestry of ancient wisdom',
      'You can lead a stubborn horse to clear mountain water but you cannot make him drink from stream',
      'When the going gets tough the tough get going and refuse to surrender to difficult outside circumstances',
      'Do not cross the rickety wooden bridge until you actually arrive at the edge of the rushing river',
      'The squeaky wheel gets the grease but the silent wheel quietly carries the heaviest cargo across long journeys',
      'It is always darkest just before the glorious dawn breaks through the misty mountain horizon in early morning',
      'Give a man a fish and you feed him for a day teach him to fish feeds lifetime',
      'A journey of a thousand miles must begin with a single determined step in the right direction today',
      'People who live in fragile glass houses should never throw heavy stone rocks at their quiet neighbors',
      'The road to hell is frequently paved with good intentions that were never translated into concrete thoughtful actions',
      'There is no honor among thieves until the gold is divided equally under the flickering light of lantern',
      'A chain is only as strong as its weakest link when enduring the relentless pull of heavy stress',
      'Too many cooks spoil the delicate broth because each insists on adding their own secret pinch of spice',
      'An ounce of sensible prevention is worth a full pound of painful cure after the damage has occurred',
      'Hope for the best prepare for the worst and take whatever comes with grace and unshakeable inner resilience',
      'Strike while the iron is glowing hot because cold metal resists even the heaviest hammer blows of blacksmith',
      'You cannot have your sweet cake and eat it too without eventually facing the empty plate before you',
      'Birds of a feather flock together in great numbers while the solitary eagle soars high above mountain peaks',
      'When one door closes another opens but we often gaze so longingly at the locked wooden portal',
      'Do not throw the healthy baby out with the dirty bathwater when attempting to clean up messy situation',
      'A rising tide lifts all boats in the tranquil harbor while sudden storm tests the seaworthiness of all',
      'The devil is in the granular details while salvation often lies in stepping back to see whole picture',
      'Fools rush in where wise angels fear to tread lightly across the treacherous ground of untested claims',
      'What doesn’t kill you makes you stronger provided you possess the emotional fortitude to learn from the wound',
      'A fool and his money are soon parted especially when flattered by cunning strangers offering effortless riches',
      'Cleanliness is next to godliness but genuine kindness and compassion outrank spotless floors every single hour of day',
      'He who laughs last laughs best because time has a curious way of vindicating the patient underdog',
      'Absence makes the fond heart grow fonder while constant familiarity can sometimes breed unnecessary contempt among close companions',
      'Every dark cloud possesses a shimmering silver lining if only travelers maintain the optimism to look upward steadily',
    ],
  },
};

// ══════════════════════════════════════════════════════════════
// 5. SCIENCE & COSMOS (science)
// ══════════════════════════════════════════════════════════════
const science = {
  cat: {
    slug: 'science',
    label: 'Science & Cosmos',
    icon: '🔬',
    description: 'Astronomy, quantum physics, biology, chemistry, and wonder of the universe',
    display_order: 6,
  },
  data: {
    easy: [
      'Gravity pulls objects downward', 'Light travels extremely fast', 'Cells divide to reproduce', 'Atoms form all matter',
      'Stars burn bright hydrogen', 'Energy cannot be destroyed', 'Water freezes at zero', 'Planets orbit the sun',
      'DNA carries genetic code', 'Photons have zero mass', 'Electrons orbit atomic nucleus', 'Protons carry positive charge',
      'Neutrons have neutral charge', 'Earth rotates on axis', 'Moon causes ocean tides', 'Sound waves require medium',
      'Prism splits white light', 'Magnets attract iron metal', 'Plants absorb carbon dioxide', 'Trees produce fresh oxygen',
      'Molecules bond together chemically', 'Enzymes speed up reactions', 'Fungi decompose organic matter', 'Bacteria live everywhere globally',
      'Viruses require host cells', 'Blood carries dissolved oxygen', 'Heart pumps red blood', 'Lungs breathe ambient air',
      'Brain contains billions neurons', 'Eyes perceive visible spectrum', 'Ears detect acoustic vibration', 'Skin protects internal organs',
      'Bones provide structural support', 'Muscles contract to move', 'Fossils preserve prehistoric life', 'Evolution shapes animal species',
      'Tectonic plates shift slowly', 'Volcanoes erupt molten lava', 'Earthquakes release seismic energy', 'Atmosphere shields harmful radiation',
      'Ozone layer absorbs ultraviolet', 'Rainbows refract rainy sunlight', 'Clouds consist of droplets', 'Lightning heats ambient air',
      'Thunder follows bright lightning', 'Glaciers carve deep valleys', 'Rivers flow toward oceans', 'Salt dissolves into water',
      'Acids taste very sour', 'Bases feel very slippery', 'Helium is lighter air', 'Iron rusts in moisture',
      'Combustion produces hot heat', 'Speed of light constant', 'Space is near vacuum', 'Black holes trap light',
      'Milky Way is galaxy', 'Andromeda collides with us', 'Comets have icy tails', 'Asteroids orbit between planets',
      'Supernovae forge heavy elements', 'Nebulae birth baby stars', 'Pulsars emit radio beams', 'Quasars shine across cosmos',
      'Dark matter binds galaxies', 'Cosmos expands every second', 'Universe began with bang', 'Entropy increases over time',
      'Absolute zero stops motion', 'Quantum particles can tunnel', 'Waves exhibit interference patterns', 'Laser light is coherent',
      'Solar panels convert photons', 'Nuclear fission splits atoms', 'Fusion powers our sun', 'Gravity bends passing light',
      'Time dilates at speed', 'Matter and energy equivalent', 'Chlorophyll absorbs red blue', 'Symbiosis benefits both species',
      'Predators hunt for prey', 'Herbivores eat green plants', 'Food webs sustain ecosystems', 'Coral reefs host biodiversity',
      'Plankton produce ocean oxygen', 'Mammals nurse their young', 'Reptiles lay scaly eggs', 'Birds evolved from dinosaurs',
      'Amphibians live double lives', 'Insects have six legs', 'Spiders spin silk webs', 'Bees pollinate blooming flowers',
      'Ants build complex colonies', 'Termites digest wooden fibers', 'Roots anchor tall trees', 'Leaves turn toward sunlight',
    ],
    normal: [
      'Photosynthesis converts radiant sunlight into chemical energy for growing plants',
      'DNA carries detailed genetic instructions for all living cellular organisms',
      'Black holes possess gravitational pulls that trap even fleeing light',
      'The speed of sound depends directly on the surrounding medium',
      'Quantum particles can exist in multiple probabilistic states simultaneously together',
      'Plate tectonics continuously reshape the continental landmasses of our planet',
      'Mitochondria generate adenosine triphosphate through respiration inside living eukaryotic cells',
      'The ozone layer absorbs dangerous ultraviolet radiation emitted by sun',
      'Radioactive isotopes decay into stable elements at mathematically predictable rates',
      'General relativity demonstrates that massive celestial bodies curve surrounding spacetime',
      'Supermassive black holes anchor the spinning centers of spiral galaxies',
      'Electromagnetic radiation travels across empty space at the speed light',
      'Natural selection drives the gradual evolution of species over epochs',
      'The periodic table organizes chemical elements by their atomic numbers',
      'Bioluminescent deep sea organisms generate cold light through chemical luciferin',
      'Cosmic microwave background radiation is the ancient thermal afterglow creation',
      'Enzymes act as biological catalysts lowering activation energy for reactions',
      'Neurotransmitters transmit electrochemical signals across microscopic synaptic gaps between neurons',
      'Tectonic subduction zones trigger intense volcanic eruptions and deep earthquakes',
      'The greenhouse effect traps atmospheric thermal infrared energy keeping Earth warm',
      'Gravitational waves ripple across spacetime when massive neutron stars collide',
      'Cellular mitosis produces two genetically identical daughter cells from parent',
      'Stem cells possess the remarkable capacity to differentiate into specialized tissues',
      'Hubble discovered that distant galaxies are rapidly receding away from us',
      'Quantum entanglement links particle properties instantaneously across vast cosmological distances',
      'The human genome contains approximately three billion nucleotide base pairs',
      'Superconductors conduct electrical current with zero resistance at cryogenic temperatures',
      'Thermodynamics dictates that total entropy in closed systems always increases',
      'Photosynthetic phytoplankton produce more than half of the planet oxygen',
      'Kepler laws precisely describe the elliptical orbits of planets orbiting stars',
      'Hydrogen is the most abundant chemical element throughout the observable universe',
      'The magnetic field of Earth deflects solar wind charged particles',
      'Epigenetic modifications alter gene expression without mutating the underlying DNA',
      'Dark energy constitutes roughly sixty eight percent of total cosmic energy',
      'Coronal mass ejections from the sun can disrupt terrestrial satellite networks',
      'Geothermal energy originates from radioactive decay deep within Earth mantle',
      'Bacteriophages are specialized viruses that infect and destroy pathogenic bacteria',
      'The Doppler effect shifts light frequencies toward blue or red spectra',
      'Carbon atoms form four covalent bonds allowing complex molecular chemistry',
      'Tidal forces from the moon gradually slow the rotation of Earth',
      'Cryogenic temperatures slow molecular motion to near absolute zero limits',
      'Cellular apoptosis is programmed cell death essential for tissue development',
      'Brownian motion provided early empirical evidence for the atomic hypothesis',
      'Bioluminescence allows deep ocean creatures to communicate hunt and camouflage',
      'Continental drift was originally proposed based on matching fossil coastlines',
      'Atmospheric pressure decreases exponentially with increasing altitude above sea level',
      'Antibiotic resistance evolves rapidly when bacterial populations encounter sublethal dosages',
      'Gravitational lensing magnifies faint distant galaxies behind massive foreground clusters',
      'The Coriolis effect deflects prevailing winds across spinning planetary atmospheres',
      'All living organisms share a universal genetic code of four nucleotides',
      'Superfluid helium climbs container walls defying classical fluid dynamics laws',
      'Telescopes acting as time machines reveal cosmic events billions years ago',
      'The human microbiome comprises trillions of symbiotic bacteria assisting digestion',
      'Nuclear fusion requires extreme temperatures and pressures found inside stellar cores',
      'Particle accelerators smash subatomic nuclei to discover novel fundamental particles',
      'The event horizon marks the boundary of no return around singularity',
      'Hemoglobin binds oxygen reversibly to transport vital fuel across tissues',
      'Paleoclimatologists extract ancient ice cores to reconstruct prehistoric atmospheric compositions',
      'Synthetic polymers revolutionized industrial materials through versatile chemical carbon backbones',
      'Crystallography uses X-ray diffraction patterns to map atomic protein structures',
      'Endosymbiosis explains how primitive eukaryotic cells engulfed ancestral energy producing bacteria',
      'The heliosphere shields our solar system from intense galactic cosmic rays',
      'Solar eclipses occur when the moon passes directly in front sun',
      'Dark matter does not interact with light yet exerts powerful gravity',
      'The strong nuclear force binds quarks together inside protons and neutrons',
      'Quantum tunneling allows particles to cross barriers higher than kinetic energy',
      'CRISPR technology enables precise editing of genetic sequences inside living organisms',
      'Hydrothermal vents support chemosynthetic ecosystems completely independent of solar energy',
      'The speed of light in vacuum is exactly constant for all',
      'Scientific inquiry relies on reproducible empirical evidence to falsify hypotheses systematically',
    ],
    hard: [
      'Every action has an equal and opposite reaction throughout the entire physical universe as formulated by classical mechanics',
      'The expansion of the cosmos accelerates due to the mysterious repulsive pressure exerted by pervasive dark energy',
      'General relativity demonstrates that massive celestial objects warp the fabric of spacetime creating the phenomenon we experience as gravity',
      'Mitochondria generate adenosine triphosphate through complex chemical chemiosmotic electron transport chains embedded across inner mitochondrial membranes',
      'Radioactive decay provides an extraordinarily reliable geological clock for determining the precise numerical age of ancient planetary rocks',
      'Look deep into nature and then you will understand everything about human purpose and physical reality much better',
      'The quantum wave function describes the probabilistic distribution of finding a subatomic particle in particular state upon measurement',
      'Photosynthesis in terrestrial plants and marine phytoplankton absorbs solar photons to split water molecules releasing gaseous oxygen into atmosphere',
      'The James Webb space telescope captures infrared light from early galaxies that formed merely hundreds of millions years after big bang',
      'Black holes represent regions of spacetime where gravitational collapse produces infinite density enclosed within an inescapable light trapping event horizon',
      'The double slit experiment demonstrates that fundamental particles exhibit both localized particle behavior and continuous wave interference depending on observation',
      'DNA replication proceeds with astonishing fidelity thanks to molecular proofreading enzymes that detect and excise mismatched nucleotide base pairs',
      'Plate tectonics drives continental drift through convection currents circulating slowly within the semi molten mantle beneath brittle lithospheric plates',
      'Massive stars end their lifecycles in catastrophic supernova explosions dispersing forged heavy elements like iron gold and uranium into cosmos',
      'Entropy serves as the arrow of time dictating that isolated thermodynamic systems evolve irreversibly toward states of maximum disorder',
      'The human immune system distinguishes self from non self antigens through sophisticated signaling between T cells B cells and antibodies',
      'Cosmic inflation posits that the infant universe underwent an exponential metric expansion within a tiny fraction of second following singularity',
      'Quantum entanglement demonstrates that measurements performed on one particle instantaneously correlate with another regardless of distance separating them across universe',
      'The magnetic field generated by geodynamo processes in the liquid outer core protects terrestrial biology from deadly solar plasma winds',
      'Synthetic biology engineers novel metabolic pathways inside bacterial chassis to manufacture sustainable fuels medicines and biodegradable polymers at industrial scale',
      'Neutron stars pack the mass of our entire sun into sphere roughly twenty kilometers across creating unfathomable matter densities',
      'The discovery of gravitational waves produced by colliding black holes confirmed one of the final untested predictions of Einstein relativity',
      'Cellular senescence prevents damaged cells from proliferating into malignant tumors yet contributes to tissue degradation and chronic inflammation during aging',
      'Spectroscopy allows astrophysicists to determine the precise chemical composition temperature density and velocity of distant stars through absorption lines',
      'The standard model of particle physics successfully unifies electromagnetic weak and strong nuclear forces through fundamental gauge bosons and fermions',
      'Bioluminescent chemical reactions convert chemical luciferin into cold emission light with nearly one hundred percent quantum efficiency inside deep creatures',
      'Thermal equilibrium occurs when two physical bodies in contact cease exchanging heat because their thermodynamic temperatures have equalized completely',
      'Exoplanet atmospheric characterization searches for chemical biosignatures like simultaneous presence of methane and oxygen indicating potential extraterrestrial biological activity',
      'Paleontological fossil records reveal that five catastrophic mass extinction events have drastically reshaped biodiversity across geological planetary history',
      'Understanding the fundamental laws of nature liberates human curiosity from superstition and illuminates our humble place among the stars',
    ],
  },
};

// ══════════════════════════════════════════════════════════════
// 6. CINEMA & MOVIES (cinema)
// ══════════════════════════════════════════════════════════════
const cinema = {
  cat: {
    slug: 'cinema',
    label: 'Cinema & Movies',
    icon: '🎬',
    description: 'Iconic movie lines, cinema culture, Hollywood lore, and director craft',
    display_order: 7,
  },
  data: {
    easy: [
      'Lights camera and action', 'May the force assist', 'Here is looking kid', 'Cut print that take',
      'Cinema captures human dreams', 'Popcorn at the movies', 'Roll the film reel', 'Direct the next scene',
      'The credits roll down', 'Audience cheers out loud', 'Watch the silver screen', 'Screenplay tells great story',
      'Actor memorizes his lines', 'Soundtrack sets the mood', 'Boom mic catches audio', 'Camera pans across room',
      'Zoom into actor eyes', 'Fade to black screen', 'Opening scene sets tone', 'Climax delivers emotional punch',
      'Plot twists shock viewers', 'Special effects look real', 'Costumes reflect historical era', 'Makeup transforms the actor',
      'Stunt double jumps car', 'Set designer paints walls', 'Film editing creates rhythm', 'Color grading adds atmosphere',
      'Box office record broken', 'Premiere on red carpet', 'Film festival wins award', 'Critics praise director vision',
      'Trailers build immense hype', 'Sequel hits theaters soon', 'Prequel reveals back story', 'Franchise spans four movies',
      'Animation brings toys alive', 'Documentary uncovers hidden truth', 'Thriller keeps audience guessing', 'Horror movie causes screams',
      'Romance warms viewers hearts', 'Comedy produces roaring laughter', 'Western features dusty deserts', 'Sci fi explores future',
      'Action stunts defy physics', 'Musical features singing dancers', 'Silent movies used cards', 'Black and white aesthetic',
      'Technicolor brought vivid hues', 'CGI creates fantastic beasts', 'Stop motion requires patience', 'Voice actors deliver emotion',
      'Film noir features shadows', 'Femme fatale plots revenge', 'Private detective tracks clues', 'Villain reveals evil plan',
      'Hero saves the city', 'Sidekick provides comic relief', 'Mentor passes on wisdom', 'Underdog wins final match',
      'Final farewell brings tears', 'Standing ovation fills theater', 'Director yells cut loud', 'Best picture nominee chosen',
      'Golden statuette awarded tonight', 'Red carpet flash bulbs', 'Interviewing stars on premiere', 'Midnight movie screening starts',
      'Tickets sold out completely', 'Front row movie seats', 'Surround sound rattles room', 'Projector beams light forward',
      'Cinematographer frames wide shot', 'Focal length alters perspective', 'Depth of field separates', 'Wide angle shows landscape',
      'Close up captures tears', 'Dutch angle creates tension', 'Dolly zoom disorients viewer', 'Tracking shot follows runner',
      'Long take builds suspense', 'Jump cuts show panic', 'Montage accelerates passing time', 'Voiceover narrates inner thoughts',
      'Score swells with strings', 'Foley artist records footsteps', 'Dialogue mixed crystal clear', 'Subtitles translate foreign lines',
      'Matinee show costs less', 'Drive in movie nights', 'Classic cinema never dies', 'Stories live on forever',
    ],
    normal: [
      'There is no place like home after a sudden storm',
      'I am going to make him an irresistible profitable offer',
      'Fasten your seatbelts it is going to be bumpy night',
      'Keep your friends close and your enemies even closer always',
      'You cannot handle the unvarnished truth about this courtroom',
      'Cinema allows audiences to experience a thousand lives in darkness',
      'A classic film reveals fresh emotional depths every single time',
      'Cinematography balances lighting shadows and composition to create visual wonder',
      'Great directors orchestrate actors sound and camera motion into vision',
      'I will be back promised the unstoppable cybernetic Austrian assassin',
      'Houston we have a problem echoed across ground control consoles',
      'Say hello to my little friend shouted the desperate gangster',
      'You talking to me asked the lonely midnight taxi driver',
      'Show me the money shouted the sports agent on phone',
      'Life was like a box of chocolates with unexpected flavors',
      'E T phone home whispered the gentle stranded cosmic alien',
      'My precious murmured the creature in dark underground cave chambers',
      'I see dead people confessed the terrified young hospital patient',
      'Here is Johnny screamed the crazed axe wielding hotel caretaker',
      'Bond James Bond introduced the suave British secret service agent',
      'Frankly my dear I do not give a damn anymore',
      'There is no crying in baseball yelled the frustrated coach',
      'To infinity and beyond shouted the plastic space ranger hero',
      'Why so serious asked the scarred anarchist with wicked smile',
      'You had me at hello she whispered with teary eyes',
      'Carpe diem seize the day boys make lives extraordinary',
      'I love the smell of napalm in the early morning',
      'Nobody puts Baby in a corner at the summer resort',
      'I feel the need the need for extreme supersonic speed',
      'Elementary my dear Watson observed the brilliant Victorian consulting detective',
      'Cinematographers use golden hour sunlight to bathe scenes in warm glow',
      'A compelling screenplay balances external stakes with profound internal emotional conflicts',
      'The musical leitmotif signals the terrifying presence of the predator',
      'Practical in camera stunt effects often age far better than CGI',
      'Independent cinema provides a vital counterweight to franchise blockbuster formulas',
      'Film editors control temporal pacing through rhythmic assembly of individual takes',
      'Method actors immerse themselves completely into psychological mindset of characters',
      'Production designers craft immersive architectural environments that reflect themes of story',
      'The MacGuffin drives plot forward while character development provides genuine soul',
      'Classic film noir utilized high contrast chiaroscuro lighting to depict corruption',
      'Foley artists crush celery to create sounds of breaking human bones',
      'The director commentary track reveals fascinating behind the scenes production secrets',
      'Nonlinear narrative storytelling challenges viewers to piece together timeline clues',
      'The cliffhanger ending leaves moviegoers eagerly anticipating the next franchise chapter',
      'Color palettes shift subtly across movie acts to mirror emotional arcs',
      'Costume designers research historical eras meticulously to ensure period film authenticity',
      'Surround sound soundscapes envelop the audience placing them directly within action',
      'A brilliant villain believes sincerely that they are the righteous hero',
      'The coming of age genre captures the bitter sweetness of youth',
      'Stop motion animation requires shooting twenty four individual photographs per second',
      'Cinematic montages compress months of grueling training into two minutes',
      'Subtitles allow international films to transcend linguistic and cultural barriers globally',
      'The auteur theory posits that director is primary creative author film',
      'Jump scares deliver immediate physiological adrenaline rushes to terrified horror fans',
      'Wide anamorphic lenses capture sprawling cinematic vistas with distinctive horizontal flares',
      'A memorable movie twist reframes previous events in startling new light',
      'Screenwriters follow three act dramatic structures pioneered by ancient theatrical traditions',
      'The overture introduces recurring musical themes before the opening titles appear',
      'A character flaw must be overcome before protagonist achieves final victory',
      'Silent cinema relied on expressive pantomime physical comedy and musical accompaniment',
      'Box office performance does not always reflect artistic merit or durability',
      'The climax forces the protagonist to make an agonizing moral choice',
      'Dolly zoom shots create unsettling sensations that background is rushing away',
      'Movie trailers must tantalize viewers without spoiling crucial narrative third acts',
      'Documentaries bear witness to real world injustices and extraordinary human resilience',
      'Film preservation archives restore nitrate reels before chemical degradation destroys them',
      'The mid credits teaser hints at broader cinematic universe crossovers ahead',
      'A masterclass in suspense delays gratification keeping audience on edge seats',
      'Great cinema mirrors the collective anxieties and subconscious hopes of era',
      'The magic of motion pictures transforms flickering light into unforgettable memories',
    ],
    hard: [
      'Frankly my dear I do not give a damn about yesterday troubles or lingering sentimental regrets of past',
      'To infinity and beyond became the eternal inspirational motto of dreamers and explorers across multiple human generations',
      'A classic film reveals fresh emotional depths and thematic subtleties every single time you choose to sit and rewatch',
      'Cinematography balances lighting shadows and camera composition to create unforgettable visual emotional experiences on the silver screen',
      'Great directors orchestrate actors lighting sound and camera choreography into a singular cohesive and transcendent artistic vision',
      'You cannot handle the truth because in world that has walls those walls need to be guarded by men with guns',
      'There is no place like home whispered Dorothy as she clicked her ruby slippers three times in Kansas farm bedroom',
      'I am going to make him an offer he cannot refuse whispered the soft spoken patriarch of New York crime family',
      'Fasten your seatbelts it is going to be a bumpy night warned the glamorous Broadway diva with mischievous smile',
      'The greatest trick the devil ever pulled was convincing the entire gullible world that he did not exist at all',
      'May the force be with you became an indelible cultural blessing shared by millions of film lovers across the world',
      'Cinema is a matter of what is in the frame and what is out of the frame observed master director Martin Scorsese',
      'A film is never really good unless the camera is an eye in the head of a poet declared Orson Welles',
      'We all go a little mad sometimes confessed the soft spoken motel manager before the screeching violins played in shower',
      'Every time a bell rings an angel gets his wings announced the little girl on snowy Christmas Eve in Bedford Falls',
      'Keep your friends close but your enemies closer remained the chilling strategic advice passed down through crime dynasties in cinema history',
      'I have always depended on the kindness of strangers sighed the tragic Southern belle as she was led away quietly',
      'The best movies do not provide easy answers rather they provoke profound moral and existential questions that linger for decades',
      'Cinematographers use natural lighting and shallow depth of field to draw audience empathy directly into the protagonist intimate world',
      'The transition from silent films to synchronized sound completely revolutionized acting styles screenwriting techniques and cinematic pacing worldwide',
      'Behind every breathtaking Hollywood stunt sequence lies months of rigorous physics calculations rehearsal and meticulous safety engineering on set',
      'A powerful film score does not simply accompany images it acts as an invisible emotional character guiding the viewer subconscious response',
      'Documentary filmmakers walk a delicate ethical tightrope between objective historical documentation and subjective dramatic artistic storytelling in their work',
      'Independent films often take daring narrative risks that risk averse corporate studio blockbusters are unwilling to finance or explore',
      'The iconic closing shot of Casablanca demonstrates how romantic sacrifice can elevate personal heartbreak into timeless heroic cinematic legend',
      'Practical animatronics and miniature sets often impart an organic tactile weight to fantasy cinema that computer generated pixels struggle to match',
      'Stanley Kubrick insisted on hundreds of takes to break through actors rehearsed habits and access raw unvarnished psychological honesty',
      'Film noir emerged from post war cynicism using brooding shadows and morally compromised detectives to reflect deep societal disillusionment',
      'The art of film editing lies in knowing not just where to cut but precisely which moments need prolonged silence to breathe',
      'Sitting in a crowded darkened theater sharing collective gasps tears and laughter remains one of our most sacred communal secular rituals',
    ],
  },
};

// Write Batch 1
[casual, quotes, programming, idioms, science, cinema].forEach(({ cat, data }) => {
  writeCategorySeedFile(cat, data);
});
