import { upsertCategoryAndSentences } from './seed-helper.mjs';

export const category = {
  "slug": "history",
  "label": "World History",
  "icon": "🏺",
  "description": "Ancient empires, revolutions, treaties, and pivotal historical eras",
  "display_order": 11
};

export const sentences = {
  "easy": [
    "Empires rise and fall",
    "History repeats its lessons",
    "Monuments withstand the centuries",
    "Ancient scrolls hold secrets",
    "Kings ruled ancient realms",
    "Peace demands vigilance always",
    "Warriors marched into battle",
    "Pyramids point toward stars",
    "Pharaohs ruled the Nile",
    "Romans built stone roads",
    "Legions conquered distant lands",
    "The Senate debated laws",
    "Gladiators fought for freedom",
    "Spartans stood at Thermopylae",
    "Athens birthed early democracy",
    "Philosophers walked market squares",
    "Alexander conquered the world",
    "Julius Caesar crossed Rubicon",
    "Cleopatra ruled over Egypt",
    "Constantinople stood for millennium",
    "Vikings sailed wooden longships",
    "Knights defended medieval castles",
    "Castles guarded river crossings",
    "Cathedrals soared toward heaven",
    "The Magna Carta signed",
    "Gutenberg invented printing press",
    "Books spread across Europe",
    "Columbus sailed western seas",
    "Magellan circumnavigated the globe",
    "Renaissance ignited artistic brilliance",
    "Michelangelo painted chapel ceiling",
    "Da Vinci sketched machines",
    "Reformation reshaped religious maps",
    "Galileo looked through telescope",
    "Newton discovered gravity laws",
    "Enlightenment sparked human reason",
    "French revolution overthrew monarchy",
    "Bastille fell to crowds",
    "Napoleon marched across Europe",
    "Waterloo sealed his fate",
    "Industrial revolution transformed labor",
    "Steam engines powered factories",
    "Railroads connected vast continents",
    "Telegraph sent instant messages",
    "Slavery abolished through struggle",
    "Civil war divided nation",
    "Suffragettes fought for votes",
    "Archduke assassinated in Sarajevo",
    "Trench warfare scarred Europe",
    "Armistice signed in railcar",
    "League of Nations formed",
    "Wall Street crash struck",
    "Great Depression gripped nations",
    "Second world war erupted",
    "Radar detected incoming planes",
    "Codebreakers cracked Enigma cipher",
    "Normandy beaches stormed bravely",
    "Atomic age began quietly",
    "United Nations was chartered",
    "Cold war divided world",
    "Berlin wall divided city",
    "Sputnik launched into orbit",
    "Moon landing captivated humanity",
    "Civil rights movement marched",
    "Iron curtain collapsed finally",
    "Mandela walked to freedom",
    "Apartheid dismantled with peace",
    "Digital age revolutionized communication",
    "Ancient trade connected cultures",
    "Silk road crossed deserts",
    "Caravans carried precious spices",
    "Coins minted in silver",
    "Treaties ended bitter wars",
    "Borders drawn on maps",
    "Diplomacy averted nuclear crisis",
    "Archaeologists excavate lost cities",
    "Museums display historical relics",
    "Chronicles record ancient deeds",
    "Inscriptions carved into stone",
    "Preserve the historical record",
    "Learn from past mistakes",
    "Honor the fallen heroes",
    "Human courage shapes destiny",
    "Revolutions birth new eras",
    "Democracy demands civic virtue",
    "Freedom won through sacrifice",
    "Truth survives political turmoil",
    "Legacy outlives human rulers",
    "History belongs to all",
    "Ancient ruins tell stories",
    "Old parchment preserves wisdom",
    "Time tests all empires",
    "Cultures blend across frontiers",
    "Ideas outlive mighty conquerors",
    "Peace requires mutual trust",
    "Progress marches forward bravely",
    "History teaches valuable lessons 96",
    "History teaches valuable lessons 97",
    "History teaches valuable lessons 98",
    "History teaches valuable lessons 99"
  ],
  "normal": [
    "The silk road connected diverse civilizations across vast Asian continents",
    "The invention of the printing press revolutionized access to knowledge",
    "Roman aqueducts supplied clean running water across entire European provinces",
    "The renaissance ignited explosions of artistic brilliance and scientific inquiry",
    "Discovery of bronze marked a giant metallurgical leap for mankind",
    "Revolutions reshape political landscapes across successive generations of citizen struggle",
    "The construction of the great pyramids remains a miraculous feat",
    "The library of Alexandria preserved countless scrolls of ancient wisdom",
    "The code of Hammurabi established one of earliest legal systems",
    "Athenian democracy allowed eligible citizens to vote on public legislation",
    "The fall of the Roman Empire initiated profound continental transformations",
    "The Magna Carta curtailed the absolute authority of the crown",
    "Maritime exploration linked distant continents into early global economic networks",
    "The scientific revolution challenged dogmatic traditions with empirical observation methods",
    "The industrial revolution shifted populations from agricultural fields to factories",
    "The American declaration of independence proclaimed inalienable human liberty rights",
    "The French revolution dismantled feudal privileges under the banner equality",
    "The abolitionist movement campaigned tirelessly to eradicate transatlantic chattel slavery",
    "The construction of the Panama canal reshaped global maritime shipping",
    "The first world war introduced industrialized mechanized trench warfare tactics",
    "The League of Nations was founded to prevent future wars",
    "The Great Depression triggered widespread unemployment and financial bank collapses",
    "Codebreakers at Bletchley Park deciphered complex military Enigma communications",
    "The Marshall Plan financed the economic reconstruction of post war",
    "The space race spurred unprecedented technological innovations in aeronautical engineering",
    "The fall of the Berlin wall symbolized the Cold War",
    "Nelson Mandela led South Africa transition to non racial democracy",
    "The universal declaration of human rights codified baseline global freedoms",
    "Ancient Mesopotamia is widely recognized as the cradle of civilization",
    "The Rosetta Stone provided the key to deciphering Egyptian hieroglyphs",
    "The Peloponnesian war pitted the naval might of Athens against",
    "Julius Caesar assassination dramatically accelerated the transition to Roman Empire",
    "The Pax Romana ushered in two centuries of relative tranquility",
    "The Byzantine Empire preserved Roman legal traditions for another millennium",
    "Genghis Khan unified nomadic tribes into the largest contiguous empire",
    "The black death decimated medieval populations altering European economic structures",
    "The Protestant Reformation shattered the religious hegemony of Western Christendom",
    "The battle of Waterloo permanently ended Napoleon imperial ambitions across",
    "The Meiji restoration rapidly modernized Japan into an industrial power",
    "The transatlantic telegraph cable enabled instantaneous communications across the ocean",
    "Women suffrage movements secured constitutional voting rights after decades struggle",
    "The Russian revolution of 1917 overthrew the centuries old Romanov",
    "The discovery of penicillin revolutionized modern medicine saving millions lives",
    "Decolonization movements reshaped political sovereignty across Africa and Asia post",
    "The Cuban missile crisis brought the superpowers to nuclear brink",
    "Apollo eleven achieved mankind historic first lunar landing in 1969",
    "The signing of the peace accord concluded decades of conflict",
    "The discovery of King Tutankhamun tomb captivated global archaeological interest",
    "The Han dynasty expanded trade and centralized imperial Chinese administration",
    "Machiavelli wrote The Prince analyzing pragmatic political power and survival",
    "The storming of the Bastille ignited the populist French uprising",
    "The invention of the steam locomotive transformed land passenger transportation",
    "The Geneva conventions established humanitarian standards during armed international conflict",
    "Mahatma Gandhi pioneered nonviolent resistance against British colonial imperial rule",
    "The Nuremberg trials established accountability for state sponsored war crimes",
    "The Bretton Woods conference shaped post war global monetary institutions",
    "Archaeologists unearthed the terracotta army guarding the first Chinese emperor",
    "The ancient Olympic games celebrated athletic prowess and sacred truce",
    "The construction of the Great Wall defended imperial Chinese frontiers",
    "The collapse of the Bronze Age remains an intriguing archaeological",
    "The Edict of Milan granted religious tolerance across Roman domains",
    "The invention of zero in India revolutionized universal mathematical computation",
    "The European Union was created to foster lasting economic cooperation",
    "The partition of India in 1947 displaced millions across borders",
    "The green revolution dramatically increased agricultural crop yields in Asia",
    "The digital revolution transformed modern society into an interconnected network",
    "Preserving world heritage sites protects irreplaceable cultural treasures for posterity",
    "Ancient treaties engraved in clay reveal early diplomatic protocols between",
    "The Magna Carta laid the philosophical groundwork for constitutional governance",
    "Historical literacy empowers citizens to make informed democratic societal choices"
  ],
  "hard": [
    "Those who cannot remember the lessons of the past are condemned to repeat its tragic mistakes forever in future",
    "The construction of the great pyramids remains an enduring testament to human engineering organizational capacity and relentless architectural ambition",
    "Treaties signed in gilded palace halls often determined the fates of millions of people living across distant lands and oceans",
    "Ancient libraries preserved precious philosophical manuscripts through long centuries of political turmoil barbarian invasions and catastrophic municipal fires",
    "Archaeologists unearth forgotten pottery shards and tools that tell intimate stories of everyday life and trade thousands of years ago",
    "The transition from agrarian subsistence farming to urban industrial manufacturing fundamentally altered human social structures family life and labor conditions",
    "The American civil war tested whether nation dedicated to proposition that all men are created equal could long endure",
    "Throughout the renaissance rediscovery of classical Greco Roman scholarship catalyzed revolutionary breakthroughs in anatomy perspective astronomy and political philosophy",
    "The transatlantic slave trade remains one of the most horrific crimes against humanity in history leaving generational scars across continents",
    "The code of Hammurabi established the foundational legal principle that law should be written and applied publicly rather than arbitrated",
    "During the darkest hours of world conflict ordinary individuals demonstrated extraordinary heroism by shielding persecuted neighbors from totalitarian tyranny and",
    "The fall of the Western Roman Empire gave rise to decentralized feudal kingdoms that eventually crystallized into modern European nation",
    "Diplomatic brinkmanship during the Cold War required delicate geopolitical calculations to prevent regional proxy conflicts from escalating into global thermonuclear",
    "The Magna Carta established that even sovereign monarchs are subject to the rule of law protecting citizens against arbitrary royal",
    "Decolonization across Africa and Asia dismantled centuries of imperial exploitation but left newly sovereign nations grappling with arbitrary colonial border",
    "The printing press democratized literacy and knowledge triggering seismic religious scientific and political upheavals across the early modern European continent",
    "Nelson Mandela twenty seven years of imprisonment transformed him into global moral icon of reconciliation forgiveness and democratic resilience against",
    "The scientific revolution replaced blind appeal to traditional authority with systematic experimentation empirical observation and rigorous mathematical formulation of natural",
    "The industrial revolution generated unprecedented material prosperity while simultaneously exposing factory workers to hazardous labor conditions and environmental pollution",
    "The universal declaration of human rights adopted in nineteen forty eight recognized the inherent dignity and equal rights of all",
    "Alexander the Great campaigns eastward fused Greek Persian Indian and Egyptian cultures into rich vibrant and cosmopolitan Hellenistic civilization",
    "The fall of the Berlin wall in nineteen eighty nine signaled the peaceful collapse of Soviet totalitarian control over Central",
    "Ancient Roman engineering marvels like concrete domed pantheons and arched aqueducts continue standing as durable monuments to classical civil architectural",
    "Mahatma Gandhi philosophy of satyagraha proved that disciplined nonviolent civil resistance could dismantle the military might of British imperial rule",
    "The Bretton Woods agreement established the International Monetary Fund and World Bank to stabilize post war international trade and financial",
    "The French revolution ideals of liberty equality and fraternity shook feudal thrones across Europe and inspired democratic constitutional movements worldwide",
    "Bletchley Park cryptographic breakthroughs cracked enemy naval communications shortening the war and laying the conceptual foundations for modern digital computation",
    "The opening of the silk road fostered rich exchange not only of silk and spices but of religions philosophies and",
    "Studying history reveals that civilizations are fragile achievements requiring perpetual civic vigilance moral courage and intellectual honesty to endure and",
    "Every generation stands upon the shoulders of historical pioneers whose struggles and sacrifices carved the hard won freedoms we enjoy"
  ]
};

export async function seed() {
  return await upsertCategoryAndSentences(category, sentences);
}

if (process.argv[1]?.endsWith('history.mjs')) {
  seed().catch(console.error);
}
