import { upsertCategoryAndSentences } from './seed-helper.mjs';

export const category = {
  "slug": "idioms",
  "label": "Compound Idioms",
  "icon": "🧩",
  "description": "Colorful English idioms, figures of speech, and proverbial wisdom",
  "display_order": 5
};

export const sentences = {
  "easy": [
    "Bite the bullet now",
    "Break a leg tonight",
    "Cost an arm leg",
    "Piece of sweet cake",
    "Hit the sack early",
    "Under the chilly weather",
    "Spill the secret beans",
    "See eye to eye",
    "Cut corners on work",
    "Once in blue moon",
    "Burn the midnight oil",
    "Cold feet at last",
    "Speak of the devil",
    "Best of both worlds",
    "Blessing in clever disguise",
    "Call it a day",
    "Barking up wrong tree",
    "Cry over spilled milk",
    "Every cloud silver lining",
    "Hit nail on head",
    "Keep chin up high",
    "Kill two birds stones",
    "Let sleeping dogs lie",
    "Miss the moving boat",
    "No pain no gain",
    "On the same page",
    "Penny for your thoughts",
    "Pull someone quick leg",
    "Shape up or ship",
    "Spill your true feelings",
    "Take with grain salt",
    "Taste of own medicine",
    "Through thick and thin",
    "Time flies so fast",
    "Up in the air",
    "Weather the fierce storm",
    "Wild goose chase adventure",
    "Wrapped around little finger",
    "Your guess is mine",
    "Back to drawing board",
    "Ball is your court",
    "Beat around the bush",
    "Bite off more chew",
    "Burn bridges behind you",
    "Catch red handed today",
    "Curiosity killed the cat",
    "Devil in the details",
    "Down to the wire",
    "Draw the line clearly",
    "Drive someone up wall",
    "Drop of a hat",
    "Easier said than done",
    "Face the loud music",
    "Fish out of water",
    "Fit as a fiddle",
    "Flash in the pan",
    "Get out of hand",
    "Give benefit of doubt",
    "Go down in flames",
    "Go extra long mile",
    "Head in the clouds",
    "Hold your horses now",
    "In hot boiling water",
    "Jump on the bandwagon",
    "Keep at arm length",
    "Leave no stone unturned",
    "Let cat out bag",
    "Make ends meet today",
    "Off the beaten path",
    "On thin slippery ice",
    "Out of the woods",
    "Play devil own advocate",
    "Pull yourself together now",
    "Raining cats and dogs",
    "Ring a distant bell",
    "Roll with the punches",
    "Rule of thumb rule",
    "Save for rainy day",
    "Shoot from the hip",
    "Sight for sore eyes",
    "Skeleton in the closet",
    "Skin of your teeth",
    "Sleep like a log",
    "Smell something very fishy",
    "Snowed under with work",
    "Spick and clean span",
    "Steal someone shining thunder",
    "Straight from horse mouth",
    "Straw that broke back",
    "Take bull by horns",
    "The elephant in room",
    "The tip of iceberg",
    "Throw in the towel",
    "Turn over new leaf",
    "Under your very nose",
    "Up to your ears",
    "Water under the bridge",
    "Wear heart on sleeve",
    "Wolf in sheep clothing",
    "Word of mouth news"
  ],
  "normal": [
    "A bird in the hand is worth two in bush",
    "A picture is worth a thousand words in storytelling",
    "Actions speak much louder than spoken words ever could",
    "All good things must come to an end eventually",
    "An apple a day keeps the doctor away safely",
    "Better late than never when doing the right thing",
    "Birds of a feather flock together in shared interest",
    "Do not put all your eggs in one fragile basket",
    "Do not count your chickens before they actually hatch",
    "Early bird catches the worm in morning quiet hours",
    "Every cloud has a silver lining if you look",
    "Fortune favors the bold and the brave in life",
    "Good things come to those who wait with patience",
    "Haste makes waste when rushing through critical important tasks",
    "If you cannot beat them join them in mutual effort",
    "It takes two to tango during delicate negotiations always",
    "Laughter is the best medicine for a heavy heart",
    "Look before you leap into unfamiliar risky new territory",
    "Make hay while the warm sun shines bright outside",
    "Necessity is the true mother of all human invention",
    "No use crying over spilled milk on kitchen floor",
    "Practice makes perfect through consistent daily discipline and dedication",
    "Rome was not built in a single day or night",
    "The grass is always greener on the other side",
    "The pen is mightier than the sword in history",
    "There is no place like home after long travel",
    "Too many cooks spoil the broth in busy kitchen",
    "Two heads are always better than one single head",
    "When in Rome do as the Romans do naturally",
    "You cannot judge a book by its glossy cover",
    "He decided to bite the bullet and make the apology",
    "She felt completely under the weather after catching the flu",
    "They were burning the midnight oil to finish the report",
    "We see eye to eye on almost every major decision",
    "Finding that parking spot was a blessing in clever disguise",
    "Let us call it a day and resume tomorrow morning",
    "The unexpected promotion came completely out of the clear blue",
    "He hit the nail on the head with that observation",
    "You should take his wild claims with a grain salt",
    "She was caught between a rock and a hard place",
    "They always go the extra mile to assist their customers",
    "He let the cat out of the bag about party",
    "Learning to drive a manual car was a piece cake",
    "She decided to take the bull by the horns directly",
    "That expensive antique watch cost him an arm and leg",
    "We are all in the same boat during difficult times",
    "He was walking on eggshells around his irritable new boss",
    "She has a heart of pure gold toward everyone around",
    "They had to face the music after losing the project",
    "It was the straw that broke the camel sturdy back",
    "He wears his heart on his sleeve for all see",
    "She is always barking up the wrong tree with accusations",
    "They decided to bury the hatchet and become close friends",
    "The team was firing on all cylinders during championship game",
    "He jumped out of the frying pan into the fire",
    "She has been snowed under with work all week long",
    "We need to get our ducks in a neat row",
    "That performance was just a flash in the pan moment",
    "He likes to play devil advocate during team brainstorm meetings",
    "She pulled strings behind the scenes to secure the interview",
    "They decided to turn over a brand new fresh leaf",
    "The company had to tighten its belt during economic downturn",
    "He was skating on very thin ice with his manager",
    "She gave him the benefit of doubt regarding the delay",
    "They managed to pull off the deal by skin teeth",
    "It is always water under the bridge after sincere apologies",
    "He spilled the beans about the secret surprise birthday dinner",
    "She was over the moon when she passed her exam",
    "They finally saw the light at the end of tunnel",
    "He threw in the towel after three grueling championship rounds"
  ],
  "hard": [
    "He who hesitates is lost but he who leaps blindly without looking often lands in thorny ditch",
    "A rolling stone gathers no moss while stationary boulder slowly accumulates rich green tapestry of ancient wisdom",
    "You can lead a stubborn horse to clear mountain water but you cannot make him drink from stream",
    "When the going gets tough the tough get going and refuse to surrender to difficult outside circumstances",
    "Do not cross the rickety wooden bridge until you actually arrive at the edge of the rushing river",
    "The squeaky wheel gets the grease but the silent wheel quietly carries the heaviest cargo across long journeys",
    "It is always darkest just before the glorious dawn breaks through the misty mountain horizon in early morning",
    "Give a man a fish and you feed him for a day teach him to fish feeds lifetime",
    "A journey of a thousand miles must begin with a single determined step in the right direction today",
    "People who live in fragile glass houses should never throw heavy stone rocks at their quiet neighbors",
    "The road to hell is frequently paved with good intentions that were never translated into concrete thoughtful actions",
    "There is no honor among thieves until the gold is divided equally under the flickering light of lantern",
    "A chain is only as strong as its weakest link when enduring the relentless pull of heavy stress",
    "Too many cooks spoil the delicate broth because each insists on adding their own secret pinch of spice",
    "An ounce of sensible prevention is worth a full pound of painful cure after the damage has occurred",
    "Hope for the best prepare for the worst and take whatever comes with grace and unshakeable inner resilience",
    "Strike while the iron is glowing hot because cold metal resists even the heaviest hammer blows of blacksmith",
    "You cannot have your sweet cake and eat it too without eventually facing the empty plate before you",
    "Birds of a feather flock together in great numbers while the solitary eagle soars high above mountain peaks",
    "When one door closes another opens but we often gaze so longingly at the locked wooden portal",
    "Do not throw the healthy baby out with the dirty bathwater when attempting to clean up messy situation",
    "A rising tide lifts all boats in the tranquil harbor while sudden storm tests the seaworthiness of all",
    "The devil is in the granular details while salvation often lies in stepping back to see whole picture",
    "Fools rush in where wise angels fear to tread lightly across the treacherous ground of untested claims",
    "What doesn’t kill you makes you stronger provided you possess the emotional fortitude to learn from the wound",
    "A fool and his money are soon parted especially when flattered by cunning strangers offering effortless riches",
    "Cleanliness is next to godliness but genuine kindness and compassion outrank spotless floors every single hour of day",
    "He who laughs last laughs best because time has a curious way of vindicating the patient underdog",
    "Absence makes the fond heart grow fonder while constant familiarity can sometimes breed unnecessary contempt among close companions",
    "Every dark cloud possesses a shimmering silver lining if only travelers maintain the optimism to look upward steadily"
  ]
};

export async function seed() {
  return await upsertCategoryAndSentences(category, sentences);
}

if (process.argv[1]?.endsWith('idioms.mjs')) {
  seed().catch(console.error);
}
