import { upsertCategoryAndSentences } from './seed-helper.mjs';

export const category = {
  "slug": "literature",
  "label": "Classic Literature",
  "icon": "📚",
  "description": "Timeless opening lines, iconic passages, and prose from masterworks",
  "display_order": 9
};

export const sentences = {
  "easy": [
    "Call me Ishmael today",
    "Winter came to stay",
    "Words hold great magic",
    "Books unlock ancient minds",
    "The great story begins",
    "Read between the lines",
    "Stories endure forevermore",
    "Turn the printed page",
    "Ink flows upon parchment",
    "Characters come to life",
    "Plots twist and turn",
    "A hero starts journey",
    "The quest begins now",
    "Shadows fall across valley",
    "Once upon a time",
    "Far beyond the horizon",
    "The clock struck thirteen",
    "Lantern flickered in darkness",
    "Footsteps echoed down hall",
    "A mysterious letter arrived",
    "The secret was revealed",
    "Destiny called his name",
    "Love conquered ancient sorrow",
    "The journey home ended",
    "Whispers in the library",
    "Volumes bound in leather",
    "Poetry stirs the soul",
    "Prose paints vivid pictures",
    "Legends whispered in taverns",
    "Tales told by firelight",
    "Echoes of forgotten lore",
    "The ship set sail",
    "Adventures await the brave",
    "Courage tested by adversity",
    "Fate sealed with kiss",
    "Tears shed in silence",
    "Joy returned to kingdom",
    "A classic tale told",
    "Memories written in stone",
    "Dreams woven in words",
    "Midnight strikes the bell",
    "Pages yellow with age",
    "Read beneath the lamp",
    "Find truth in fiction",
    "Old stories teach lessons",
    "The narrator begins speaking",
    "Villains meet their fate",
    "Heroes find redemption now",
    "A quiet autumn evening",
    "Wind howling through pines",
    "Castle stood upon cliff",
    "Candle burns down low",
    "The library smelled wonderful",
    "Bookmark marks the spot",
    "End of first chapter",
    "Mystery deepens with time",
    "Tragedy strikes the innocent",
    "Comedy delights the court",
    "Romance blossoms in spring",
    "Epic battles shake earth",
    "Honor guiding the knight",
    "Swords clash in battle",
    "Banners fly in wind",
    "Crown sits upon brow",
    "The kingdom found peace",
    "A wanderer entered town",
    "Strange footsteps outside door",
    "Dusty manuscripts in cellar",
    "The author finished masterpiece",
    "Words outlive the author",
    "Stories span all generations",
    "Imagination knows no limits",
    "Every book holds worlds",
    "Open your reading eyes",
    "Travel through time pages",
    "Discover forgotten old realms",
    "Villages nestled in valleys",
    "Dragons slept under mountain",
    "Brave hobbits walked forward",
    "A ring of power",
    "The great gates opened",
    "Stars watched over traveler",
    "Morning brought sweet hope",
    "The tempest raged wildly",
    "Ghosts haunted the moor",
    "A detective solved case",
    "The raven tapped window",
    "Nevermore spoke the bird",
    "Fables carry moral truth",
    "Myths explain the cosmos",
    "Laughter fills the tavern",
    "Farewell to dear friend",
    "The story ends here",
    "Close the final book",
    "Remember the spoken words",
    "Wisdom lives in pages",
    "Treasures found in libraries",
    "Read to understand life",
    "Stories connect human hearts",
    "Literature enriches the spirit"
  ],
  "normal": [
    "It was the best of times it was the worst",
    "All happy families resemble one another each unhappy family is",
    "Not all those who wander are truly lost in the",
    "Whatever our souls are made of his and mine are",
    "In a hole in the ground there lived a peaceful",
    "There is some good in this world worth fighting for",
    "It was a bright cold day in April and clocks",
    "Someone must have slandered Josef K for one morning he",
    "As Gregor Samsa awoke one morning from uneasy dreams he",
    "Happy families are all alike every unhappy family is unhappy",
    "Whether I shall turn out to be the hero of",
    "The sun shone having no alternative on the nothing new",
    "He was an old man who fished alone in a",
    "You will rejoice to hear that no disaster has accompanied",
    "Mother died today or maybe yesterday I cannot be entirely",
    "It is a truth universally acknowledged that a single man",
    "So we beat on boats against the current borne back",
    "The only way out of the labyrinth of suffering is",
    "Beware for I am fearless and therefore extraordinarily powerful in",
    "There are more things in heaven and earth than are",
    "Brevity is the soul of wit and tediousness the limbs",
    "To be or not to be that is the eternal",
    "We are such stuff as dreams are made on in",
    "All the world is a stage and all men merely",
    "Some are born great some achieve greatness and some have",
    "The fault dear Brutus is not in our stars but",
    "A horse a horse my entire kingdom for a swift",
    "Parting is such sweet sorrow that I shall say good",
    "Lord what fools these mortal human beings be in the",
    "If music be the food of love play on give",
    "Hell is empty and all the devils are wandering right",
    "There is nothing either good or bad but thinking makes",
    "Though she be but little she is fierce in her",
    "The course of true love never did run smooth across",
    "Listen to many speak to a few and keep your",
    "Love looks not with the eyes but with the mind",
    "What is done cannot be undone whispered the guilt ridden",
    "By the pricking of my thumbs something wicked this way",
    "One may smile and smile and still be an absolute",
    "Things without all remedy should be without regard what is",
    "Words without thoughts never to heaven go uttered the praying",
    "Cowards die many times before their deaths the valiant never",
    "Men at some time are masters of their own shifting",
    "Suspicion always haunts the guilty mind the thief doth fear",
    "Give every man thy ear but few thy voice in",
    "When sorrows come they come not single spies but in",
    "Conscience doth make cowards of us all as we hesitate",
    "Rich gifts wax poor when givers prove unkind in their",
    "My words fly up my thoughts remain below words without",
    "A little more than kin and less than kind muttered",
    "Get thee to a nunnery why wouldst thou be a",
    "Something is rotten in the state of Denmark observed the",
    "The lady doth protest too much methinks during the dramatic",
    "To thine own self be true and it must follow",
    "Neither a borrower nor a lender be for loan oft",
    "This above all to thine own self be true through",
    "Stay gold Ponyboy stay gold whispered the dying brave young",
    "It matters not what someone is born but what they",
    "It is our choices that show what we truly are",
    "Words are in my not so humble opinion our inexhaustible",
    "Do not pity the dead Harry pity the living above",
    "Of course it is happening inside your head why should",
    "Until I feared I would lose it I never loved",
    "Real courage is when you know you are licked before",
    "You never really understand a person until you consider things",
    "The scar had not pained Harry for nineteen years all",
    "I cannot carry the ring for you but I can",
    "Even the smallest person can change the course of the",
    "Courage is found in unlikely places where hope seems utterly",
    "The world is indeed full of peril and in it"
  ],
  "hard": [
    "It is a truth universally acknowledged that a single man in possession of a good fortune must be in want",
    "So we beat on boats against the current borne back ceaselessly into the romantic and elusive corridors of the past",
    "The only way out of the labyrinth of human suffering is to choose forgiveness and compassion over resentment and cold",
    "All that is gold does not glitter and not all those who wander aimlessly across mountain paths are truly lost",
    "Beware for I am fearless and therefore extraordinarily powerful when confronting those who sought to destroy my gentle creators and",
    "In a hole in the ground there lived a hobbit not a nasty dirty wet hole but cozy hobbit hole",
    "It was the best of times it was the worst of times it was the age of wisdom and foolishness",
    "All happy families resemble one another each unhappy family is unhappy in its own unique and heart wrenching individual manner",
    "Someone must have been telling lies about Josef K for without having done anything wrong he was arrested one fine",
    "As Gregor Samsa awoke one morning from uneasy dreams he found himself transformed in his bed into a gigantic insect",
    "It was a bright cold day in April and the clocks on the city towers were striking thirteen ominous heavy",
    "Whether I shall turn out to be the hero of my own life or whether that station will be held",
    "The sun shone having no alternative on the nothing new as it illuminated the barren and timeless streets of the",
    "He was an old man who fished alone in a skiff in the Gulf Stream and had gone eighty four",
    "You will rejoice to hear that no disaster has accompanied the commencement of an enterprise which you have regarded with",
    "Mother died today or maybe yesterday I cannot be sure as the telegram from the retirement home arrived without specific",
    "If you really want to hear about it the first thing you will probably want to know is where I",
    "There is no greater agony than bearing an untold story inside you as you wander through the silent landscapes of",
    "Whatever our souls are made of his and mine are identical while the rest of the world remains distant and",
    "There are more things in heaven and earth Horatio than are dreamt of in your narrow and rigid philosophical systems",
    "We are such stuff as dreams are made on and our little earthly life is rounded with a deep and",
    "Some are born great some achieve greatness and some have greatness thrust upon them unexpectedly by the winds of shifting",
    "The fault dear Brutus is not in our stars but in ourselves that we are underlings submitting meekly to mortal",
    "A coward dies a thousand deaths before his time while the valiant man never tastes of death but once in",
    "Tomorrow and tomorrow and tomorrow creeps in this petty pace from day to day to the last syllable of recorded",
    "Out out brief candle life is but a walking shadow a poor player that struts and frets his hour upon",
    "It is a tale told by an idiot full of sound and fury signifying nothing at the conclusion of mortal",
    "All the world is a stage and all the men and women merely players who enter perform and exit quietly",
    "I wandered lonely as a cloud that floats on high o’er vales and hills when all at once I saw",
    "To see a world in a grain of sand and a heaven in a wild flower hold infinity in the"
  ]
};

export async function seed() {
  return await upsertCategoryAndSentences(category, sentences);
}

if (process.argv[1]?.endsWith('literature.mjs')) {
  seed().catch(console.error);
}
