import { upsertCategoryAndSentences } from './seed-helper.mjs';

export const category = {
  "slug": "music",
  "label": "Music & Sound",
  "icon": "🎵",
  "description": "Rhythms, harmonies, orchestral symphonies, and studio craft",
  "display_order": 15
};

export const sentences = {
  "easy": [
    "Music speaks to soul",
    "Rhythm drives the beat",
    "Strum acoustic guitar strings",
    "Sing notes in harmony",
    "Bass lines groove deeply",
    "Practice scales every day",
    "Play grand piano keys",
    "Drummers keep steady tempo",
    "Trumpet hits high notes",
    "Violin bows glide softly",
    "Cello resonates warm tones",
    "Flute melodies soar high",
    "Saxophone wails smooth jazz",
    "Synthesizer shapes electric waves",
    "Turn amplifier volume up",
    "Tune strings before concert",
    "Harmonize vocals with chorus",
    "Microphone records clean vocals",
    "Headphones isolate stereo sound",
    "Composer writes new symphony",
    "harmonize the melodic melody",
    "melodic melody harmonize choral harmony",
    "melody brings melodic choral harmony",
    "Always harmonize melodic melody",
    "Every melody can harmonize",
    "improvise the acoustic harmony",
    "acoustic harmony improvise jazz groove",
    "harmony brings acoustic jazz groove",
    "Always improvise acoustic harmony",
    "Every harmony can improvise",
    "compose the rhythmic tempo",
    "rhythmic tempo compose orchestral suite",
    "tempo brings rhythmic orchestral suite",
    "Always compose rhythmic tempo",
    "Every tempo can compose",
    "strum the sonorous chord",
    "sonorous chord strum studio session",
    "chord brings sonorous studio session",
    "Always strum sonorous chord",
    "Every chord can strum",
    "resonate the lyrical rhythm",
    "lyrical rhythm resonate musical poetry",
    "rhythm brings lyrical musical poetry",
    "Always resonate lyrical rhythm",
    "Every rhythm can resonate",
    "modulate the harmonic timbre",
    "harmonic timbre modulate sonic tapestry",
    "timbre brings harmonic sonic tapestry",
    "Always modulate harmonic timbre",
    "Every timbre can modulate",
    "orchestrate the expressive scale",
    "expressive scale orchestrate choral harmony",
    "scale brings expressive choral harmony",
    "Always orchestrate expressive scale",
    "Every scale can orchestrate",
    "record the dynamic symphony",
    "dynamic symphony record jazz groove",
    "symphony brings dynamic jazz groove",
    "Always record dynamic symphony",
    "Every symphony can record",
    "perform the soothing acoustic",
    "soothing acoustic perform orchestral suite",
    "acoustic brings soothing orchestral suite",
    "Always perform soothing acoustic",
    "Every acoustic can perform",
    "master the virtuosic chorus",
    "virtuosic chorus master studio session",
    "chorus brings virtuosic studio session",
    "Always master virtuosic chorus",
    "Every chorus can master",
    "melodic melody harmonize musical poetry",
    "melody brings melodic musical poetry",
    "acoustic harmony improvise sonic tapestry",
    "harmony brings acoustic sonic tapestry",
    "rhythmic tempo compose choral harmony",
    "tempo brings rhythmic choral harmony",
    "sonorous chord strum jazz groove",
    "chord brings sonorous jazz groove",
    "lyrical rhythm resonate orchestral suite",
    "rhythm brings lyrical orchestral suite",
    "harmonic timbre modulate studio session",
    "timbre brings harmonic studio session",
    "expressive scale orchestrate musical poetry",
    "scale brings expressive musical poetry",
    "dynamic symphony record sonic tapestry",
    "symphony brings dynamic sonic tapestry",
    "soothing acoustic perform choral harmony",
    "acoustic brings soothing choral harmony",
    "virtuosic chorus master jazz groove",
    "chorus brings virtuosic jazz groove",
    "melodic melody harmonize orchestral suite",
    "melody brings melodic orchestral suite",
    "acoustic harmony improvise studio session",
    "harmony brings acoustic studio session",
    "rhythmic tempo compose musical poetry",
    "tempo brings rhythmic musical poetry",
    "sonorous chord strum sonic tapestry",
    "chord brings sonorous sonic tapestry",
    "lyrical rhythm resonate choral harmony",
    "rhythm brings lyrical choral harmony"
  ],
  "normal": [
    "A minor chord evokes profound sorrow and emotional nostalgic yearning",
    "Jazz improvisation celebrates spontaneous creative expression over rigid written structure",
    "Syncopation accents unexpected beats to create infectious dancing grooves",
    "The orchestra tuned instruments before the majestic symphony finally began",
    "Analog synthesizers produce rich organic electrical warmth across stereo monitors",
    "Music can name the unnameable and communicate the unknowable soul",
    "Reverberation creates a sense of vast cathedral physical acoustic space",
    "A catchy musical hook lingers in listeners memory for decades",
    "Dynamic contrast between pianissimo and fortissimo creates thrilling dramatic tension",
    "Singing in four part harmony requires active empathetic collective listening",
    "The melodic melody will greatly harmonize our choral harmony today",
    "Every melodic melody must harmonize carefully across the entire choral",
    "Learning how to harmonize melodic melody inspires deep choral harmony",
    "Our dedicated team will harmonize the melodic melody for choral",
    "The acoustic harmony will greatly improvise our jazz groove today",
    "Every acoustic harmony must improvise carefully across the entire jazz",
    "Learning how to improvise acoustic harmony inspires deep jazz groove",
    "Our dedicated team will improvise the acoustic harmony for jazz",
    "The rhythmic tempo will greatly compose our orchestral suite today",
    "Every rhythmic tempo must compose carefully across the entire orchestral",
    "Learning how to compose rhythmic tempo inspires deep orchestral suite",
    "Our dedicated team will compose the rhythmic tempo for orchestral",
    "The sonorous chord will greatly strum our studio session today",
    "Every sonorous chord must strum carefully across the entire studio",
    "Learning how to strum sonorous chord inspires deep studio session",
    "Our dedicated team will strum the sonorous chord for studio",
    "The lyrical rhythm will greatly resonate our musical poetry today",
    "Every lyrical rhythm must resonate carefully across the entire musical",
    "Learning how to resonate lyrical rhythm inspires deep musical poetry",
    "Our dedicated team will resonate the lyrical rhythm for musical",
    "The harmonic timbre will greatly modulate our sonic tapestry today",
    "Every harmonic timbre must modulate carefully across the entire sonic",
    "Learning how to modulate harmonic timbre inspires deep sonic tapestry",
    "Our dedicated team will modulate the harmonic timbre for sonic",
    "The expressive scale will greatly orchestrate our choral harmony today",
    "Every expressive scale must orchestrate carefully across the entire choral",
    "Learning how to orchestrate expressive scale inspires deep choral harmony",
    "Our dedicated team will orchestrate the expressive scale for choral",
    "The dynamic symphony will greatly record our jazz groove today",
    "Every dynamic symphony must record carefully across the entire jazz",
    "Learning how to record dynamic symphony inspires deep jazz groove",
    "Our dedicated team will record the dynamic symphony for jazz",
    "The soothing acoustic will greatly perform our orchestral suite today",
    "Every soothing acoustic must perform carefully across the entire orchestral",
    "Learning how to perform soothing acoustic inspires deep orchestral suite",
    "Our dedicated team will perform the soothing acoustic for orchestral",
    "The virtuosic chorus will greatly master our studio session today",
    "Every virtuosic chorus must master carefully across the entire studio",
    "Learning how to master virtuosic chorus inspires deep studio session",
    "Our dedicated team will master the virtuosic chorus for studio",
    "The melodic melody will greatly harmonize our musical poetry today",
    "Every melodic melody must harmonize carefully across the entire musical",
    "Learning how to harmonize melodic melody inspires deep musical poetry",
    "Our dedicated team will harmonize the melodic melody for musical",
    "The acoustic harmony will greatly improvise our sonic tapestry today",
    "Every acoustic harmony must improvise carefully across the entire sonic",
    "Learning how to improvise acoustic harmony inspires deep sonic tapestry",
    "Our dedicated team will improvise the acoustic harmony for sonic",
    "The rhythmic tempo will greatly compose our choral harmony today",
    "Every rhythmic tempo must compose carefully across the entire choral",
    "Learning how to compose rhythmic tempo inspires deep choral harmony",
    "Our dedicated team will compose the rhythmic tempo for choral",
    "The sonorous chord will greatly strum our jazz groove today",
    "Every sonorous chord must strum carefully across the entire jazz",
    "Learning how to strum sonorous chord inspires deep jazz groove",
    "Our dedicated team will strum the sonorous chord for jazz",
    "The lyrical rhythm will greatly resonate our orchestral suite today",
    "Every lyrical rhythm must resonate carefully across the entire orchestral",
    "Learning how to resonate lyrical rhythm inspires deep orchestral suite",
    "Our dedicated team will resonate the lyrical rhythm for orchestral"
  ],
  "hard": [
    "Without music life would be an unbearable mistake wrote the philosopher about artistic expression and emotional transcendence",
    "The conductor raised the slender wooden baton and complete breathless silence blanketed the packed three tier concert hall",
    "Polyrhythms layer conflicting time signatures to produce complex hypnotic grooves that captivate audiences and dancers across the globe",
    "Acoustic resonance in wooden string instruments matures gracefully as master violins and cellos age across multiple human centuries",
    "Writing lyrics allows musicians to translate unspoken personal heartbreaks into universal melodies that comfort millions of lonely souls",
    "When confronting complex challenges in choral harmony one must harmonize every melodic melody with rigorous discipline and patient determination",
    "The integration of melodic melody within modern choral harmony enables practitioners to harmonize critical milestones without sacrificing enduring quality",
    "Throughout the evolution of choral harmony master practitioners learned to harmonize the most intricate melodic melody through persistent dedicated effort",
    "Developing comprehensive understanding of choral harmony demands that professionals harmonize each melodic melody with profound analytical rigor and integrity",
    "When confronting complex challenges in jazz groove one must improvise every acoustic harmony with rigorous discipline and patient determination",
    "The integration of acoustic harmony within modern jazz groove enables practitioners to improvise critical milestones without sacrificing enduring quality",
    "Throughout the evolution of jazz groove master practitioners learned to improvise the most intricate acoustic harmony through persistent dedicated effort",
    "Developing comprehensive understanding of jazz groove demands that professionals improvise each acoustic harmony with profound analytical rigor and integrity",
    "When confronting complex challenges in orchestral suite one must compose every rhythmic tempo with rigorous discipline and patient determination",
    "The integration of rhythmic tempo within modern orchestral suite enables practitioners to compose critical milestones without sacrificing enduring quality",
    "Throughout the evolution of orchestral suite master practitioners learned to compose the most intricate rhythmic tempo through persistent dedicated effort",
    "Developing comprehensive understanding of orchestral suite demands that professionals compose each rhythmic tempo with profound analytical rigor and integrity",
    "When confronting complex challenges in studio session one must strum every sonorous chord with rigorous discipline and patient determination",
    "The integration of sonorous chord within modern studio session enables practitioners to strum critical milestones without sacrificing enduring quality",
    "Throughout the evolution of studio session master practitioners learned to strum the most intricate sonorous chord through persistent dedicated effort",
    "Developing comprehensive understanding of studio session demands that professionals strum each sonorous chord with profound analytical rigor and integrity",
    "When confronting complex challenges in musical poetry one must resonate every lyrical rhythm with rigorous discipline and patient determination",
    "The integration of lyrical rhythm within modern musical poetry enables practitioners to resonate critical milestones without sacrificing enduring quality",
    "Throughout the evolution of musical poetry master practitioners learned to resonate the most intricate lyrical rhythm through persistent dedicated effort",
    "Developing comprehensive understanding of musical poetry demands that professionals resonate each lyrical rhythm with profound analytical rigor and integrity",
    "When confronting complex challenges in sonic tapestry one must modulate every harmonic timbre with rigorous discipline and patient determination",
    "The integration of harmonic timbre within modern sonic tapestry enables practitioners to modulate critical milestones without sacrificing enduring quality",
    "Throughout the evolution of sonic tapestry master practitioners learned to modulate the most intricate harmonic timbre through persistent dedicated effort",
    "Developing comprehensive understanding of sonic tapestry demands that professionals modulate each harmonic timbre with profound analytical rigor and integrity",
    "When confronting complex challenges in choral harmony one must orchestrate every expressive scale with rigorous discipline and patient determination"
  ]
};

export async function seed() {
  return await upsertCategoryAndSentences(category, sentences);
}

if (process.argv[1]?.endsWith('music.mjs')) {
  seed().catch(console.error);
}
