import { upsertCategoryAndSentences } from './seed-helper.mjs';

export const category = {
  "slug": "mythology",
  "label": "Mythology & Legends",
  "icon": "⚡",
  "description": "Olympian gods, Norse sagas, mythical beasts, and heroic quests",
  "display_order": 18
};

export const sentences = {
  "easy": [
    "Zeus hurled bright lightning",
    "Thor swung heavy hammer",
    "Dragons hoard ancient gold",
    "The Phoenix rose again",
    "Heroes face great trials",
    "Pegasus flew past clouds",
    "Odin sought sacred runes",
    "Loki plotted clever mischief",
    "Poseidon commanded ocean waves",
    "Athena offered wise counsel",
    "Ares marched into war",
    "Hades ruled the underworld",
    "Anubis weighed mortal hearts",
    "Ra sailed solar barque",
    "Scylla lurked in rocks",
    "Charybdis swallowed passing ships",
    "Medusa turned men stone",
    "Centaur roamed wild woods",
    "Minotaur guarded stone maze",
    "Theseus followed golden thread",
    "vanquish the mythic chariot",
    "mythic chariot vanquish heroic quest",
    "chariot brings mythic heroic quest",
    "Always vanquish mythic chariot",
    "Every chariot can vanquish",
    "prophesy the immortal oracle",
    "immortal oracle prophesy divine retribution",
    "oracle brings immortal divine retribution",
    "Always prophesy immortal oracle",
    "Every oracle can prophesy",
    "conquer the divine labyrinth",
    "divine labyrinth conquer epic chronicle",
    "labyrinth brings divine epic chronicle",
    "Always conquer divine labyrinth",
    "Every labyrinth can conquer",
    "invoke the valiant relic",
    "valiant relic invoke sacred prophecy",
    "relic brings valiant sacred prophecy",
    "Always invoke valiant relic",
    "Every relic can invoke",
    "transcend the colossal pantheon",
    "colossal pantheon transcend olympian lore",
    "pantheon brings colossal olympian lore",
    "Always transcend colossal pantheon",
    "Every pantheon can transcend",
    "bestow the sacred spear",
    "sacred spear bestow norse saga",
    "spear brings sacred norse saga",
    "Always bestow sacred spear",
    "Every spear can bestow",
    "wield the heroic chalice",
    "heroic chalice wield heroic quest",
    "chalice brings heroic heroic quest",
    "Always wield heroic chalice",
    "Every chalice can wield",
    "inscribe the enchanted shield",
    "enchanted shield inscribe divine retribution",
    "shield brings enchanted divine retribution",
    "Always inscribe enchanted shield",
    "Every shield can inscribe",
    "summon the invincible saga",
    "invincible saga summon epic chronicle",
    "saga brings invincible epic chronicle",
    "Always summon invincible saga",
    "Every saga can summon",
    "manifest the legendary prophecy",
    "legendary prophecy manifest sacred prophecy",
    "prophecy brings legendary sacred prophecy",
    "Always manifest legendary prophecy",
    "Every prophecy can manifest",
    "mythic chariot vanquish olympian lore",
    "chariot brings mythic olympian lore",
    "immortal oracle prophesy norse saga",
    "oracle brings immortal norse saga",
    "divine labyrinth conquer heroic quest",
    "labyrinth brings divine heroic quest",
    "valiant relic invoke divine retribution",
    "relic brings valiant divine retribution",
    "colossal pantheon transcend epic chronicle",
    "pantheon brings colossal epic chronicle",
    "sacred spear bestow sacred prophecy",
    "spear brings sacred sacred prophecy",
    "heroic chalice wield olympian lore",
    "chalice brings heroic olympian lore",
    "enchanted shield inscribe norse saga",
    "shield brings enchanted norse saga",
    "invincible saga summon heroic quest",
    "saga brings invincible heroic quest",
    "legendary prophecy manifest divine retribution",
    "prophecy brings legendary divine retribution",
    "mythic chariot vanquish epic chronicle",
    "chariot brings mythic epic chronicle",
    "immortal oracle prophesy sacred prophecy",
    "oracle brings immortal sacred prophecy",
    "divine labyrinth conquer olympian lore",
    "labyrinth brings divine olympian lore",
    "valiant relic invoke norse saga",
    "relic brings valiant norse saga",
    "colossal pantheon transcend heroic quest",
    "pantheon brings colossal heroic quest"
  ],
  "normal": [
    "Pandora opened the forbidden box leaving only hope trapped inside",
    "Icarus flew too close to the blazing melting sun",
    "Achilles possessed invulnerable armor except for his fragile mortal heel",
    "The Minotaur guarded the winding subterranean labyrinth of ancient Crete",
    "Odin traded his eye for eternal divine cosmic wisdom",
    "Valkyries escorted fallen brave warriors to the golden feast halls",
    "Prometheus endured eternal punishment for gifting sacred fire to humanity",
    "Jason and brave Argonauts sailed in search of golden fleece",
    "Perseus used a mirrored shield to defeat the petrifying Gorgon",
    "The Oracle at Delphi spoke riddles foretelling tragic royal fates",
    "The mythic chariot will greatly vanquish our heroic quest today",
    "Every mythic chariot must vanquish carefully across the entire heroic",
    "Learning how to vanquish mythic chariot inspires deep heroic quest",
    "Our dedicated team will vanquish the mythic chariot for heroic",
    "The immortal oracle will greatly prophesy our divine retribution today",
    "Every immortal oracle must prophesy carefully across the entire divine",
    "Learning how to prophesy immortal oracle inspires deep divine retribution",
    "Our dedicated team will prophesy the immortal oracle for divine",
    "The divine labyrinth will greatly conquer our epic chronicle today",
    "Every divine labyrinth must conquer carefully across the entire epic",
    "Learning how to conquer divine labyrinth inspires deep epic chronicle",
    "Our dedicated team will conquer the divine labyrinth for epic",
    "The valiant relic will greatly invoke our sacred prophecy today",
    "Every valiant relic must invoke carefully across the entire sacred",
    "Learning how to invoke valiant relic inspires deep sacred prophecy",
    "Our dedicated team will invoke the valiant relic for sacred",
    "The colossal pantheon will greatly transcend our olympian lore today",
    "Every colossal pantheon must transcend carefully across the entire olympian",
    "Learning how to transcend colossal pantheon inspires deep olympian lore",
    "Our dedicated team will transcend the colossal pantheon for olympian",
    "The sacred spear will greatly bestow our norse saga today",
    "Every sacred spear must bestow carefully across the entire norse",
    "Learning how to bestow sacred spear inspires deep norse saga",
    "Our dedicated team will bestow the sacred spear for norse",
    "The heroic chalice will greatly wield our heroic quest today",
    "Every heroic chalice must wield carefully across the entire heroic",
    "Learning how to wield heroic chalice inspires deep heroic quest",
    "Our dedicated team will wield the heroic chalice for heroic",
    "The enchanted shield will greatly inscribe our divine retribution today",
    "Every enchanted shield must inscribe carefully across the entire divine",
    "Learning how to inscribe enchanted shield inspires deep divine retribution",
    "Our dedicated team will inscribe the enchanted shield for divine",
    "The invincible saga will greatly summon our epic chronicle today",
    "Every invincible saga must summon carefully across the entire epic",
    "Learning how to summon invincible saga inspires deep epic chronicle",
    "Our dedicated team will summon the invincible saga for epic",
    "The legendary prophecy will greatly manifest our sacred prophecy today",
    "Every legendary prophecy must manifest carefully across the entire sacred",
    "Learning how to manifest legendary prophecy inspires deep sacred prophecy",
    "Our dedicated team will manifest the legendary prophecy for sacred",
    "The mythic chariot will greatly vanquish our olympian lore today",
    "Every mythic chariot must vanquish carefully across the entire olympian",
    "Learning how to vanquish mythic chariot inspires deep olympian lore",
    "Our dedicated team will vanquish the mythic chariot for olympian",
    "The immortal oracle will greatly prophesy our norse saga today",
    "Every immortal oracle must prophesy carefully across the entire norse",
    "Learning how to prophesy immortal oracle inspires deep norse saga",
    "Our dedicated team will prophesy the immortal oracle for norse",
    "The divine labyrinth will greatly conquer our heroic quest today",
    "Every divine labyrinth must conquer carefully across the entire heroic",
    "Learning how to conquer divine labyrinth inspires deep heroic quest",
    "Our dedicated team will conquer the divine labyrinth for heroic",
    "The valiant relic will greatly invoke our divine retribution today",
    "Every valiant relic must invoke carefully across the entire divine",
    "Learning how to invoke valiant relic inspires deep divine retribution",
    "Our dedicated team will invoke the valiant relic for divine",
    "The colossal pantheon will greatly transcend our epic chronicle today",
    "Every colossal pantheon must transcend carefully across the entire epic",
    "Learning how to transcend colossal pantheon inspires deep epic chronicle",
    "Our dedicated team will transcend the colossal pantheon for epic"
  ],
  "hard": [
    "Prometheus defied the Olympian gods to deliver the gift of sacred fire and arts to mortal human civilizations",
    "The golden fleece was guarded by an unsleeping dragon until brave Jason arrived with his band of heroic Argonauts",
    "Ancient myths were symbolic maps guiding early human souls through grief terror romantic devotion and transcendent heroic moral courage",
    "Persephone return to the underworld plunged the earth into icy winter until spring green blossomed upon her joyful emergence",
    "Hercules completed twelve legendary labors demonstrating that mortal perseverance can triumph over divine wrath and monstrous impossible trials",
    "When confronting complex challenges in heroic quest one must vanquish every mythic chariot with rigorous discipline and patient determination",
    "The integration of mythic chariot within modern heroic quest enables practitioners to vanquish critical milestones without sacrificing enduring quality",
    "Throughout the evolution of heroic quest master practitioners learned to vanquish the most intricate mythic chariot through persistent dedicated effort",
    "Developing comprehensive understanding of heroic quest demands that professionals vanquish each mythic chariot with profound analytical rigor and integrity",
    "When confronting complex challenges in divine retribution one must prophesy every immortal oracle with rigorous discipline and patient determination",
    "The integration of immortal oracle within modern divine retribution enables practitioners to prophesy critical milestones without sacrificing enduring quality",
    "Throughout the evolution of divine retribution master practitioners learned to prophesy the most intricate immortal oracle through persistent dedicated effort",
    "Developing comprehensive understanding of divine retribution demands that professionals prophesy each immortal oracle with profound analytical rigor and integrity",
    "When confronting complex challenges in epic chronicle one must conquer every divine labyrinth with rigorous discipline and patient determination",
    "The integration of divine labyrinth within modern epic chronicle enables practitioners to conquer critical milestones without sacrificing enduring quality",
    "Throughout the evolution of epic chronicle master practitioners learned to conquer the most intricate divine labyrinth through persistent dedicated effort",
    "Developing comprehensive understanding of epic chronicle demands that professionals conquer each divine labyrinth with profound analytical rigor and integrity",
    "When confronting complex challenges in sacred prophecy one must invoke every valiant relic with rigorous discipline and patient determination",
    "The integration of valiant relic within modern sacred prophecy enables practitioners to invoke critical milestones without sacrificing enduring quality",
    "Throughout the evolution of sacred prophecy master practitioners learned to invoke the most intricate valiant relic through persistent dedicated effort",
    "Developing comprehensive understanding of sacred prophecy demands that professionals invoke each valiant relic with profound analytical rigor and integrity",
    "When confronting complex challenges in olympian lore one must transcend every colossal pantheon with rigorous discipline and patient determination",
    "The integration of colossal pantheon within modern olympian lore enables practitioners to transcend critical milestones without sacrificing enduring quality",
    "Throughout the evolution of olympian lore master practitioners learned to transcend the most intricate colossal pantheon through persistent dedicated effort",
    "Developing comprehensive understanding of olympian lore demands that professionals transcend each colossal pantheon with profound analytical rigor and integrity",
    "When confronting complex challenges in norse saga one must bestow every sacred spear with rigorous discipline and patient determination",
    "The integration of sacred spear within modern norse saga enables practitioners to bestow critical milestones without sacrificing enduring quality",
    "Throughout the evolution of norse saga master practitioners learned to bestow the most intricate sacred spear through persistent dedicated effort",
    "Developing comprehensive understanding of norse saga demands that professionals bestow each sacred spear with profound analytical rigor and integrity",
    "When confronting complex challenges in heroic quest one must wield every heroic chalice with rigorous discipline and patient determination"
  ]
};

export async function seed() {
  return await upsertCategoryAndSentences(category, sentences);
}

if (process.argv[1]?.endsWith('mythology.mjs')) {
  seed().catch(console.error);
}
