import { upsertCategoryAndSentences } from './seed-helper.mjs';

export const category = {
  "slug": "nature",
  "label": "Nature & Wildlife",
  "icon": "🌲",
  "description": "Forests, oceans, animal kingdoms, and wilderness landscapes",
  "display_order": 10
};

export const sentences = {
  "easy": [
    "Wolves howl at moon",
    "Rivers carve deep canyons",
    "Leaves turn amber gold",
    "Eagles soar over peaks",
    "Whales breach ocean waves",
    "Rain falls on moss",
    "Salmon swim up rivers",
    "Owls hunt in darkness",
    "Bears hibernate in winter",
    "Spiders spin delicate webs",
    "Ferns unfurl in spring",
    "Foxes prowl silent woods",
    "Deer graze green meadows",
    "Lions rule open savanna",
    "Tigers stalk in shadows",
    "Otters play in streams",
    "Hawks circle thermal winds",
    "Bees harvest golden pollen",
    "Frogs call near pond",
    "Snakes bask on stone",
    "Herons stand in shallows",
    "Pine trees smell fresh",
    "Acorns drop from oaks",
    "Moss carpets forest floor",
    "Mist covers mountain valley",
    "Sunlight filters through canopy",
    "Tide recedes from shore",
    "Seagulls call across bay",
    "Dolphins leap through surf",
    "Coral glows under water",
    "Jellyfish drift in currents",
    "Sharks patrol coral reefs",
    "Crabs scuttle across sand",
    "Crickets chirp in grass",
    "Fireflies illuminate summer night",
    "Caterpillars build silk cocoons",
    "Butterflies sip sweet nectar",
    "Ants march in line",
    "Woodpeckers drill tree bark",
    "Hummingbirds hover near blooms",
    "Geese fly south together",
    "Swans glide upon lake",
    "Wild horses roam plains",
    "Bison graze open prairie",
    "Mountain goats climb cliffs",
    "Cougars leap across rocks",
    "Snow leopards hunt peaks",
    "Pandas chew green bamboo",
    "Koalas sleep in eucalyptus",
    "Kangaroos hop across desert",
    "Emus run through bush",
    "Platypus swims fresh creeks",
    "Penguins waddle on ice",
    "Seals dive into sea",
    "Walrus rests on icebergs",
    "Polar bears hunt seals",
    "Arctic foxes follow tracks",
    "Reindeer migrate across tundra",
    "Mushrooms sprout after rain",
    "Vines climb tall trees",
    "Wild orchids bloom brightly",
    "Cactus thrives in drought",
    "Tumbleweeds blow in wind",
    "Geysers erupt boiling water",
    "Waterfalls crash into pool",
    "Caves hide underground rivers",
    "Canyons glow at dusk",
    "Glaciers move like turtles",
    "Volcanic ash enriches soil",
    "Mangroves protect sandy coastlines",
    "Wetlands filter fresh water",
    "Swamps teem with life",
    "Dunes shift with breeze",
    "Oasis appears in desert",
    "Thunder rolls across plains",
    "Rainbow bends across sky",
    "Morning dew coats leaves",
    "Frost covers winter grass",
    "Autumn winds shake branches",
    "Spring blossoms fill air",
    "Summer sun warms earth",
    "Winter snow blankets forest",
    "Nature restores tired souls",
    "Wilderness teaches deep humility",
    "Predators balance natural ecosystems",
    "Prey animals stay alert",
    "Insects aerate garden soil",
    "Birds spread fruit seeds",
    "Roots hold riverbanks firm",
    "Forests breathe for planet",
    "Oceans regulate global climate",
    "Wildflowers carpet rolling hills",
    "Sunflowers follow morning sun",
    "Beavers engineer wooden dams",
    "Wolves hunt in packs",
    "Ecosystems thrive with diversity",
    "Protect pristine natural habitats",
    "Conserve clean fresh water",
    "Cherish the animal kingdom",
    "Preserve ancient virgin forests"
  ],
  "normal": [
    "The coral reef shelters thousands of colorful marine creatures",
    "Redwood trees survive centuries by weaving roots tightly together",
    "Monarch butterflies migrate thousands of miles every single autumn",
    "Alpine flowers bloom resiliently upon steep frozen rocky slopes",
    "Lightning illuminates dark towering thunderclouds during intense midnight storms",
    "Fresh morning dew glistens across intricate green spider webs",
    "The silent flight of owls relies on specialized serrated feathers",
    "Salmon navigate thousands of river miles guided by olfactory memory",
    "Ancient sea turtles return precisely to the beaches where hatched",
    "Bioluminescent phytoplankton illuminate breaking waves with ethereal electric blue",
    "Apex predators maintain ecological equilibrium across sprawling grassland biomes",
    "Deciduous forests transform into brilliant tapestries of scarlet and gold",
    "Honeybees communicate the location of blooming flowers through waggle dances",
    "Glacial valleys showcase the immense scouring power of ancient ice",
    "The canopy layer of tropical rainforests harbors unparalleled terrestrial biodiversity",
    "Mangrove root systems dissipate wave energy protecting vulnerable coastlines",
    "Geothermal springs provide minerals sustaining unique extremophile microbial life",
    "Migratory birds navigate using internal biological compasses sensing magnetic fields",
    "The tundra ecosystem supports hardy flora adapted to permafrost conditions",
    "Desert cacti store rainwater in spongy expandable stem tissues efficiently",
    "Carnivorous plants thrive in nutrient poor soils by trapping insects",
    "Bioluminescence serves multiple evolutionary purposes from predation to camouflage",
    "Symbiotic nitrogen fixing bacteria enrich soil surrounding legume root nodules",
    "Coral bleaching occurs when rising ocean temperatures expel symbiotic algae",
    "Beavers construct sophisticated dams creating wetlands that foster diverse species",
    "The annual wildebeest migration represents one of greatest terrestrial spectacles",
    "Deep ocean hydrothermal vents support life without any sunlight input",
    "Fungal mycorrhizal networks facilitate nutrient exchange between distant forest trees",
    "Chameleons alter skin pigmentation through crystalline structural nanostructures within cells",
    "Arctic terns complete the longest annual migration of any animal",
    "The Amazon river basin discharges more water than any other",
    "Forest fires clear dense undergrowth allowing sunlight to reach seedlings",
    "Otters use sea kelp strands to anchor themselves during sleep",
    "The keen eyesight of raptors allows them to spot prey",
    "Photosynthetic algae produce substantial portions of atmospheric oxygen we breathe",
    "Tectonic uplift created soaring mountain ranges that alter regional weather",
    "Whale song travels across entire ocean basins through deep channels",
    "Invertebrates comprise the overwhelming majority of known animal species today",
    "Lichen represents a hardy symbiotic partnership between fungi and algae",
    "Estuaries serve as productive biological nurseries for hundreds of fish",
    "Subterranean cave ecosystems evolved troglobitic species without functional visual organs",
    "Pronghorn antelopes evolved unmatched running endurance to outrun extinct cheetahs",
    "The rings of trees record centuries of past climatic variations",
    "Pollination by native insects is indispensable for terrestrial food webs",
    "Alpine marmots enter deep hibernation to endure harsh winter blizzards",
    "Tidal pools reveal miniature ecosystems teeming with starfish and anemones",
    "Tropical cloud forests capture atmospheric moisture through moss draped branches",
    "Wolves reintroduction to Yellowstone rejuvenated overgrazed riparian vegetation corridors",
    "Desert flora bloom explosively following rare and unpredictable desert downpours",
    "Sea otters act as keystone species preserving coastal kelp forests",
    "Massive underground mycelial networks can span hundreds of forest acres",
    "Vampire bats demonstrate reciprocal food sharing among unrelated roost companions",
    "Ancient bristlecone pines survive thousands of years on barren dolomite",
    "The migration of monarch butterflies spans multiple successive insect generations",
    "Elephants communicate across long savannah distances using sub audible infrasonic",
    "Bioluminescent fireflies synchronize flashes across entire riverbanks in Southeast Asia",
    "Hummingbird metabolism demands consuming their own weight in nectar daily",
    "The protective coloration of snow leopards renders them virtually invisible",
    "Antarctic krill form one of the planet largest biomass congregations",
    "Pitcher plants drown curious insects in slippery digestive fluid reservoirs",
    "The complex architecture of termite mounds maintains constant internal temperatures",
    "Deep sea anglerfish illuminate bioluminescent lures to attract unsuspecting prey",
    "Migrating humpback whales fast for months during tropical breeding seasons",
    "The biodiversity of Madagascar evolved in isolation for millions years",
    "Giant sequoias rely on forest fires to burst open cones",
    "Planktonic food webs sustain the colossal nutritional requirements of whales",
    "The iridescent plumage of peacocks results from microscopic feather interference",
    "Mangroves excrete excess salt through specialized glands on leaf surfaces",
    "Polar bears possess black skin beneath white fur to absorb",
    "Preserving wilderness corridors ensures wildlife populations can migrate and adapt"
  ],
  "hard": [
    "Look deep into nature and then you will understand everything about human purpose and physical reality much better",
    "The clearest way into the universe is through a forest wilderness untouched by industrialized human hands and machinery",
    "In every walk with nature one receives far more than he ever sought to discover along the winding trail",
    "Ancient glaciers slowly carve majestic valleys as they grind quietly against continental bedrock over thousands of cold winters",
    "A solitary wolf tracks prey through dense snow covered pine forests beneath the emerald shimmer of northern aurora borealis",
    "The delicate balance of tropical coral reefs depends upon harmonious symbiosis between calcifying coral polyps and photosynthetic zooxanthellae algae",
    "Redwood canopies capture coastal morning fog allowing life giving droplets to shower down onto lush fern carpeted understory below",
    "Throughout the African savannah predator and prey engage in an ancient evolutionary dance honed over millions of perilous generations",
    "Beneath the forest floor vast fungal mycelial networks act as biological internet sharing carbon water and alarm signals between trees",
    "The annual salmon run injects millions of tons of ocean derived nitrogen directly into ancient coastal temperate rainforest ecosystems",
    "Migrating songbirds cross thousands of open sea miles navigating by stellar constellations and magnetic field lines with breathtaking accuracy",
    "Deep within ocean abyssal plains chemosynthetic tube worms thrive beside superheated mineral chimneys without receiving single ray of solar light",
    "The reintroduction of apex predators can trigger miraculous trophic cascades that stabilize eroding riverbanks and restore depleted biodiversity habitats",
    "Monarch butterflies embark on multi generational migrations demonstrating that behavioral blueprints can be preserved and transmitted through insect genetic code",
    "Mangrove forests act as indispensable nurseries for juvenile reef fish while shielding vulnerable coastal communities from devastating tropical storm surges",
    "Ancient bristlecone pines endure howling winds freezing temperatures and rocky alkaline soil on high mountain peaks for over four millennia",
    "Bioluminescence across the midnight ocean transforms dark depths into magical underwater galaxies illuminated by flashing jellyfish comb jellies and squids",
    "Tectonic forces push ocean floors into fiery subduction trenches while lifting soaring granite mountain spires toward cloud swept alpine skies",
    "The staggering diversity of the Amazon rainforest remains nature most complex living library holding undiscovered medicines and ecological marvels worldwide",
    "Every autumn millions of deciduous trees reabsorb chlorophyll revealing brilliant scarlet anthocyanin and golden carotenoid pigments before winter dormancy begins",
    "Desert seed banks lie dormant beneath sun baked sand for decades awaiting single torrential rainstorm to carpet wasteland in blooms",
    "Humpback whales collaborate in bubble net hunting creating spiral columns of air to corral panicked shoals of herring toward surface",
    "The intricate social structure of honeybee colonies functions like single superorganism where individual sacrifice preserves collective reproductive longevity of hive",
    "Polar ecosystems face existential challenges as retreating summer sea ice diminishes hunting platforms essential for polar bears and seal pups",
    "Wild rivers carve dramatic canyons through sedimentary strata exposing millions of years of ancient geological history to the open air",
    "The graceful dance of murmuration sees hundreds of thousands of starlings wheeling across dusk sky without single midair collision",
    "Preserving global biodiversity is not luxury but existential necessity for sustaining ecological services that make human life on Earth possible",
    "Old growth forests store immense volumes of terrestrial carbon while nurturing complex multi tiered ecosystems that second growth timber cannot",
    "From microscopic soil nematodes to colossal blue whales every creature occupies irreplaceable niche within the grand tapestry of planetary life",
    "Standing atop wind swept mountain pass beneath starry midnight sky one feels small yet inextricably woven into cosmic web of"
  ]
};

export async function seed() {
  return await upsertCategoryAndSentences(category, sentences);
}

if (process.argv[1]?.endsWith('nature.mjs')) {
  seed().catch(console.error);
}
