import { upsertCategoryAndSentences } from './seed-helper.mjs';

export const category = {
  "slug": "philosophy",
  "label": "Philosophy & Wisdom",
  "icon": "🏛️",
  "description": "Stoicism, existentialism, ethics, and timeless meditations",
  "display_order": 8
};

export const sentences = {
  "easy": [
    "I think therefore exist",
    "Know yourself deeply first",
    "Virtue is its reward",
    "Time heals all wounds",
    "Silence is often golden",
    "Seek wisdom not riches",
    "Patience yields true peace",
    "Question all your beliefs",
    "Reason guides moral action",
    "Truth requires honest courage",
    "Life is constant change",
    "Accept what comes naturally",
    "Desire causes human suffering",
    "Freedom requires personal discipline",
    "Death gives life meaning",
    "Character shapes personal destiny",
    "Moderation is golden mean",
    "Live in this moment",
    "Peace begins with understanding",
    "Justice protects the vulnerable",
    "Courage conquers hidden fear",
    "Wisdom outlasts all gold",
    "Mind creates own reality",
    "Forgiveness heals bitter hearts",
    "Nature teaches simple humility",
    "Kindness requires quiet strength",
    "Honor your daily word",
    "Curiosity leads to insight",
    "Doubt precedes true understanding",
    "Solitude brings profound clarity",
    "Embrace your mortal limits",
    "Cherish the passing seasons",
    "Listen before you judge",
    "Act without selfish expectation",
    "Self control is power",
    "Be content with simplicity",
    "Observe without hasty judgment",
    "Choose compassion over anger",
    "Gratitude transforms ordinary days",
    "Harmony resides within peace",
    "Virtuous deeds outlive empires",
    "Seek knowledge with humility",
    "Accept your honest fate",
    "Live with calm purpose",
    "Speak only truthful words",
    "Master your inner impulses",
    "Every dawn brings renewal",
    "Kindness is highest wisdom",
    "Reflection reveals inner truth",
    "Balance leads to serenity",
    "Walk the righteous path",
    "Let go of attachments",
    "Simplicity fosters deep joy",
    "Conquer yourself each day",
    "Quiet minds see clearly",
    "Honor the common good",
    "Patience overcomes heavy burdens",
    "Inner virtue cannot perish",
    "Respect every living creature",
    "Truth stands on itself",
    "Stand firm in virtue",
    "Embrace the stoic mindset",
    "Guard your mental fortress",
    "Cultivate an honest spirit",
    "Time flows like water",
    "Wisdom guides moral choice",
    "Dwell in peaceful thoughts",
    "Judge actions not words",
    "Control your own reactions",
    "Happiness is internal state",
    "Accept inevitable life changes",
    "Live according to nature",
    "Seek virtue above wealth",
    "Practice daily self examination",
    "Fear nothing except dishonor",
    "Strength lies in composure",
    "Be grateful for breath",
    "Wisdom is eternal light",
    "Tolerate other human faults",
    "Hold fast to truth",
    "Choose duty over desire",
    "Calm waves mirror sky",
    "Quiet heart hears wisdom",
    "Refrain from idle gossip",
    "Every hardship teaches lessons",
    "Kindness softens stubborn minds",
    "Endure with noble patience",
    "Treat all with dignity",
    "True wealth is contentment",
    "Live simply speak kindly",
    "Self mastery brings victory",
    "Focus on present duty",
    "Embrace the unfolding universe",
    "Light shines in darkness",
    "Act with good conscience",
    "Peace is highest virtue",
    "Seek harmony in all",
    "Wisdom guides righteous feet",
    "Purity of intent matters",
    "Endure and renounce attachments"
  ],
  "normal": [
    "We suffer more often in imagination than in reality",
    "The unexamined life is truly not worth living for humans",
    "Waste no more time arguing what a good person should",
    "Happiness depends entirely upon the quality of your inner thoughts",
    "You have power over your mind not outside worldly events",
    "He who has a why to live can bear almost",
    "Man is condemned to be free because he is fully",
    "The only true wisdom is in knowing you know almost",
    "When you arise think what a precious privilege it is",
    "Do not explain your philosophy rather embody its core virtues",
    "He who overcomes his desires is braver than him who",
    "It is not death a man should fear but never",
    "Very little is needed to make a happy peaceful life",
    "If it is not right do not do it immediately",
    "Dwell on the beauty of life watch the stars and",
    "The soul becomes dyed with the color of its frequent",
    "No man is free who is not master of himself",
    "First say to yourself what you would be and then",
    "Wealth consists not in having great possessions but having few",
    "Freedom is the only worthy goal in human earthly existence",
    "He who laughs at himself never runs out of things",
    "To be evenminded is the greatest virtue and wisdom in",
    "Character is both a long standing habit and a destiny",
    "There is nothing permanent in this world except constant ongoing",
    "The key is to keep company only with people who",
    "Be kind for everyone you meet is fighting a harder",
    "To live is the rarest thing in the entire world",
    "Better a little which is well done than a great",
    "He who is not contented with what he has would",
    "The greatest remedy for anger is delay and careful thoughtful",
    "A man who suffers before it is necessary suffers more",
    "True happiness is to enjoy the present without anxious dependence",
    "Difficulty shows what men truly are beneath the polished surface",
    "Know how to listen and you will profit even from",
    "It is a rough road that leads to the heights",
    "Silence is a lesson learned through life many painful trials",
    "He who fears death will never do anything worthy of",
    "To conquer oneself is a greater task than conquering others",
    "Do not spoil what you have by desiring what you",
    "The more you know the more you realize you know",
    "Live your life as an exclamation rather than an ongoing",
    "The art of living is more like wrestling than dancing",
    "Things do not touch the soul for they are external",
    "If someone is able to show me that what I",
    "Receive wealth or prosperity without arrogance and be ready to",
    "How much trouble he avoids who does not look to",
    "Never let the future disturb you you will meet it",
    "Look within within is the fountain of good and it",
    "The best revenge is to be unlike him who performed",
    "Loss is nothing else but change and change is Nature",
    "Each day provides its own gifts if we choose to",
    "Patience is the companion of wisdom throughout all human history",
    "Associate with people who are likely to improve you as",
    "Virtue is sufficient of itself for human happiness and peace",
    "No evil can happen to a good man either in",
    "The mind that is anxious about future events is miserable",
    "It is quality rather than quantity that matters in human",
    "He who wishes to be obeyed must know how to",
    "Wisdom ceases to be wisdom when it becomes too proud",
    "The greatest obstacle to living is expectancy which hangs upon",
    "Every night before going to sleep ask yourself what virtue",
    "Do every act of your life as though it were",
    "A ship should not ride on a single anchor nor",
    "Nothing can harm you except what makes you a worse",
    "Practice what you preach before attempting to teach it to",
    "Serenity comes when you trade expectations for deep and heartfelt",
    "A disciplined mind brings happiness while an undisciplined mind produces",
    "Treat people as if they were what they ought to",
    "The unexamined thought is often the root of all unnecessary",
    "Live in harmony with the cosmos and you will never"
  ],
  "hard": [
    "Man is condemned to be free because once thrown into the world he is responsible for everything he does",
    "The only true wisdom is in knowing you know absolutely nothing about the boundless and mysterious cosmos around us",
    "When you arise in the morning think of what a precious privilege it is to breathe think and love",
    "Do not explain your philosophy rather embody its core virtues in your daily actions and interactions with all people",
    "He who overcomes his desires is braver than him who conquers his formidable enemies for hardest victory is over self",
    "You have power over your mind not outside events realize this and you will find immense and enduring inner strength",
    "It is not that we have a short time to live but that we waste a great deal of it",
    "If anyone can refute me show me I am making a mistake or looking at things from wrong perspective I",
    "The happiness of your life depends upon the quality of your thoughts therefore guard accordingly and take care of your",
    "Waste no more time arguing about what a good man should be simply go forth and be one in daily",
    "He who fears death will never do anything worthy of a man who is truly alive and pursuing noble ideals",
    "Never esteem anything as of advantage to you that will make you break your word or lose your self respect",
    "Dwell on the beauty of life watch the twinkling stars and see yourself running alongside them in cosmic harmony",
    "The mind that is free from turbulent passions is a citadel for man has no fortress more secure to shelter",
    "Choose rather to be strong of soul than strong of body for inner resilience outlasts any physical worldly power",
    "We are more often frightened than hurt and we suffer more from our anxious imaginations than from reality itself",
    "Everything we hear is an opinion not a fact and everything we see is a perspective not the absolute truth",
    "Accept the things to which fate binds you and love the people with whom fate brings you together with heart",
    "To live a good life we have the potential for it if we can learn to be indifferent to what",
    "Begin each morning by telling yourself today I shall meet with the meddling ungrateful arrogant dishonest and envious people",
    "Do not act as if you were going to live ten thousand years death hangs over you while you live",
    "Whatever anyone does or says I must be emerald and keep my color declared the emperor regarding personal integrity",
    "Look back over the past with its changing empires that rose and fell and you can foresee the future also",
    "It is not the man who has too little but the man who craves more that is truly poor and",
    "How ridiculous and strange to be surprised at anything which happens in life since nature governs all things with necessity",
    "If you are distressed by anything external the pain is not due to thing itself but to your own estimate",
    "A man cannot lose either the past or the future for what a man cannot have how can anyone take",
    "External things are not the problem it is your assessment of them which you can erase this very moment with",
    "The soul becomes dyed with the color of its thoughts so bathe it frequently in courageous generous and benevolent reflections",
    "Life is neither good nor evil in itself but it is the scene of good and evil depending on our"
  ]
};

export async function seed() {
  return await upsertCategoryAndSentences(category, sentences);
}

if (process.argv[1]?.endsWith('philosophy.mjs')) {
  seed().catch(console.error);
}
