import { upsertCategoryAndSentences } from './seed-helper.mjs';

export const category = {
  "slug": "poetry",
  "label": "Poetry & Verse",
  "icon": "🖋️",
  "description": "Lyrical rhymes, romantic sonnets, and evocative verses",
  "display_order": 21
};

export const sentences = {
  "easy": [
    "Rose petals fall softly",
    "Stars whisper at night",
    "Shadows dance in moonlight",
    "Hope has gentle feathers",
    "Rivers hum sweet tunes",
    "Time flows like water",
    "Morning dew greets dawn",
    "Autumn winds sigh gently",
    "Candle flickers in dark",
    "Silence speaks to sorrow",
    "Golden leaves drift down",
    "Moonlight silver on sea",
    "Echoes fade across hills",
    "A lonely bird sings",
    "Dreams wake with sunrise",
    "Words woven like tapestry",
    "Heart beats in rhythm",
    "Rain taps window pane",
    "Gentle breeze stirs branches",
    "Beauty lingers in silence",
    "whisper the lyrical verse",
    "lyrical verse whisper poetic verse",
    "verse brings lyrical poetic verse",
    "Always whisper lyrical verse",
    "Every verse can whisper",
    "awaken the ethereal stanza",
    "ethereal stanza awaken moonlit sonnet",
    "stanza brings ethereal moonlit sonnet",
    "Always awaken ethereal stanza",
    "Every stanza can awaken",
    "resonate the poetic rhyme",
    "poetic rhyme resonate lyrical rhyme",
    "rhyme brings poetic lyrical rhyme",
    "Always resonate poetic rhyme",
    "Every rhyme can resonate",
    "echo the melodic sonnet",
    "melodic sonnet echo twilight stanza",
    "sonnet brings melodic twilight stanza",
    "Always echo melodic sonnet",
    "Every sonnet can echo",
    "breathe the haunting metaphor",
    "haunting metaphor breathe silent rhythm",
    "metaphor brings haunting silent rhythm",
    "Always breathe haunting metaphor",
    "Every metaphor can breathe",
    "illuminate the wistful rhythm",
    "wistful rhythm illuminate whispering wind",
    "rhythm brings wistful whispering wind",
    "Always illuminate wistful rhythm",
    "Every rhythm can illuminate",
    "caress the golden whisper",
    "golden whisper caress poetic verse",
    "whisper brings golden poetic verse",
    "Always caress golden whisper",
    "Every whisper can caress",
    "quiver the tender shadow",
    "tender shadow quiver moonlit sonnet",
    "shadow brings tender moonlit sonnet",
    "Always quiver tender shadow",
    "Every shadow can quiver",
    "transcend the radiant twilight",
    "radiant twilight transcend lyrical rhyme",
    "twilight brings radiant lyrical rhyme",
    "Always transcend radiant twilight",
    "Every twilight can transcend",
    "enchant the melancholic melody",
    "melancholic melody enchant twilight stanza",
    "melody brings melancholic twilight stanza",
    "Always enchant melancholic melody",
    "Every melody can enchant",
    "lyrical verse whisper silent rhythm",
    "verse brings lyrical silent rhythm",
    "ethereal stanza awaken whispering wind",
    "stanza brings ethereal whispering wind",
    "poetic rhyme resonate poetic verse",
    "rhyme brings poetic poetic verse",
    "melodic sonnet echo moonlit sonnet",
    "sonnet brings melodic moonlit sonnet",
    "haunting metaphor breathe lyrical rhyme",
    "metaphor brings haunting lyrical rhyme",
    "wistful rhythm illuminate twilight stanza",
    "rhythm brings wistful twilight stanza",
    "golden whisper caress silent rhythm",
    "whisper brings golden silent rhythm",
    "tender shadow quiver whispering wind",
    "shadow brings tender whispering wind",
    "radiant twilight transcend poetic verse",
    "twilight brings radiant poetic verse",
    "melancholic melody enchant moonlit sonnet",
    "melody brings melancholic moonlit sonnet",
    "lyrical verse whisper lyrical rhyme",
    "verse brings lyrical lyrical rhyme",
    "ethereal stanza awaken twilight stanza",
    "stanza brings ethereal twilight stanza",
    "poetic rhyme resonate silent rhythm",
    "rhyme brings poetic silent rhythm",
    "melodic sonnet echo whispering wind",
    "sonnet brings melodic whispering wind",
    "haunting metaphor breathe poetic verse",
    "metaphor brings haunting poetic verse"
  ],
  "normal": [
    "Two roads diverged in a yellow quiet autumn wood",
    "I took the one less traveled by today",
    "Shall I compare thee to a summer warm day",
    "Do not go gentle into that good night",
    "Rage against the dying of the fading light",
    "The woods are lovely dark and deep tonight",
    "Because I could not stop for death he stopped",
    "Tell me what you plan to do with life",
    "Poetry is the rhythmical creation of beauty through language",
    "Hope is the thing with feathers that perches soul",
    "The lyrical verse will greatly whisper our poetic verse today",
    "Every lyrical verse must whisper carefully across the entire poetic",
    "Learning how to whisper lyrical verse inspires deep poetic verse",
    "Our dedicated team will whisper the lyrical verse for poetic",
    "The ethereal stanza will greatly awaken our moonlit sonnet today",
    "Every ethereal stanza must awaken carefully across the entire moonlit",
    "Learning how to awaken ethereal stanza inspires deep moonlit sonnet",
    "Our dedicated team will awaken the ethereal stanza for moonlit",
    "The poetic rhyme will greatly resonate our lyrical rhyme today",
    "Every poetic rhyme must resonate carefully across the entire lyrical",
    "Learning how to resonate poetic rhyme inspires deep lyrical rhyme",
    "Our dedicated team will resonate the poetic rhyme for lyrical",
    "The melodic sonnet will greatly echo our twilight stanza today",
    "Every melodic sonnet must echo carefully across the entire twilight",
    "Learning how to echo melodic sonnet inspires deep twilight stanza",
    "Our dedicated team will echo the melodic sonnet for twilight",
    "The haunting metaphor will greatly breathe our silent rhythm today",
    "Every haunting metaphor must breathe carefully across the entire silent",
    "Learning how to breathe haunting metaphor inspires deep silent rhythm",
    "Our dedicated team will breathe the haunting metaphor for silent",
    "The wistful rhythm will greatly illuminate our whispering wind today",
    "Every wistful rhythm must illuminate carefully across the entire whispering",
    "Learning how to illuminate wistful rhythm inspires deep whispering wind",
    "Our dedicated team will illuminate the wistful rhythm for whispering",
    "The golden whisper will greatly caress our poetic verse today",
    "Every golden whisper must caress carefully across the entire poetic",
    "Learning how to caress golden whisper inspires deep poetic verse",
    "Our dedicated team will caress the golden whisper for poetic",
    "The tender shadow will greatly quiver our moonlit sonnet today",
    "Every tender shadow must quiver carefully across the entire moonlit",
    "Learning how to quiver tender shadow inspires deep moonlit sonnet",
    "Our dedicated team will quiver the tender shadow for moonlit",
    "The radiant twilight will greatly transcend our lyrical rhyme today",
    "Every radiant twilight must transcend carefully across the entire lyrical",
    "Learning how to transcend radiant twilight inspires deep lyrical rhyme",
    "Our dedicated team will transcend the radiant twilight for lyrical",
    "The melancholic melody will greatly enchant our twilight stanza today",
    "Every melancholic melody must enchant carefully across the entire twilight",
    "Learning how to enchant melancholic melody inspires deep twilight stanza",
    "Our dedicated team will enchant the melancholic melody for twilight",
    "The lyrical verse will greatly whisper our silent rhythm today",
    "Every lyrical verse must whisper carefully across the entire silent",
    "Learning how to whisper lyrical verse inspires deep silent rhythm",
    "Our dedicated team will whisper the lyrical verse for silent",
    "The ethereal stanza will greatly awaken our whispering wind today",
    "Every ethereal stanza must awaken carefully across the entire whispering",
    "Learning how to awaken ethereal stanza inspires deep whispering wind",
    "Our dedicated team will awaken the ethereal stanza for whispering",
    "The poetic rhyme will greatly resonate our poetic verse today",
    "Every poetic rhyme must resonate carefully across the entire poetic",
    "Learning how to resonate poetic rhyme inspires deep poetic verse",
    "Our dedicated team will resonate the poetic rhyme for poetic",
    "The melodic sonnet will greatly echo our moonlit sonnet today",
    "Every melodic sonnet must echo carefully across the entire moonlit",
    "Learning how to echo melodic sonnet inspires deep moonlit sonnet",
    "Our dedicated team will echo the melodic sonnet for moonlit",
    "The haunting metaphor will greatly breathe our lyrical rhyme today",
    "Every haunting metaphor must breathe carefully across the entire lyrical",
    "Learning how to breathe haunting metaphor inspires deep lyrical rhyme",
    "Our dedicated team will breathe the haunting metaphor for lyrical"
  ],
  "hard": [
    "Because I could not stop for death he kindly stopped for me along the slow carriage ride through town",
    "Water water everywhere nor any drop to drink lamented the weary sailor on open vast and desolate oceans",
    "Tell me what is it you plan to do with your one wild and precious life under the sun",
    "Poetry is the rhythmical creation of beauty through language that touches the most guarded and vulnerable human hearts",
    "In the desert I saw a creature naked bestial who squatting upon the ground ate his own burning heart",
    "When confronting complex challenges in poetic verse one must whisper every lyrical verse with rigorous discipline and patient determination",
    "The integration of lyrical verse within modern poetic verse enables practitioners to whisper critical milestones without sacrificing enduring quality",
    "Throughout the evolution of poetic verse master practitioners learned to whisper the most intricate lyrical verse through persistent dedicated effort",
    "Developing comprehensive understanding of poetic verse demands that professionals whisper each lyrical verse with profound analytical rigor and integrity",
    "When confronting complex challenges in moonlit sonnet one must awaken every ethereal stanza with rigorous discipline and patient determination",
    "The integration of ethereal stanza within modern moonlit sonnet enables practitioners to awaken critical milestones without sacrificing enduring quality",
    "Throughout the evolution of moonlit sonnet master practitioners learned to awaken the most intricate ethereal stanza through persistent dedicated effort",
    "Developing comprehensive understanding of moonlit sonnet demands that professionals awaken each ethereal stanza with profound analytical rigor and integrity",
    "When confronting complex challenges in lyrical rhyme one must resonate every poetic rhyme with rigorous discipline and patient determination",
    "The integration of poetic rhyme within modern lyrical rhyme enables practitioners to resonate critical milestones without sacrificing enduring quality",
    "Throughout the evolution of lyrical rhyme master practitioners learned to resonate the most intricate poetic rhyme through persistent dedicated effort",
    "Developing comprehensive understanding of lyrical rhyme demands that professionals resonate each poetic rhyme with profound analytical rigor and integrity",
    "When confronting complex challenges in twilight stanza one must echo every melodic sonnet with rigorous discipline and patient determination",
    "The integration of melodic sonnet within modern twilight stanza enables practitioners to echo critical milestones without sacrificing enduring quality",
    "Throughout the evolution of twilight stanza master practitioners learned to echo the most intricate melodic sonnet through persistent dedicated effort",
    "Developing comprehensive understanding of twilight stanza demands that professionals echo each melodic sonnet with profound analytical rigor and integrity",
    "When confronting complex challenges in silent rhythm one must breathe every haunting metaphor with rigorous discipline and patient determination",
    "The integration of haunting metaphor within modern silent rhythm enables practitioners to breathe critical milestones without sacrificing enduring quality",
    "Throughout the evolution of silent rhythm master practitioners learned to breathe the most intricate haunting metaphor through persistent dedicated effort",
    "Developing comprehensive understanding of silent rhythm demands that professionals breathe each haunting metaphor with profound analytical rigor and integrity",
    "When confronting complex challenges in whispering wind one must illuminate every wistful rhythm with rigorous discipline and patient determination",
    "The integration of wistful rhythm within modern whispering wind enables practitioners to illuminate critical milestones without sacrificing enduring quality",
    "Throughout the evolution of whispering wind master practitioners learned to illuminate the most intricate wistful rhythm through persistent dedicated effort",
    "Developing comprehensive understanding of whispering wind demands that professionals illuminate each wistful rhythm with profound analytical rigor and integrity",
    "When confronting complex challenges in poetic verse one must caress every golden whisper with rigorous discipline and patient determination"
  ]
};

export async function seed() {
  return await upsertCategoryAndSentences(category, sentences);
}

if (process.argv[1]?.endsWith('poetry.mjs')) {
  seed().catch(console.error);
}
