import { upsertCategoryAndSentences } from './seed-helper.mjs';

export const category = {
  "slug": "programming",
  "label": "Pro Programming",
  "icon": "💻",
  "description": "Code patterns, system architecture, engineering lore, and developer wit",
  "display_order": 4
};

export const sentences = {
  "easy": [
    "Write clean readable code",
    "Fix compiler syntax error",
    "Commit changes to git",
    "Push code to main",
    "Deploy service to production",
    "Build pipeline succeeded today",
    "Review incoming pull request",
    "Resolve merge conflict now",
    "Refactor messy legacy functions",
    "Run automated test suite",
    "Check server error logs",
    "Optimize slow database query",
    "Cache frequent API responses",
    "Containerize modern backend services",
    "Index primary database tables",
    "Prevent memory leak issues",
    "Handle null pointer exceptions",
    "Implement binary search tree",
    "Sort array in place",
    "Validate user input strings",
    "Sanitize database query inputs",
    "Monitor application response time",
    "Scale cluster horizontally now",
    "Encrypt sensitive user credentials",
    "Parse incoming JSON payload",
    "Configure reverse proxy routes",
    "Manage global state stores",
    "Benchmark CPU execution speed",
    "Profile memory heap allocations",
    "Design responsive user interfaces",
    "Minify production asset files",
    "Implement rate limiting rules",
    "Automate repetitive development tasks",
    "Debug async race conditions",
    "Upgrade outdated software dependencies",
    "Follow continuous integration practices",
    "Enforce strict typing rules",
    "Document public API endpoints",
    "Mock external network calls",
    "Configure local environment variables",
    "Generate secure access tokens",
    "Rotate database secret keys",
    "Define reusable component props",
    "Format code with prettier",
    "Inspect network payload headers",
    "Track uncaught runtime exceptions",
    "Write modular helper utilities",
    "Audit open source packages",
    "Configure cloud load balancers",
    "Implement optimistic UI updates",
    "Talk is very cheap",
    "Show me the code",
    "Code is like humor",
    "Deleted code is debugged",
    "Make it work first",
    "Make it run fast",
    "Make it clean right",
    "Premature optimization brings evil",
    "Simplicity is true efficiency",
    "First solve the problem",
    "Then write clean code",
    "Testing leads to understanding",
    "Functions should do one",
    "Do that one well",
    "Walking on water easier",
    "Specs are deeply frozen",
    "Nine people cannot deliver",
    "Babies in single month",
    "Any fool can code",
    "Good coders write humans",
    "Debugging twice as hard",
    "Writing the first place",
    "Cache invalidation is hard",
    "Naming things is hard",
    "Off by one errors",
    "Software entropy always increases",
    "Best error never shows",
    "Avoid global variable state",
    "Pure functions prevent bugs",
    "Immutability ensures predictable state",
    "Async await simplifies callbacks",
    "Promises resolve or reject",
    "Map filter reduce arrays",
    "Typescript catches compile bugs",
    "Use semantic html tags",
    "Keep components small reusable",
    "Hooks manage lifecycle state",
    "Custom hooks encapsulate logic",
    "Virtual dom diffs nodes",
    "Tailwind speeds up styling",
    "Nextjs optimizes route loading",
    "Server components stream html",
    "Prisma queries relational tables",
    "Postgres handles complex joins",
    "Redis stores ephemeral sessions",
    "Websockets enable live duplex",
    "GraphQL queries exact shapes",
    "REST apis follow verbs",
    "Docker isolates runtime environments",
    "Kubernetes orchestrates pod clusters"
  ],
  "normal": [
    "Every great developer got there by solving problems they were unqualified to solve",
    "The best error message is the one that never shows up to user",
    "Talk is cheap show me the actual working implementation in code",
    "Programs must be written for people to read and only incidentally for machines",
    "Code is like humor when you have to explain it it is bad",
    "Always write code as if the maintainer knows where you live",
    "A software function should do one thing and do it exceptionally well",
    "Walking on water and developing software from specifications are both easy if frozen",
    "Make it work correctly make it right and then make it fast",
    "Premature optimization is the root of all evil in software engineering",
    "It is not a software bug it is an undocumented creative feature",
    "Nine programmers cannot make a software release in one single month",
    "Any fool can write code that computers understand good programmers write human readable",
    "Debugging is twice as hard as writing the code in first place",
    "There are only two hard things cache invalidation and naming things",
    "Simplicity of system architecture is the true soul of sustainable engineering",
    "Programming is not merely typing syntax it is rigorous structured thinking",
    "The best performance improvement is moving from nonworking to working state",
    "Software is like entropy it is difficult to grasp and always increases",
    "First solve the underlying user problem then write the minimal code required",
    "Testing leads to unexpected failure and failure leads to deep engineering understanding",
    "Continuous integration pipelines catch regressions before they impact live production users",
    "Immutable state structures prevent subtle concurrency race conditions across asynchronous threads",
    "Microservices introduce distributed network complexity while monolithic architectures simplify local debugging",
    "Relational database indices accelerate queries but impose measurable write throughput overhead",
    "Writing automated unit tests provides a psychological safety net during refactoring",
    "Semantic versioning communicates breaking changes clearly to downstream open source consumers",
    "Proper error handling distinguishes robust production applications from fragile proof concepts",
    "Caching hot database queries in Redis dramatically reduces database cpu utilization",
    "Container orchestration simplifies rolling deployments with zero recorded service downtime",
    "Good documentation is just as valuable as elegant clean algorithms",
    "Stateless web servers scale horizontally across multi cloud availability zones seamlessly",
    "Static type checkers catch common null reference exceptions at compile time",
    "Monitoring request latency and error rates provides proactive visibility into systems",
    "Refactoring messy technical debt pays compounding dividends across software lifecycles",
    "Asynchronous event queues decouple long running background jobs from request handlers",
    "Code reviews encourage knowledge sharing and maintain consistency across engineering teams",
    "Automated database migrations ensure reproducible schema state across staging and production",
    "Designing backward compatible RESTful endpoints prevents unexpected breakage for mobile clients",
    "A clean git commit history tells a coherent story of development",
    "Declarative user interfaces simplify state synchronization between backend models and screens",
    "Rate limiting protects vulnerable authentication endpoints against brute force credential stuffing",
    "Dependency injection fosters modular architecture and simplifies writing mock unit tests",
    "Serverless computing eliminates server management overhead but introduces cold start latency",
    "Garbage collection pauses can introduce unpredictable latency spikes in real time applications",
    "Cross origin resource sharing policies protect browser clients from malicious external domains",
    "Configuring proper content security policy headers mitigates cross site scripting vulnerabilities",
    "Structured JSON logging simplifies debugging distributed microservices through centralized search clusters",
    "Writing idempotency keys into payment requests prevents accidental double billing for customers",
    "Benchmarking under realistic production load exposes bottleneck locks before customer traffic arrives",
    "Event sourcing captures state mutations as immutable sequences of historical facts",
    "Feature flags allow engineering teams to decouple code deployment from release",
    "Optimistic locking mechanisms detect concurrent database row modifications without blocking transactions",
    "GraphQL allows client applications to request precisely the attributes they need",
    "Database connection pooling prevents thread exhaustion under sudden high concurrency spikes",
    "Clean software architecture separates domain business rules from external transport mechanisms",
    "Domain driven design models complex enterprise workflows into ubiquitous shared vocabularies",
    "Zero downtime database schema migrations require additive non breaking multi stage releases",
    "Edge compute functions execute logic geographically closer to global end users",
    "Automated dependency security scanners identify known published vulnerabilities in project lockfiles",
    "Static site generation produces blazing fast web pages with minimal compute",
    "WebAssembly enables high performance compiled algorithms to run securely inside browsers",
    "Distributed tracing assigns correlation identifiers to track requests across microservice boundaries",
    "Circuit breakers prevent cascade failures when upstream third party dependencies become unresponsive",
    "Consistent code formatting eliminates bikeshedding arguments during asynchronous pull request reviews",
    "Database replication provides high availability read scaling across disparate geographic data centers",
    "Strongly typed programming languages reduce cognitive load when navigating large unfamiliar codebases",
    "Single responsibility principle ensures modules change for only one well defined reason",
    "Inversion of control containers decouple high level policy from low level implementations",
    "The most reliable code is the code that you never had to write"
  ],
  "hard": [
    "Always write code as if the person who ends up maintaining it will be a violent psychopath who knows where you live",
    "Deleted code is debugged code and the fastest code is the routine that never executes during runtime",
    "Controlling complexity is the essence of computer programming and simplicity is prerequisite for reliability in software",
    "Measuring programming progress by lines of code is like measuring aircraft building progress by physical weight and volume",
    "There are two ways of constructing software design one is to make it so simple that there are obviously no deficiencies",
    "The other way is to make it so complicated that there are no obvious deficiencies in architecture",
    "Walking on water and developing software from a specification are easy only when both requirements are completely frozen solid",
    "Premature optimization is the root of all evil yet we should not pass up our opportunities in critical hotspots",
    "A language that doesn’t affect the way you think about programming is not worth knowing or studying deeply",
    "Before software can be reusable it first has to be usable and verified through realistic production traffic loads",
    "The function of good software architecture is to postpone speculative implementation decisions as long as possible without penalty",
    "Good code is its own best documentation as you are about to add a comment ask yourself how code could clarify",
    "It is practically impossible to teach good programming to students that have had a prior exposure to undisciplined hacking",
    "Simplicity does not precede complexity but follows it after countless iterations of refactoring and ruthless distillation of requirements",
    "The greatest performance improvements arise not from micro optimizing inner loops but from designing superior algorithmic data structures",
    "Distributed systems are inherently unpredictable because network partitions machine crashes and clock drift will inevitably happen simultaneously",
    "Writing comprehensive automated test coverage does not guarantee absence of software defects but it guarantees regressions are rapidly detected",
    "Decoupling state mutation from pure side effect computation makes asynchronous applications substantially easier to test and reason about",
    "When microservices multiply without clear organizational domain boundaries network latency and distributed failure modes multiply exponentially across production",
    "Engineering teams that prioritize continuous refactoring and eliminate technical debt ship features with consistent velocity over years",
    "A database without foreign key constraints and transactional integrity guarantees will eventually accumulate corrupt orphaned data under high concurrency",
    "Software engineers must resist the temptation to invent complex custom abstractions when standard boring battle tested solutions already exist",
    "Ensuring end to end type safety from backend database schemas to frontend user interface components eliminates entire classes of runtime errors",
    "Building resilient systems requires embracing failure as normal event rather than rare anomaly through chaos testing and graceful degradation",
    "The cost of fixing a software defect increases by an order of magnitude at each phase from unit testing to production release",
    "Caching invalidation remains treacherous because stale data can propagate silently through downstream services without triggering explicit error alerts",
    "Every complex system that works was found to have evolved from a simple system that worked reliably in production",
    "Over engineering occurs when developers solve hypothetical future problems rather than addressing current verified concrete requirements of users",
    "Clean code reads like well written prose where classes and functions reveal their architectural intent without cognitive friction",
    "Observability requires collecting structured telemetry logs distributed tracing metrics and actionable alerts to diagnose novel emergent production behaviors"
  ]
};

export async function seed() {
  return await upsertCategoryAndSentences(category, sentences);
}

if (process.argv[1]?.endsWith('programming.mjs')) {
  seed().catch(console.error);
}
