import { upsertCategoryAndSentences } from './seed-helper.mjs';

export const category = {
  "slug": "quotes",
  "label": "Famous Quotes",
  "icon": "💬",
  "description": "Inspirational quotes and timeless reflections from notable figures",
  "display_order": 3
};

export const sentences = {
  "easy": [
    "Love what you do",
    "Never give up hope",
    "Be the change today",
    "Knowledge is true power",
    "Stay hungry stay foolish",
    "Simplicity is ultimate sophistication",
    "Think outside the box",
    "Fortune favors the brave",
    "Time waits for nobody",
    "Every moment matters deeply",
    "Truth shall set free",
    "Believe you can succeed",
    "Dream big work hard",
    "Action speaks louder words",
    "Silence is golden speech",
    "Patience is bitter virtue",
    "Kindness costs nothing ever",
    "Life is very short",
    "Choose courage over comfort",
    "Creativity takes great courage",
    "Live and let live",
    "Hope anchors human soul",
    "Wisdom begins with wonder",
    "No pressure no diamonds",
    "Failure is learning opportunity",
    "Light overcomes all darkness",
    "Peace begins with smile",
    "Character is destiny always",
    "Happiness is inside you",
    "Honesty is best policy",
    "Practice makes master craft",
    "Small deeds beat intentions",
    "Live in the present",
    "Grace under extreme pressure",
    "Forgive but never forget",
    "Joy is contagious energy",
    "Courage conquers all fear",
    "Faith moves mighty mountains",
    "Gratitude changes everything now",
    "Beauty lies within simplicity",
    "Listen more speak less",
    "Brevity is wit soul",
    "Seek truth not praise",
    "Great things take time",
    "Mind over physical matter",
    "Keep your eyes forward",
    "Stand for noble ideals",
    "Lead by humble example",
    "Speak with honest intention",
    "Victory belongs to persistent",
    "Dare to know yourself",
    "Trust your inner voice",
    "Change begins from within",
    "Stars require deep darkness",
    "Rise above the noise",
    "Embrace every new challenge",
    "Never stop asking questions",
    "Curiosity opens every door",
    "Patience brings sweetest fruit",
    "Focus on what matters",
    "Leave world better place",
    "Inspire someone today friend",
    "Every expert was beginner",
    "Make today count forever",
    "Stand tall through storms",
    "Create your own sunshine",
    "Follow your true north",
    "Cherish the journey always",
    "Small steps bring victory",
    "Energy flows where attention",
    "Boldness has genius power",
    "Keep learning every day",
    "Shine bright without apology",
    "Plant seeds for tomorrow",
    "Kind words heal wounds",
    "Stay humble through success",
    "Turn scars into wisdom",
    "Greatness lies in service",
    "Breathe through the chaos",
    "Choose love over fear",
    "Let your light shine",
    "Sow seeds of kindness",
    "Honor your daily truth",
    "Live with deep gratitude",
    "Seek beauty in ordinary",
    "Strength grows through resistance",
    "Write your own story",
    "Never regret being kind",
    "Quiet minds hear wisdom",
    "Work with passionate purpose",
    "Build bridges not walls",
    "Courage is contagious always",
    "Keep moving forward bravely",
    "Celebrate every small win",
    "Lift others as climb",
    "Purity of thought guides",
    "Inner peace surpasses understanding",
    "Find joy in journey",
    "Be gentle with yourself",
    "Create with open heart"
  ],
  "normal": [
    "The only way to do great work is to love what you do",
    "In the middle of difficulty lies great opportunity for growth",
    "Life is what happens while you are making other plans",
    "The future belongs to those who believe in their dreams",
    "It does not matter how slowly you go as long as you do not stop",
    "The best time to plant a tree was twenty years ago",
    "Be the change that you wish to see in this world",
    "Success is not final and failure is not fatal in life",
    "To be yourself in a conformist world is the greatest triumph",
    "The mind is everything what you think you eventually become",
    "Imagination is more important than knowledge in creative pursuits",
    "Happiness is not something readymade it comes from your actions",
    "Do what you can with what you have right where you are",
    "Not all those who wander are lost in the deep woods",
    "In the depth of winter I found an invincible summer inside",
    "Darkness cannot drive out darkness only light can do that",
    "The journey of a thousand miles begins with a single step",
    "What lies behind us and before us are tiny matters compared within",
    "The greatest glory in living lies not in never falling",
    "An unexamined life is truly not worth living for any human",
    "Act as if what you do makes a difference because it does",
    "You must do the things you think you cannot possibly do",
    "Turn your wounds into wisdom and your challenges into greatest assets",
    "If you want to lift yourself up lift up someone else",
    "The purpose of our lives is to be happy and helpful",
    "Change your thoughts and you change your entire reality around you",
    "We become what we think about most of the waking time",
    "It always seems impossible until it is finally achieved by someone",
    "Do not go where the path may lead go where there is no path",
    "Live as if you were to die tomorrow and learn as if forever",
    "Everything you have ever wanted is sitting on the other side of fear",
    "Happiness depends upon ourselves and not upon external shifting circumstances",
    "Peace comes from within do not seek it without in worldly praise",
    "A room without books is like a body without a soul",
    "Knowing yourself is the beginning of all true wisdom and enlightenment",
    "There is nothing either good or bad but thinking makes it so",
    "If you tell the truth you do not need to remember anything",
    "We must accept finite disappointment but never lose infinite genuine hope",
    "Keep your face always toward the sunshine and shadows will fall behind",
    "No one can make you feel inferior without your own consent",
    "Success usually comes to those who are too busy looking for it",
    "You will face many defeats in life but never let yourself be defeated",
    "The secret of getting ahead is simply getting started right now",
    "Opportunities multiply as they are seized with bold decisive action",
    "What we achieve inwardly will change outer reality in surprising ways",
    "The greatest wealth is to live content with very little in heart",
    "Do not wait to strike till the iron is hot make it hot",
    "Simplicity is the keynote of all true elegance in life",
    "Defeat is not the worst of failures not to have tried is true failure",
    "A champion is defined not by their wins but how they recover",
    "The only true wisdom is knowing that you know almost nothing",
    "Energy and persistence conquer all obstacles across human endeavors and history",
    "Your time is limited so do not waste it living someone else life",
    "Character is like a tree and reputation is like its fleeting shadow",
    "To succeed in life you need two things ignorance and boundless confidence",
    "The brave man is not he who does not feel afraid",
    "Great minds discuss ideas average minds discuss events small minds discuss people",
    "He who has courage and faith will never perish in misery",
    "Live each day as if your life had just begun today",
    "It is during our darkest moments that we must focus to see light",
    "Nothing great was ever achieved without enthusiastic dedication and persistent effort",
    "The best revenge is massive success achieved through calm quiet excellence",
    "Education is the most powerful weapon which you can use to change world",
    "We are what we repeatedly do excellence then is a lasting habit",
    "Stay true to yourself and the world will adjust around you",
    "Doubt kills more dreams than failure ever will in human lives",
    "Let the beauty of what you love be what you do daily",
    "Where there is love there is life and enduring hope for all",
    "A person who never made a mistake never tried anything new",
    "Count your age by friends not years count life by smiles not tears"
  ],
  "hard": [
    "To be yourself in a world that is constantly trying to make you something else is greatest accomplishment",
    "Success is not final failure is not fatal it is the courage to continue that counts through all storms",
    "Our greatest glory is not in never falling but in rising every time we fall upon difficult ground",
    "Two roads diverged in a wood and I took the one less traveled by and that made all difference",
    "In the end we will remember not the words of our enemies but the silence of our true friends",
    "The question isn’t who is going to let me it is who is going to stop me from striving forward",
    "Twenty years from now you will be more disappointed by the things you didn’t do than by the ones you did",
    "Spread love everywhere you go let no one ever come to you without leaving happier and far more peaceful",
    "I have learned that people will forget what you said people will forget what you did but never how you made feel",
    "Do not dwell in the past do not dream of the future concentrate the mind on the present waking moment",
    "Whatever you are physically or mentally you are because you have chosen to be that way through daily habits",
    "The only limit to our realization of tomorrow will be our doubts of today let us advance with strong faith",
    "When one door of happiness closes another opens but often we look so long at the closed door we miss open one",
    "You cannot swim for new horizons until you have courage to lose sight of the familiar shore for long while",
    "It is not the critic who counts not the man who points out how the strong man stumbles or where deeds fell short",
    "The credit belongs to the man who is actually in the arena whose face is marred by dust and sweat and blood",
    "Live in such a way that if someone spoke badly of you no one would ever believe them for single moment",
    "What you do speaks so loudly that I cannot hear what you say about your noble intentions and grand promises",
    "Watch your thoughts they become your words watch your words they become your actions and watch your actions they become character",
    "A bird sitting on a tree is never afraid of the branch breaking because her trust is not on branch but wings",
    "We do not inherit the earth from our ancestors rather we borrow it carefully from our children for future generations",
    "Give me six hours to chop down a tree and I will spend the first four sharpening the axe with precision",
    "The greatest danger for most of us is not that our aim is too high and we miss it but too low",
    "Peace cannot be kept by force it can only be achieved through genuine empathy and profound mutual understanding among nations",
    "Stand up for what is right even if you stand completely alone against the howling winds of popular public opinion",
    "The ultimate measure of a man is not where he stands in moments of comfort but where he stands at challenge",
    "Real integrity is doing the right thing knowing that nobody is going to know whether you did it or not",
    "If you cannot fly then run if you cannot run then walk if you cannot walk then crawl keep moving",
    "Do not judge each day by the harvest you reap but by the seeds that you carefully plant into soil",
    "Happiness is when what you think what you say and what you do are all in complete and beautiful harmony"
  ]
};

export async function seed() {
  return await upsertCategoryAndSentences(category, sentences);
}

if (process.argv[1]?.endsWith('quotes.mjs')) {
  seed().catch(console.error);
}
