import { upsertCategoryAndSentences } from './seed-helper.mjs';

export const category = {
  "slug": "science",
  "label": "Science & Cosmos",
  "icon": "🔬",
  "description": "Astronomy, quantum physics, biology, chemistry, and wonder of the universe",
  "display_order": 6
};

export const sentences = {
  "easy": [
    "Gravity pulls objects downward",
    "Light travels extremely fast",
    "Cells divide to reproduce",
    "Atoms form all matter",
    "Stars burn bright hydrogen",
    "Energy cannot be destroyed",
    "Water freezes at zero",
    "Planets orbit the sun",
    "DNA carries genetic code",
    "Photons have zero mass",
    "Electrons orbit atomic nucleus",
    "Protons carry positive charge",
    "Neutrons have neutral charge",
    "Earth rotates on axis",
    "Moon causes ocean tides",
    "Sound waves require medium",
    "Prism splits white light",
    "Magnets attract iron metal",
    "Plants absorb carbon dioxide",
    "Trees produce fresh oxygen",
    "Molecules bond together chemically",
    "Enzymes speed up reactions",
    "Fungi decompose organic matter",
    "Bacteria live everywhere globally",
    "Viruses require host cells",
    "Blood carries dissolved oxygen",
    "Heart pumps red blood",
    "Lungs breathe ambient air",
    "Brain contains billions neurons",
    "Eyes perceive visible spectrum",
    "Ears detect acoustic vibration",
    "Skin protects internal organs",
    "Bones provide structural support",
    "Muscles contract to move",
    "Fossils preserve prehistoric life",
    "Evolution shapes animal species",
    "Tectonic plates shift slowly",
    "Volcanoes erupt molten lava",
    "Earthquakes release seismic energy",
    "Atmosphere shields harmful radiation",
    "Ozone layer absorbs ultraviolet",
    "Rainbows refract rainy sunlight",
    "Clouds consist of droplets",
    "Lightning heats ambient air",
    "Thunder follows bright lightning",
    "Glaciers carve deep valleys",
    "Rivers flow toward oceans",
    "Salt dissolves into water",
    "Acids taste very sour",
    "Bases feel very slippery",
    "Helium is lighter air",
    "Iron rusts in moisture",
    "Combustion produces hot heat",
    "Speed of light constant",
    "Space is near vacuum",
    "Black holes trap light",
    "Milky Way is galaxy",
    "Andromeda collides with us",
    "Comets have icy tails",
    "Asteroids orbit between planets",
    "Supernovae forge heavy elements",
    "Nebulae birth baby stars",
    "Pulsars emit radio beams",
    "Quasars shine across cosmos",
    "Dark matter binds galaxies",
    "Cosmos expands every second",
    "Universe began with bang",
    "Entropy increases over time",
    "Absolute zero stops motion",
    "Quantum particles can tunnel",
    "Waves exhibit interference patterns",
    "Laser light is coherent",
    "Solar panels convert photons",
    "Nuclear fission splits atoms",
    "Fusion powers our sun",
    "Gravity bends passing light",
    "Time dilates at speed",
    "Matter and energy equivalent",
    "Chlorophyll absorbs red blue",
    "Symbiosis benefits both species",
    "Predators hunt for prey",
    "Herbivores eat green plants",
    "Food webs sustain ecosystems",
    "Coral reefs host biodiversity",
    "Plankton produce ocean oxygen",
    "Mammals nurse their young",
    "Reptiles lay scaly eggs",
    "Birds evolved from dinosaurs",
    "Amphibians live double lives",
    "Insects have six legs",
    "Spiders spin silk webs",
    "Bees pollinate blooming flowers",
    "Ants build complex colonies",
    "Termites digest wooden fibers",
    "Roots anchor tall trees",
    "Leaves turn toward sunlight",
    "Science explores cosmic wonder 96",
    "Science explores cosmic wonder 97",
    "Science explores cosmic wonder 98",
    "Science explores cosmic wonder 99"
  ],
  "normal": [
    "Photosynthesis converts radiant sunlight into chemical energy for growing plants",
    "DNA carries detailed genetic instructions for all living cellular organisms",
    "Black holes possess gravitational pulls that trap even fleeing light",
    "The speed of sound depends directly on the surrounding medium",
    "Quantum particles can exist in multiple probabilistic states simultaneously together",
    "Plate tectonics continuously reshape the continental landmasses of our planet",
    "Mitochondria generate adenosine triphosphate through respiration inside living eukaryotic cells",
    "The ozone layer absorbs dangerous ultraviolet radiation emitted by sun",
    "Radioactive isotopes decay into stable elements at mathematically predictable rates",
    "General relativity demonstrates that massive celestial bodies curve surrounding spacetime",
    "Supermassive black holes anchor the spinning centers of spiral galaxies",
    "Electromagnetic radiation travels across empty space at the speed light",
    "Natural selection drives the gradual evolution of species over epochs",
    "The periodic table organizes chemical elements by their atomic numbers",
    "Bioluminescent deep sea organisms generate cold light through chemical luciferin",
    "Cosmic microwave background radiation is the ancient thermal afterglow creation",
    "Enzymes act as biological catalysts lowering activation energy for reactions",
    "Neurotransmitters transmit electrochemical signals across microscopic synaptic gaps between neurons",
    "Tectonic subduction zones trigger intense volcanic eruptions and deep earthquakes",
    "The greenhouse effect traps atmospheric thermal infrared energy keeping Earth",
    "Gravitational waves ripple across spacetime when massive neutron stars collide",
    "Cellular mitosis produces two genetically identical daughter cells from parent",
    "Stem cells possess the remarkable capacity to differentiate into specialized",
    "Hubble discovered that distant galaxies are rapidly receding away from",
    "Quantum entanglement links particle properties instantaneously across vast cosmological distances",
    "The human genome contains approximately three billion nucleotide base pairs",
    "Superconductors conduct electrical current with zero resistance at cryogenic temperatures",
    "Thermodynamics dictates that total entropy in closed systems always increases",
    "Photosynthetic phytoplankton produce more than half of the planet oxygen",
    "Kepler laws precisely describe the elliptical orbits of planets orbiting",
    "Hydrogen is the most abundant chemical element throughout the observable",
    "The magnetic field of Earth deflects solar wind charged particles",
    "Epigenetic modifications alter gene expression without mutating the underlying DNA",
    "Dark energy constitutes roughly sixty eight percent of total cosmic",
    "Coronal mass ejections from the sun can disrupt terrestrial satellite",
    "Geothermal energy originates from radioactive decay deep within Earth mantle",
    "Bacteriophages are specialized viruses that infect and destroy pathogenic bacteria",
    "The Doppler effect shifts light frequencies toward blue or red",
    "Carbon atoms form four covalent bonds allowing complex molecular chemistry",
    "Tidal forces from the moon gradually slow the rotation of",
    "Cryogenic temperatures slow molecular motion to near absolute zero limits",
    "Cellular apoptosis is programmed cell death essential for tissue development",
    "Brownian motion provided early empirical evidence for the atomic hypothesis",
    "Bioluminescence allows deep ocean creatures to communicate hunt and camouflage",
    "Continental drift was originally proposed based on matching fossil coastlines",
    "Atmospheric pressure decreases exponentially with increasing altitude above sea level",
    "Antibiotic resistance evolves rapidly when bacterial populations encounter sublethal dosages",
    "Gravitational lensing magnifies faint distant galaxies behind massive foreground clusters",
    "The Coriolis effect deflects prevailing winds across spinning planetary atmospheres",
    "All living organisms share a universal genetic code of four",
    "Superfluid helium climbs container walls defying classical fluid dynamics laws",
    "Telescopes acting as time machines reveal cosmic events billions years",
    "The human microbiome comprises trillions of symbiotic bacteria assisting digestion",
    "Nuclear fusion requires extreme temperatures and pressures found inside stellar",
    "Particle accelerators smash subatomic nuclei to discover novel fundamental particles",
    "The event horizon marks the boundary of no return around",
    "Hemoglobin binds oxygen reversibly to transport vital fuel across tissues",
    "Paleoclimatologists extract ancient ice cores to reconstruct prehistoric atmospheric compositions",
    "Synthetic polymers revolutionized industrial materials through versatile chemical carbon backbones",
    "Crystallography uses X-ray diffraction patterns to map atomic protein structures",
    "Endosymbiosis explains how primitive eukaryotic cells engulfed ancestral energy producing",
    "The heliosphere shields our solar system from intense galactic cosmic",
    "Solar eclipses occur when the moon passes directly in front",
    "Dark matter does not interact with light yet exerts powerful",
    "The strong nuclear force binds quarks together inside protons and",
    "Quantum tunneling allows particles to cross barriers higher than kinetic",
    "CRISPR technology enables precise editing of genetic sequences inside living",
    "Hydrothermal vents support chemosynthetic ecosystems completely independent of solar energy",
    "The speed of light in vacuum is exactly constant for",
    "Scientific inquiry relies on reproducible empirical evidence to falsify hypotheses"
  ],
  "hard": [
    "Every action has an equal and opposite reaction throughout the entire physical universe as formulated by classical mechanics",
    "The expansion of the cosmos accelerates due to the mysterious repulsive pressure exerted by pervasive dark energy",
    "General relativity demonstrates that massive celestial objects warp the fabric of spacetime creating the phenomenon we experience as gravity",
    "Mitochondria generate adenosine triphosphate through complex chemical chemiosmotic electron transport chains embedded across inner mitochondrial membranes",
    "Radioactive decay provides an extraordinarily reliable geological clock for determining the precise numerical age of ancient planetary rocks",
    "Look deep into nature and then you will understand everything about human purpose and physical reality much better",
    "The quantum wave function describes the probabilistic distribution of finding a subatomic particle in particular state upon measurement",
    "Photosynthesis in terrestrial plants and marine phytoplankton absorbs solar photons to split water molecules releasing gaseous oxygen into atmosphere",
    "The James Webb space telescope captures infrared light from early galaxies that formed merely hundreds of millions years after big",
    "Black holes represent regions of spacetime where gravitational collapse produces infinite density enclosed within an inescapable light trapping event horizon",
    "The double slit experiment demonstrates that fundamental particles exhibit both localized particle behavior and continuous wave interference depending on observation",
    "DNA replication proceeds with astonishing fidelity thanks to molecular proofreading enzymes that detect and excise mismatched nucleotide base pairs",
    "Plate tectonics drives continental drift through convection currents circulating slowly within the semi molten mantle beneath brittle lithospheric plates",
    "Massive stars end their lifecycles in catastrophic supernova explosions dispersing forged heavy elements like iron gold and uranium into cosmos",
    "Entropy serves as the arrow of time dictating that isolated thermodynamic systems evolve irreversibly toward states of maximum disorder",
    "The human immune system distinguishes self from non self antigens through sophisticated signaling between T cells B cells and antibodies",
    "Cosmic inflation posits that the infant universe underwent an exponential metric expansion within a tiny fraction of second following singularity",
    "Quantum entanglement demonstrates that measurements performed on one particle instantaneously correlate with another regardless of distance separating them across universe",
    "The magnetic field generated by geodynamo processes in the liquid outer core protects terrestrial biology from deadly solar plasma winds",
    "Synthetic biology engineers novel metabolic pathways inside bacterial chassis to manufacture sustainable fuels medicines and biodegradable polymers at industrial scale",
    "Neutron stars pack the mass of our entire sun into sphere roughly twenty kilometers across creating unfathomable matter densities",
    "The discovery of gravitational waves produced by colliding black holes confirmed one of the final untested predictions of Einstein relativity",
    "Cellular senescence prevents damaged cells from proliferating into malignant tumors yet contributes to tissue degradation and chronic inflammation during aging",
    "Spectroscopy allows astrophysicists to determine the precise chemical composition temperature density and velocity of distant stars through absorption lines",
    "The standard model of particle physics successfully unifies electromagnetic weak and strong nuclear forces through fundamental gauge bosons and fermions",
    "Bioluminescent chemical reactions convert chemical luciferin into cold emission light with nearly one hundred percent quantum efficiency inside deep creatures",
    "Thermal equilibrium occurs when two physical bodies in contact cease exchanging heat because their thermodynamic temperatures have equalized completely",
    "Exoplanet atmospheric characterization searches for chemical biosignatures like simultaneous presence of methane and oxygen indicating potential extraterrestrial biological activity",
    "Paleontological fossil records reveal that five catastrophic mass extinction events have drastically reshaped biodiversity across geological planetary history",
    "Understanding the fundamental laws of nature liberates human curiosity from superstition and illuminates our humble place among the stars"
  ]
};

export async function seed() {
  return await upsertCategoryAndSentences(category, sentences);
}

if (process.argv[1]?.endsWith('science.mjs')) {
  seed().catch(console.error);
}
