import { upsertCategoryAndSentences } from './seed-helper.mjs';

export const category = {
  "slug": "space",
  "label": "Space Exploration",
  "icon": "🚀",
  "description": "Rockets, Mars colonies, cosmic nebulae, and deep space voyages",
  "display_order": 16
};

export const sentences = {
  "easy": [
    "Rockets blast past clouds",
    "Mars has red dust",
    "Saturn rings spin slowly",
    "Astronauts float in orbit",
    "Telescopes gaze into infinity",
    "The countdown has started",
    "Engines ignite with roar",
    "Shuttle reaches escape velocity",
    "Spacecraft enters lunar orbit",
    "Lander touches dusty surface",
    "Rover gathers rock samples",
    "Spacewalk outside space station",
    "Solar arrays deploy smoothly",
    "Cosmonauts view blue planet",
    "Earth looks so fragile",
    "Orbiting planet every hour",
    "Satellites relay global communications",
    "Probes explore deep planets",
    "Pluto holds frozen mountains",
    "Jupiter storms swirl endlessly",
    "launch the interstellar capsule",
    "interstellar capsule launch deep space",
    "capsule brings interstellar deep space",
    "Always launch interstellar capsule",
    "Every capsule can launch",
    "dock the cosmic thruster",
    "cosmic thruster dock lunar mission",
    "thruster brings cosmic lunar mission",
    "Always dock cosmic thruster",
    "Every thruster can dock",
    "propel the orbital payload",
    "orbital payload propel orbital science",
    "payload brings orbital orbital science",
    "Always propel orbital payload",
    "Every payload can propel",
    "navigate the lunar orbit",
    "lunar orbit navigate rocket propulsion",
    "orbit brings lunar rocket propulsion",
    "Always navigate lunar orbit",
    "Every orbit can navigate",
    "explore the suborbital trajectory",
    "suborbital trajectory explore cosmic frontier",
    "trajectory brings suborbital cosmic frontier",
    "Always explore suborbital trajectory",
    "Every trajectory can explore",
    "deploy the extraterrestrial telescope",
    "extraterrestrial telescope deploy interplanetary voyage",
    "telescope brings extraterrestrial interplanetary voyage",
    "Always deploy extraterrestrial telescope",
    "Every telescope can deploy",
    "reenter the celestial crater",
    "celestial crater reenter deep space",
    "crater brings celestial deep space",
    "Always reenter celestial crater",
    "Every crater can reenter",
    "orbit the boundless lander",
    "boundless lander orbit lunar mission",
    "lander brings boundless lunar mission",
    "Always orbit boundless lander",
    "Every lander can orbit",
    "telemetry the weightless nebula",
    "weightless nebula telemetry orbital science",
    "nebula brings weightless orbital science",
    "Always telemetry weightless nebula",
    "Every nebula can telemetry",
    "calibrate the stellar cosmonaut",
    "stellar cosmonaut calibrate rocket propulsion",
    "cosmonaut brings stellar rocket propulsion",
    "Always calibrate stellar cosmonaut",
    "Every cosmonaut can calibrate",
    "interstellar capsule launch cosmic frontier",
    "capsule brings interstellar cosmic frontier",
    "cosmic thruster dock interplanetary voyage",
    "thruster brings cosmic interplanetary voyage",
    "orbital payload propel deep space",
    "payload brings orbital deep space",
    "lunar orbit navigate lunar mission",
    "orbit brings lunar lunar mission",
    "suborbital trajectory explore orbital science",
    "trajectory brings suborbital orbital science",
    "extraterrestrial telescope deploy rocket propulsion",
    "telescope brings extraterrestrial rocket propulsion",
    "celestial crater reenter cosmic frontier",
    "crater brings celestial cosmic frontier",
    "boundless lander orbit interplanetary voyage",
    "lander brings boundless interplanetary voyage",
    "weightless nebula telemetry deep space",
    "nebula brings weightless deep space",
    "stellar cosmonaut calibrate lunar mission",
    "cosmonaut brings stellar lunar mission",
    "interstellar capsule launch orbital science",
    "capsule brings interstellar orbital science",
    "cosmic thruster dock rocket propulsion",
    "thruster brings cosmic rocket propulsion",
    "orbital payload propel cosmic frontier",
    "payload brings orbital cosmic frontier",
    "lunar orbit navigate interplanetary voyage",
    "orbit brings lunar interplanetary voyage",
    "suborbital trajectory explore deep space",
    "trajectory brings suborbital deep space"
  ],
  "normal": [
    "One small step for man one giant leap mankind",
    "Robotic rovers explore dry ancient lake riverbeds on Mars",
    "The James Webb telescope peers into the early infant cosmos",
    "Gravitational slingshots accelerate scientific probes toward outer distant gas giants",
    "Space stations orbit Earth sixteen times every single calendar day",
    "Supernovae seed the universe with heavy essential chemical life elements",
    "Astronauts experience profound cognitive transformation known as the overview effect",
    "Ion thrusters provide efficient continuous propulsion for interplanetary deep missions",
    "Cryogenic rocket engines burn liquid hydrogen and liquid oxygen violently",
    "Searching for extraterrestrial biosignatures on icy moons like Europa Enceladus",
    "The interstellar capsule will greatly launch our deep space today",
    "Every interstellar capsule must launch carefully across the entire deep",
    "Learning how to launch interstellar capsule inspires deep deep space",
    "Our dedicated team will launch the interstellar capsule for deep",
    "The cosmic thruster will greatly dock our lunar mission today",
    "Every cosmic thruster must dock carefully across the entire lunar",
    "Learning how to dock cosmic thruster inspires deep lunar mission",
    "Our dedicated team will dock the cosmic thruster for lunar",
    "The orbital payload will greatly propel our orbital science today",
    "Every orbital payload must propel carefully across the entire orbital",
    "Learning how to propel orbital payload inspires deep orbital science",
    "Our dedicated team will propel the orbital payload for orbital",
    "The lunar orbit will greatly navigate our rocket propulsion today",
    "Every lunar orbit must navigate carefully across the entire rocket",
    "Learning how to navigate lunar orbit inspires deep rocket propulsion",
    "Our dedicated team will navigate the lunar orbit for rocket",
    "The suborbital trajectory will greatly explore our cosmic frontier today",
    "Every suborbital trajectory must explore carefully across the entire cosmic",
    "Learning how to explore suborbital trajectory inspires deep cosmic frontier",
    "Our dedicated team will explore the suborbital trajectory for cosmic",
    "The extraterrestrial telescope will greatly deploy our interplanetary voyage today",
    "Every extraterrestrial telescope must deploy carefully across the entire interplanetary",
    "Learning how to deploy extraterrestrial telescope inspires deep interplanetary voyage",
    "Our dedicated team will deploy the extraterrestrial telescope for interplanetary",
    "The celestial crater will greatly reenter our deep space today",
    "Every celestial crater must reenter carefully across the entire deep",
    "Learning how to reenter celestial crater inspires deep deep space",
    "Our dedicated team will reenter the celestial crater for deep",
    "The boundless lander will greatly orbit our lunar mission today",
    "Every boundless lander must orbit carefully across the entire lunar",
    "Learning how to orbit boundless lander inspires deep lunar mission",
    "Our dedicated team will orbit the boundless lander for lunar",
    "The weightless nebula will greatly telemetry our orbital science today",
    "Every weightless nebula must telemetry carefully across the entire orbital",
    "Learning how to telemetry weightless nebula inspires deep orbital science",
    "Our dedicated team will telemetry the weightless nebula for orbital",
    "The stellar cosmonaut will greatly calibrate our rocket propulsion today",
    "Every stellar cosmonaut must calibrate carefully across the entire rocket",
    "Learning how to calibrate stellar cosmonaut inspires deep rocket propulsion",
    "Our dedicated team will calibrate the stellar cosmonaut for rocket",
    "The interstellar capsule will greatly launch our cosmic frontier today",
    "Every interstellar capsule must launch carefully across the entire cosmic",
    "Learning how to launch interstellar capsule inspires deep cosmic frontier",
    "Our dedicated team will launch the interstellar capsule for cosmic",
    "The cosmic thruster will greatly dock our interplanetary voyage today",
    "Every cosmic thruster must dock carefully across the entire interplanetary",
    "Learning how to dock cosmic thruster inspires deep interplanetary voyage",
    "Our dedicated team will dock the cosmic thruster for interplanetary",
    "The orbital payload will greatly propel our deep space today",
    "Every orbital payload must propel carefully across the entire deep",
    "Learning how to propel orbital payload inspires deep deep space",
    "Our dedicated team will propel the orbital payload for deep",
    "The lunar orbit will greatly navigate our lunar mission today",
    "Every lunar orbit must navigate carefully across the entire lunar",
    "Learning how to navigate lunar orbit inspires deep lunar mission",
    "Our dedicated team will navigate the lunar orbit for lunar",
    "The suborbital trajectory will greatly explore our orbital science today",
    "Every suborbital trajectory must explore carefully across the entire orbital",
    "Learning how to explore suborbital trajectory inspires deep orbital science",
    "Our dedicated team will explore the suborbital trajectory for orbital"
  ],
  "hard": [
    "Somewhere something incredible is waiting to be known in the boundless depths of space and silent cosmic reaches",
    "Voyager one carries a golden record containing greeting sounds and pictures from our home planet into interstellar darkness",
    "Reentering planetary atmosphere generates extreme thermal plasma friction requiring sophisticated ceramic heat shields to survive unharmed",
    "Colonizing distant worlds demands closed loop life support systems capable of recycling air water and nutrients indefinitely without resupply",
    "Cosmic radiation beyond Earth protective magnetosphere poses long term biological challenges for deep space explorers venturing toward Mars",
    "When confronting complex challenges in deep space one must launch every interstellar capsule with rigorous discipline and patient determination",
    "The integration of interstellar capsule within modern deep space enables practitioners to launch critical milestones without sacrificing enduring quality",
    "Throughout the evolution of deep space master practitioners learned to launch the most intricate interstellar capsule through persistent dedicated effort",
    "Developing comprehensive understanding of deep space demands that professionals launch each interstellar capsule with profound analytical rigor and integrity",
    "When confronting complex challenges in lunar mission one must dock every cosmic thruster with rigorous discipline and patient determination",
    "The integration of cosmic thruster within modern lunar mission enables practitioners to dock critical milestones without sacrificing enduring quality",
    "Throughout the evolution of lunar mission master practitioners learned to dock the most intricate cosmic thruster through persistent dedicated effort",
    "Developing comprehensive understanding of lunar mission demands that professionals dock each cosmic thruster with profound analytical rigor and integrity",
    "When confronting complex challenges in orbital science one must propel every orbital payload with rigorous discipline and patient determination",
    "The integration of orbital payload within modern orbital science enables practitioners to propel critical milestones without sacrificing enduring quality",
    "Throughout the evolution of orbital science master practitioners learned to propel the most intricate orbital payload through persistent dedicated effort",
    "Developing comprehensive understanding of orbital science demands that professionals propel each orbital payload with profound analytical rigor and integrity",
    "When confronting complex challenges in rocket propulsion one must navigate every lunar orbit with rigorous discipline and patient determination",
    "The integration of lunar orbit within modern rocket propulsion enables practitioners to navigate critical milestones without sacrificing enduring quality",
    "Throughout the evolution of rocket propulsion master practitioners learned to navigate the most intricate lunar orbit through persistent dedicated effort",
    "Developing comprehensive understanding of rocket propulsion demands that professionals navigate each lunar orbit with profound analytical rigor and integrity",
    "When confronting complex challenges in cosmic frontier one must explore every suborbital trajectory with rigorous discipline and patient determination",
    "The integration of suborbital trajectory within modern cosmic frontier enables practitioners to explore critical milestones without sacrificing enduring quality",
    "Throughout the evolution of cosmic frontier master practitioners learned to explore the most intricate suborbital trajectory through persistent dedicated effort",
    "Developing comprehensive understanding of cosmic frontier demands that professionals explore each suborbital trajectory with profound analytical rigor and integrity",
    "When confronting complex challenges in interplanetary voyage one must deploy every extraterrestrial telescope with rigorous discipline and patient determination",
    "The integration of extraterrestrial telescope within modern interplanetary voyage enables practitioners to deploy critical milestones without sacrificing enduring quality",
    "Throughout the evolution of interplanetary voyage master practitioners learned to deploy the most intricate extraterrestrial telescope through persistent dedicated effort",
    "Developing comprehensive understanding of interplanetary voyage demands that professionals deploy each extraterrestrial telescope with profound analytical rigor and integrity",
    "When confronting complex challenges in deep space one must reenter every celestial crater with rigorous discipline and patient determination"
  ]
};

export async function seed() {
  return await upsertCategoryAndSentences(category, sentences);
}

if (process.argv[1]?.endsWith('space.mjs')) {
  seed().catch(console.error);
}
