import { upsertCategoryAndSentences } from './seed-helper.mjs';

export const category = {
  "slug": "sports",
  "label": "Sports & Athletics",
  "icon": "🏆",
  "description": "Championship grit, marathon endurance, and athletic glory",
  "display_order": 19
};

export const sentences = {
  "easy": [
    "Practice beats pure talent",
    "Champions train when tired",
    "Pass ball to teammate",
    "Sprint past finish line",
    "Never give up hope",
    "Defense wins big games",
    "Score winning goal now",
    "Dribble past defenders quickly",
    "Sink free throw shot",
    "Hit home run ball",
    "Serve ace tennis ball",
    "Swim final freestyle lap",
    "Pedal uphill on bike",
    "Vault over high bar",
    "Stick gymnastics dismount landing",
    "Boxer lands decisive punch",
    "Run marathon through rain",
    "Lift heavy iron barbell",
    "Stretch muscles after workout",
    "Hydrate with cool water",
    "sprint the athletic stadium",
    "athletic stadium sprint marathon grit",
    "stadium brings athletic marathon grit",
    "Always sprint athletic stadium",
    "Every stadium can sprint",
    "triumph the unyielding medal",
    "unyielding medal triumph championship match",
    "medal brings unyielding championship match",
    "Always triumph unyielding medal",
    "Every medal can triumph",
    "endure the vigorous trophy",
    "vigorous trophy endure athletic training",
    "trophy brings vigorous athletic training",
    "Always endure vigorous trophy",
    "Every trophy can endure",
    "rebound the championship marathon",
    "championship marathon rebound stadium glory",
    "marathon brings championship stadium glory",
    "Always rebound championship marathon",
    "Every marathon can rebound",
    "outperform the tenacious coach",
    "tenacious coach outperform defensive rally",
    "coach brings tenacious defensive rally",
    "Always outperform tenacious coach",
    "Every coach can outperform",
    "train the swift defense",
    "swift defense train olympic sprint",
    "defense brings swift olympic sprint",
    "Always train swift defense",
    "Every defense can train",
    "compete the agile sprint",
    "agile sprint compete marathon grit",
    "sprint brings agile marathon grit",
    "Always compete agile sprint",
    "Every sprint can compete",
    "overcome the resilient jersey",
    "resilient jersey overcome championship match",
    "jersey brings resilient championship match",
    "Always overcome resilient jersey",
    "Every jersey can overcome",
    "persevere the focused whistle",
    "focused whistle persevere athletic training",
    "whistle brings focused athletic training",
    "Always persevere focused whistle",
    "Every whistle can persevere",
    "dominate the tireless athlete",
    "tireless athlete dominate stadium glory",
    "athlete brings tireless stadium glory",
    "Always dominate tireless athlete",
    "Every athlete can dominate",
    "athletic stadium sprint defensive rally",
    "stadium brings athletic defensive rally",
    "unyielding medal triumph olympic sprint",
    "medal brings unyielding olympic sprint",
    "vigorous trophy endure marathon grit",
    "trophy brings vigorous marathon grit",
    "championship marathon rebound championship match",
    "marathon brings championship championship match",
    "tenacious coach outperform athletic training",
    "coach brings tenacious athletic training",
    "swift defense train stadium glory",
    "defense brings swift stadium glory",
    "agile sprint compete defensive rally",
    "sprint brings agile defensive rally",
    "resilient jersey overcome olympic sprint",
    "jersey brings resilient olympic sprint",
    "focused whistle persevere marathon grit",
    "whistle brings focused marathon grit",
    "tireless athlete dominate championship match",
    "athlete brings tireless championship match",
    "athletic stadium sprint athletic training",
    "stadium brings athletic athletic training",
    "unyielding medal triumph stadium glory",
    "medal brings unyielding stadium glory",
    "vigorous trophy endure defensive rally",
    "trophy brings vigorous defensive rally",
    "championship marathon rebound olympic sprint",
    "marathon brings championship olympic sprint",
    "tenacious coach outperform marathon grit",
    "coach brings tenacious marathon grit"
  ],
  "normal": [
    "You miss one hundred percent of shots you never take",
    "Hard work beats talent when talent fails to work hard",
    "Gold medals are forged during early morning lonely track workouts",
    "Teamwork divides the effort and multiplies the eventual championship success",
    "Marathon runners hit the wall around mile twenty with fatigue",
    "Great athletes maintain composure under high pressure championship stadium moments",
    "Proper nutrition and restorative sleep accelerate muscular recovery between matches",
    "Mental resilience allows contenders to overcome grueling setbacks and injuries",
    "A disciplined game plan dismantles unpredictable opponents on the court",
    "Sportsmanship honors competitors while pursuing victory with fierce relentless intensity",
    "The athletic stadium will greatly sprint our marathon grit today",
    "Every athletic stadium must sprint carefully across the entire marathon",
    "Learning how to sprint athletic stadium inspires deep marathon grit",
    "Our dedicated team will sprint the athletic stadium for marathon",
    "The unyielding medal will greatly triumph our championship match today",
    "Every unyielding medal must triumph carefully across the entire championship",
    "Learning how to triumph unyielding medal inspires deep championship match",
    "Our dedicated team will triumph the unyielding medal for championship",
    "The vigorous trophy will greatly endure our athletic training today",
    "Every vigorous trophy must endure carefully across the entire athletic",
    "Learning how to endure vigorous trophy inspires deep athletic training",
    "Our dedicated team will endure the vigorous trophy for athletic",
    "The championship marathon will greatly rebound our stadium glory today",
    "Every championship marathon must rebound carefully across the entire stadium",
    "Learning how to rebound championship marathon inspires deep stadium glory",
    "Our dedicated team will rebound the championship marathon for stadium",
    "The tenacious coach will greatly outperform our defensive rally today",
    "Every tenacious coach must outperform carefully across the entire defensive",
    "Learning how to outperform tenacious coach inspires deep defensive rally",
    "Our dedicated team will outperform the tenacious coach for defensive",
    "The swift defense will greatly train our olympic sprint today",
    "Every swift defense must train carefully across the entire olympic",
    "Learning how to train swift defense inspires deep olympic sprint",
    "Our dedicated team will train the swift defense for olympic",
    "The agile sprint will greatly compete our marathon grit today",
    "Every agile sprint must compete carefully across the entire marathon",
    "Learning how to compete agile sprint inspires deep marathon grit",
    "Our dedicated team will compete the agile sprint for marathon",
    "The resilient jersey will greatly overcome our championship match today",
    "Every resilient jersey must overcome carefully across the entire championship",
    "Learning how to overcome resilient jersey inspires deep championship match",
    "Our dedicated team will overcome the resilient jersey for championship",
    "The focused whistle will greatly persevere our athletic training today",
    "Every focused whistle must persevere carefully across the entire athletic",
    "Learning how to persevere focused whistle inspires deep athletic training",
    "Our dedicated team will persevere the focused whistle for athletic",
    "The tireless athlete will greatly dominate our stadium glory today",
    "Every tireless athlete must dominate carefully across the entire stadium",
    "Learning how to dominate tireless athlete inspires deep stadium glory",
    "Our dedicated team will dominate the tireless athlete for stadium",
    "The athletic stadium will greatly sprint our defensive rally today",
    "Every athletic stadium must sprint carefully across the entire defensive",
    "Learning how to sprint athletic stadium inspires deep defensive rally",
    "Our dedicated team will sprint the athletic stadium for defensive",
    "The unyielding medal will greatly triumph our olympic sprint today",
    "Every unyielding medal must triumph carefully across the entire olympic",
    "Learning how to triumph unyielding medal inspires deep olympic sprint",
    "Our dedicated team will triumph the unyielding medal for olympic",
    "The vigorous trophy will greatly endure our marathon grit today",
    "Every vigorous trophy must endure carefully across the entire marathon",
    "Learning how to endure vigorous trophy inspires deep marathon grit",
    "Our dedicated team will endure the vigorous trophy for marathon",
    "The championship marathon will greatly rebound our championship match today",
    "Every championship marathon must rebound carefully across the entire championship",
    "Learning how to rebound championship marathon inspires deep championship match",
    "Our dedicated team will rebound the championship marathon for championship",
    "The tenacious coach will greatly outperform our athletic training today",
    "Every tenacious coach must outperform carefully across the entire athletic",
    "Learning how to outperform tenacious coach inspires deep athletic training",
    "Our dedicated team will outperform the tenacious coach for athletic"
  ],
  "hard": [
    "I have failed over and over and over again in my athletic career and that is why succeed completely",
    "The thrill of victory and the agony of defeat define the emotional drama of competitive athletics across the globe",
    "Muscles scream for rest during final sprints yet unshakeable mental fortitude pushes runners across the distant finish line",
    "Recovery nutrition adequate sleep and mental visualization are just as crucial as physical drills performed on practice field",
    "A championship team relies on selflessness where every player prioritizes collective victory above individual statistical accolades and praise",
    "When confronting complex challenges in marathon grit one must sprint every athletic stadium with rigorous discipline and patient determination",
    "The integration of athletic stadium within modern marathon grit enables practitioners to sprint critical milestones without sacrificing enduring quality",
    "Throughout the evolution of marathon grit master practitioners learned to sprint the most intricate athletic stadium through persistent dedicated effort",
    "Developing comprehensive understanding of marathon grit demands that professionals sprint each athletic stadium with profound analytical rigor and integrity",
    "When confronting complex challenges in championship match one must triumph every unyielding medal with rigorous discipline and patient determination",
    "The integration of unyielding medal within modern championship match enables practitioners to triumph critical milestones without sacrificing enduring quality",
    "Throughout the evolution of championship match master practitioners learned to triumph the most intricate unyielding medal through persistent dedicated effort",
    "Developing comprehensive understanding of championship match demands that professionals triumph each unyielding medal with profound analytical rigor and integrity",
    "When confronting complex challenges in athletic training one must endure every vigorous trophy with rigorous discipline and patient determination",
    "The integration of vigorous trophy within modern athletic training enables practitioners to endure critical milestones without sacrificing enduring quality",
    "Throughout the evolution of athletic training master practitioners learned to endure the most intricate vigorous trophy through persistent dedicated effort",
    "Developing comprehensive understanding of athletic training demands that professionals endure each vigorous trophy with profound analytical rigor and integrity",
    "When confronting complex challenges in stadium glory one must rebound every championship marathon with rigorous discipline and patient determination",
    "The integration of championship marathon within modern stadium glory enables practitioners to rebound critical milestones without sacrificing enduring quality",
    "Throughout the evolution of stadium glory master practitioners learned to rebound the most intricate championship marathon through persistent dedicated effort",
    "Developing comprehensive understanding of stadium glory demands that professionals rebound each championship marathon with profound analytical rigor and integrity",
    "When confronting complex challenges in defensive rally one must outperform every tenacious coach with rigorous discipline and patient determination",
    "The integration of tenacious coach within modern defensive rally enables practitioners to outperform critical milestones without sacrificing enduring quality",
    "Throughout the evolution of defensive rally master practitioners learned to outperform the most intricate tenacious coach through persistent dedicated effort",
    "Developing comprehensive understanding of defensive rally demands that professionals outperform each tenacious coach with profound analytical rigor and integrity",
    "When confronting complex challenges in olympic sprint one must train every swift defense with rigorous discipline and patient determination",
    "The integration of swift defense within modern olympic sprint enables practitioners to train critical milestones without sacrificing enduring quality",
    "Throughout the evolution of olympic sprint master practitioners learned to train the most intricate swift defense through persistent dedicated effort",
    "Developing comprehensive understanding of olympic sprint demands that professionals train each swift defense with profound analytical rigor and integrity",
    "When confronting complex challenges in marathon grit one must compete every agile sprint with rigorous discipline and patient determination"
  ]
};

export async function seed() {
  return await upsertCategoryAndSentences(category, sentences);
}

if (process.argv[1]?.endsWith('sports.mjs')) {
  seed().catch(console.error);
}
