import { upsertCategoryAndSentences } from './seed-helper.mjs';

export const category = {
  "slug": "travel",
  "label": "Travel & Wanderlust",
  "icon": "✈️",
  "description": "Global expeditions, scenic cities, passports, and journeys",
  "display_order": 20
};

export const sentences = {
  "easy": [
    "Pack bags for adventure",
    "Explore ancient cobblestone streets",
    "Sunsets over tropical beaches",
    "Travel opens your mind",
    "Passports collect colorful stamps",
    "Wander off beaten path",
    "Board the morning flight",
    "Climb high mountain trails",
    "Sail across sapphire waters",
    "Discover quiet hidden cafes",
    "Photograph picturesque historic plazas",
    "Taste street food dishes",
    "Meet friendly local people",
    "Hear foreign language greetings",
    "Watch sunrise over temples",
    "Walk through bustling bazaars",
    "Camp under starry skies",
    "Ride scenic alpine trains",
    "Marvel at towering glaciers",
    "Cherish lifelong travel memories",
    "explore the panoramic journey",
    "panoramic journey explore wanderlust voyage",
    "journey brings panoramic wanderlust voyage",
    "Always explore panoramic journey",
    "Every journey can explore",
    "discover the exotic passport",
    "exotic passport discover global travel",
    "passport brings exotic global travel",
    "Always discover exotic passport",
    "Every passport can discover",
    "traverse the breathtaking voyage",
    "breathtaking voyage traverse mountain expedition",
    "voyage brings breathtaking mountain expedition",
    "Always traverse breathtaking voyage",
    "Every voyage can traverse",
    "navigate the scenic destination",
    "scenic destination navigate scenic getaway",
    "destination brings scenic scenic getaway",
    "Always navigate scenic destination",
    "Every destination can navigate",
    "wander the adventurous itinerary",
    "adventurous itinerary wander cultural immersion",
    "itinerary brings adventurous cultural immersion",
    "Always wander adventurous itinerary",
    "Every itinerary can wander",
    "uncover the picturesque expedition",
    "picturesque expedition uncover nomadic journey",
    "expedition brings picturesque nomadic journey",
    "Always uncover picturesque expedition",
    "Every expedition can uncover",
    "embark the ancient harbor",
    "ancient harbor embark wanderlust voyage",
    "harbor brings ancient wanderlust voyage",
    "Always embark ancient harbor",
    "Every harbor can embark",
    "journey the remote glacier",
    "remote glacier journey global travel",
    "glacier brings remote global travel",
    "Always journey remote glacier",
    "Every glacier can journey",
    "document the tranquil trail",
    "tranquil trail document mountain expedition",
    "trail brings tranquil mountain expedition",
    "Always document tranquil trail",
    "Every trail can document",
    "witness the coastal horizon",
    "coastal horizon witness scenic getaway",
    "horizon brings coastal scenic getaway",
    "Always witness coastal horizon",
    "Every horizon can witness",
    "panoramic journey explore cultural immersion",
    "journey brings panoramic cultural immersion",
    "exotic passport discover nomadic journey",
    "passport brings exotic nomadic journey",
    "breathtaking voyage traverse wanderlust voyage",
    "voyage brings breathtaking wanderlust voyage",
    "scenic destination navigate global travel",
    "destination brings scenic global travel",
    "adventurous itinerary wander mountain expedition",
    "itinerary brings adventurous mountain expedition",
    "picturesque expedition uncover scenic getaway",
    "expedition brings picturesque scenic getaway",
    "ancient harbor embark cultural immersion",
    "harbor brings ancient cultural immersion",
    "remote glacier journey nomadic journey",
    "glacier brings remote nomadic journey",
    "tranquil trail document wanderlust voyage",
    "trail brings tranquil wanderlust voyage",
    "coastal horizon witness global travel",
    "horizon brings coastal global travel",
    "panoramic journey explore mountain expedition",
    "journey brings panoramic mountain expedition",
    "exotic passport discover scenic getaway",
    "passport brings exotic scenic getaway",
    "breathtaking voyage traverse cultural immersion",
    "voyage brings breathtaking cultural immersion",
    "scenic destination navigate nomadic journey",
    "destination brings scenic nomadic journey",
    "adventurous itinerary wander wanderlust voyage",
    "itinerary brings adventurous wanderlust voyage"
  ],
  "normal": [
    "The world is an open book for adventurous lifelong travelers",
    "Boarding a night train into unfamiliar mountain territory brings excitement",
    "Local street food night markets reveal the true culinary soul",
    "Getting lost in Venice leads to enchanting quiet forgotten canals",
    "Catching sunrise over mist covered Buddhist temple spires inspires awe",
    "Memories gathered while traveling outlive any material possessions you purchase",
    "Navigating bustling foreign transit systems builds confidence and personal independence",
    "A scenic coastal road trip offers spontaneous detour discoveries daily",
    "Immersing yourself in local customs deepens cross cultural empathy worldwide",
    "Traveling with an open heart transforms ordinary encounters into friendships",
    "The panoramic journey will greatly explore our wanderlust voyage today",
    "Every panoramic journey must explore carefully across the entire wanderlust",
    "Learning how to explore panoramic journey inspires deep wanderlust voyage",
    "Our dedicated team will explore the panoramic journey for wanderlust",
    "The exotic passport will greatly discover our global travel today",
    "Every exotic passport must discover carefully across the entire global",
    "Learning how to discover exotic passport inspires deep global travel",
    "Our dedicated team will discover the exotic passport for global",
    "The breathtaking voyage will greatly traverse our mountain expedition today",
    "Every breathtaking voyage must traverse carefully across the entire mountain",
    "Learning how to traverse breathtaking voyage inspires deep mountain expedition",
    "Our dedicated team will traverse the breathtaking voyage for mountain",
    "The scenic destination will greatly navigate our scenic getaway today",
    "Every scenic destination must navigate carefully across the entire scenic",
    "Learning how to navigate scenic destination inspires deep scenic getaway",
    "Our dedicated team will navigate the scenic destination for scenic",
    "The adventurous itinerary will greatly wander our cultural immersion today",
    "Every adventurous itinerary must wander carefully across the entire cultural",
    "Learning how to wander adventurous itinerary inspires deep cultural immersion",
    "Our dedicated team will wander the adventurous itinerary for cultural",
    "The picturesque expedition will greatly uncover our nomadic journey today",
    "Every picturesque expedition must uncover carefully across the entire nomadic",
    "Learning how to uncover picturesque expedition inspires deep nomadic journey",
    "Our dedicated team will uncover the picturesque expedition for nomadic",
    "The ancient harbor will greatly embark our wanderlust voyage today",
    "Every ancient harbor must embark carefully across the entire wanderlust",
    "Learning how to embark ancient harbor inspires deep wanderlust voyage",
    "Our dedicated team will embark the ancient harbor for wanderlust",
    "The remote glacier will greatly journey our global travel today",
    "Every remote glacier must journey carefully across the entire global",
    "Learning how to journey remote glacier inspires deep global travel",
    "Our dedicated team will journey the remote glacier for global",
    "The tranquil trail will greatly document our mountain expedition today",
    "Every tranquil trail must document carefully across the entire mountain",
    "Learning how to document tranquil trail inspires deep mountain expedition",
    "Our dedicated team will document the tranquil trail for mountain",
    "The coastal horizon will greatly witness our scenic getaway today",
    "Every coastal horizon must witness carefully across the entire scenic",
    "Learning how to witness coastal horizon inspires deep scenic getaway",
    "Our dedicated team will witness the coastal horizon for scenic",
    "The panoramic journey will greatly explore our cultural immersion today",
    "Every panoramic journey must explore carefully across the entire cultural",
    "Learning how to explore panoramic journey inspires deep cultural immersion",
    "Our dedicated team will explore the panoramic journey for cultural",
    "The exotic passport will greatly discover our nomadic journey today",
    "Every exotic passport must discover carefully across the entire nomadic",
    "Learning how to discover exotic passport inspires deep nomadic journey",
    "Our dedicated team will discover the exotic passport for nomadic",
    "The breathtaking voyage will greatly traverse our wanderlust voyage today",
    "Every breathtaking voyage must traverse carefully across the entire wanderlust",
    "Learning how to traverse breathtaking voyage inspires deep wanderlust voyage",
    "Our dedicated team will traverse the breathtaking voyage for wanderlust",
    "The scenic destination will greatly navigate our global travel today",
    "Every scenic destination must navigate carefully across the entire global",
    "Learning how to navigate scenic destination inspires deep global travel",
    "Our dedicated team will navigate the scenic destination for global",
    "The adventurous itinerary will greatly wander our mountain expedition today",
    "Every adventurous itinerary must wander carefully across the entire mountain",
    "Learning how to wander adventurous itinerary inspires deep mountain expedition",
    "Our dedicated team will wander the adventurous itinerary for mountain"
  ],
  "hard": [
    "Not until we are lost do we begin to understand ourselves and the vast beautiful world around us",
    "Backpacking across foreign continents teaches resilience adaptability and gratitude for everyday comforts often taken for granted at home",
    "The smell of fresh morning espresso on a Parisian boulevard awakens memories of carefree European summers spent wandering cobblestone streets",
    "Traveling reminds us that beneath different languages and traditions all humans share similar hopes fears and universal desires for peace",
    "Standing before towering glacial fjords makes one realize how small and fragile our footprint truly is upon ancient majestic Earth",
    "When confronting complex challenges in wanderlust voyage one must explore every panoramic journey with rigorous discipline and patient determination",
    "The integration of panoramic journey within modern wanderlust voyage enables practitioners to explore critical milestones without sacrificing enduring quality",
    "Throughout the evolution of wanderlust voyage master practitioners learned to explore the most intricate panoramic journey through persistent dedicated effort",
    "Developing comprehensive understanding of wanderlust voyage demands that professionals explore each panoramic journey with profound analytical rigor and integrity",
    "When confronting complex challenges in global travel one must discover every exotic passport with rigorous discipline and patient determination",
    "The integration of exotic passport within modern global travel enables practitioners to discover critical milestones without sacrificing enduring quality",
    "Throughout the evolution of global travel master practitioners learned to discover the most intricate exotic passport through persistent dedicated effort",
    "Developing comprehensive understanding of global travel demands that professionals discover each exotic passport with profound analytical rigor and integrity",
    "When confronting complex challenges in mountain expedition one must traverse every breathtaking voyage with rigorous discipline and patient determination",
    "The integration of breathtaking voyage within modern mountain expedition enables practitioners to traverse critical milestones without sacrificing enduring quality",
    "Throughout the evolution of mountain expedition master practitioners learned to traverse the most intricate breathtaking voyage through persistent dedicated effort",
    "Developing comprehensive understanding of mountain expedition demands that professionals traverse each breathtaking voyage with profound analytical rigor and integrity",
    "When confronting complex challenges in scenic getaway one must navigate every scenic destination with rigorous discipline and patient determination",
    "The integration of scenic destination within modern scenic getaway enables practitioners to navigate critical milestones without sacrificing enduring quality",
    "Throughout the evolution of scenic getaway master practitioners learned to navigate the most intricate scenic destination through persistent dedicated effort",
    "Developing comprehensive understanding of scenic getaway demands that professionals navigate each scenic destination with profound analytical rigor and integrity",
    "When confronting complex challenges in cultural immersion one must wander every adventurous itinerary with rigorous discipline and patient determination",
    "The integration of adventurous itinerary within modern cultural immersion enables practitioners to wander critical milestones without sacrificing enduring quality",
    "Throughout the evolution of cultural immersion master practitioners learned to wander the most intricate adventurous itinerary through persistent dedicated effort",
    "Developing comprehensive understanding of cultural immersion demands that professionals wander each adventurous itinerary with profound analytical rigor and integrity",
    "When confronting complex challenges in nomadic journey one must uncover every picturesque expedition with rigorous discipline and patient determination",
    "The integration of picturesque expedition within modern nomadic journey enables practitioners to uncover critical milestones without sacrificing enduring quality",
    "Throughout the evolution of nomadic journey master practitioners learned to uncover the most intricate picturesque expedition through persistent dedicated effort",
    "Developing comprehensive understanding of nomadic journey demands that professionals uncover each picturesque expedition with profound analytical rigor and integrity",
    "When confronting complex challenges in wanderlust voyage one must embark every ancient harbor with rigorous discipline and patient determination"
  ]
};

export async function seed() {
  return await upsertCategoryAndSentences(category, sentences);
}

if (process.argv[1]?.endsWith('travel.mjs')) {
  seed().catch(console.error);
}
