import { upsertCategoryAndSentences } from './seed-helper.mjs';

export const category = {
  "slug": "wellness",
  "label": "Mindfulness & Health",
  "icon": "🧘",
  "description": "Meditation, breathing, physical vitality, and inner peace",
  "display_order": 25
};

export const sentences = {
  "easy": [
    "Inhale peace exhale tension",
    "Drink clean fresh water",
    "Sleep heals body mind",
    "Walk outside in nature",
    "Breathe deeply right now",
    "Be present this moment",
    "Notice your breathing rhythm",
    "Relax your shoulder muscles",
    "Release mental heavy clutter",
    "Practice gratitude every morning",
    "Listen to your body",
    "Stretch muscles upon waking",
    "Eat wholesome nourishing meals",
    "Drink calming herbal tea",
    "Soak in warm bath",
    "Rest in quiet stillness",
    "Let go of worries",
    "Embrace calm peaceful thoughts",
    "Smile with gentle heart",
    "Kindness starts with yourself",
    "inhale the serene breath",
    "serene breath inhale inner peace",
    "breath brings serene inner peace",
    "Always inhale serene breath",
    "Every breath can inhale",
    "restore the tranquil vitality",
    "tranquil vitality restore breathwork practice",
    "vitality brings tranquil breathwork practice",
    "Always restore tranquil vitality",
    "Every vitality can restore",
    "rejuvenate the mindful serenity",
    "mindful serenity rejuvenate mental clarity",
    "serenity brings mindful mental clarity",
    "Always rejuvenate mindful serenity",
    "Every serenity can rejuvenate",
    "center the restorative meditation",
    "restorative meditation center physical vitality",
    "meditation brings restorative physical vitality",
    "Always center restorative meditation",
    "Every meditation can center",
    "meditate the holistic balance",
    "holistic balance meditate mindful living",
    "balance brings holistic mindful living",
    "Always meditate holistic balance",
    "Every balance can meditate",
    "nourish the calming clarity",
    "calming clarity nourish restorative calm",
    "clarity brings calming restorative calm",
    "Always nourish calming clarity",
    "Every clarity can nourish",
    "unwind the grounded mindfulness",
    "grounded mindfulness unwind inner peace",
    "mindfulness brings grounded inner peace",
    "Always unwind grounded mindfulness",
    "Every mindfulness can unwind",
    "breathe the rejuvenating posture",
    "rejuvenating posture breathe breathwork practice",
    "posture brings rejuvenating breathwork practice",
    "Always breathe rejuvenating posture",
    "Every posture can breathe",
    "harmonize the peaceful nourishment",
    "peaceful nourishment harmonize mental clarity",
    "nourishment brings peaceful mental clarity",
    "Always harmonize peaceful nourishment",
    "Every nourishment can harmonize",
    "ground the vital gratitude",
    "vital gratitude ground physical vitality",
    "gratitude brings vital physical vitality",
    "Always ground vital gratitude",
    "Every gratitude can ground",
    "serene breath inhale mindful living",
    "breath brings serene mindful living",
    "tranquil vitality restore restorative calm",
    "vitality brings tranquil restorative calm",
    "mindful serenity rejuvenate inner peace",
    "serenity brings mindful inner peace",
    "restorative meditation center breathwork practice",
    "meditation brings restorative breathwork practice",
    "holistic balance meditate mental clarity",
    "balance brings holistic mental clarity",
    "calming clarity nourish physical vitality",
    "clarity brings calming physical vitality",
    "grounded mindfulness unwind mindful living",
    "mindfulness brings grounded mindful living",
    "rejuvenating posture breathe restorative calm",
    "posture brings rejuvenating restorative calm",
    "peaceful nourishment harmonize inner peace",
    "nourishment brings peaceful inner peace",
    "vital gratitude ground breathwork practice",
    "gratitude brings vital breathwork practice",
    "serene breath inhale mental clarity",
    "breath brings serene mental clarity",
    "tranquil vitality restore physical vitality",
    "vitality brings tranquil physical vitality",
    "mindful serenity rejuvenate mindful living",
    "serenity brings mindful mindful living",
    "restorative meditation center restorative calm",
    "meditation brings restorative restorative calm",
    "holistic balance meditate inner peace",
    "balance brings holistic inner peace"
  ],
  "normal": [
    "Quiet your mind and the soul will speak soft wisdom",
    "Consistent restful sleep restores physical vitality and sharp mental focus",
    "Mindfulness is paying attention on purpose without harsh critical judgment",
    "Gratitude turns what we currently have into more than enough",
    "Stretching tight muscles relieves tension accumulated during prolonged desk work",
    "Disconnecting from digital screens promotes calmer restful thoughts before bedtime",
    "Deep diaphragmatic breathing activates the body parasympathetic calming nervous system",
    "Taking short mindful walks outdoors rejuvenates energy during demanding workdays",
    "Self compassion is treating yourself with kindness during challenging painful",
    "A peaceful morning routine grounds your energy for the day",
    "The serene breath will greatly inhale our inner peace today",
    "Every serene breath must inhale carefully across the entire inner",
    "Learning how to inhale serene breath inspires deep inner peace",
    "Our dedicated team will inhale the serene breath for inner",
    "The tranquil vitality will greatly restore our breathwork practice today",
    "Every tranquil vitality must restore carefully across the entire breathwork",
    "Learning how to restore tranquil vitality inspires deep breathwork practice",
    "Our dedicated team will restore the tranquil vitality for breathwork",
    "The mindful serenity will greatly rejuvenate our mental clarity today",
    "Every mindful serenity must rejuvenate carefully across the entire mental",
    "Learning how to rejuvenate mindful serenity inspires deep mental clarity",
    "Our dedicated team will rejuvenate the mindful serenity for mental",
    "The restorative meditation will greatly center our physical vitality today",
    "Every restorative meditation must center carefully across the entire physical",
    "Learning how to center restorative meditation inspires deep physical vitality",
    "Our dedicated team will center the restorative meditation for physical",
    "The holistic balance will greatly meditate our mindful living today",
    "Every holistic balance must meditate carefully across the entire mindful",
    "Learning how to meditate holistic balance inspires deep mindful living",
    "Our dedicated team will meditate the holistic balance for mindful",
    "The calming clarity will greatly nourish our restorative calm today",
    "Every calming clarity must nourish carefully across the entire restorative",
    "Learning how to nourish calming clarity inspires deep restorative calm",
    "Our dedicated team will nourish the calming clarity for restorative",
    "The grounded mindfulness will greatly unwind our inner peace today",
    "Every grounded mindfulness must unwind carefully across the entire inner",
    "Learning how to unwind grounded mindfulness inspires deep inner peace",
    "Our dedicated team will unwind the grounded mindfulness for inner",
    "The rejuvenating posture will greatly breathe our breathwork practice today",
    "Every rejuvenating posture must breathe carefully across the entire breathwork",
    "Learning how to breathe rejuvenating posture inspires deep breathwork practice",
    "Our dedicated team will breathe the rejuvenating posture for breathwork",
    "The peaceful nourishment will greatly harmonize our mental clarity today",
    "Every peaceful nourishment must harmonize carefully across the entire mental",
    "Learning how to harmonize peaceful nourishment inspires deep mental clarity",
    "Our dedicated team will harmonize the peaceful nourishment for mental",
    "The vital gratitude will greatly ground our physical vitality today",
    "Every vital gratitude must ground carefully across the entire physical",
    "Learning how to ground vital gratitude inspires deep physical vitality",
    "Our dedicated team will ground the vital gratitude for physical",
    "The serene breath will greatly inhale our mindful living today",
    "Every serene breath must inhale carefully across the entire mindful",
    "Learning how to inhale serene breath inspires deep mindful living",
    "Our dedicated team will inhale the serene breath for mindful",
    "The tranquil vitality will greatly restore our restorative calm today",
    "Every tranquil vitality must restore carefully across the entire restorative",
    "Learning how to restore tranquil vitality inspires deep restorative calm",
    "Our dedicated team will restore the tranquil vitality for restorative",
    "The mindful serenity will greatly rejuvenate our inner peace today",
    "Every mindful serenity must rejuvenate carefully across the entire inner",
    "Learning how to rejuvenate mindful serenity inspires deep inner peace",
    "Our dedicated team will rejuvenate the mindful serenity for inner",
    "The restorative meditation will greatly center our breathwork practice today",
    "Every restorative meditation must center carefully across the entire breathwork",
    "Learning how to center restorative meditation inspires deep breathwork practice",
    "Our dedicated team will center the restorative meditation for breathwork",
    "The holistic balance will greatly meditate our mental clarity today",
    "Every holistic balance must meditate carefully across the entire mental",
    "Learning how to meditate holistic balance inspires deep mental clarity",
    "Our dedicated team will meditate the holistic balance for mental"
  ],
  "hard": [
    "You cannot stop the turbulent waves of life but you can certainly learn how to surf them with grace",
    "Taking five slow deep breaths activates the parasympathetic nervous system reducing stress hormones and calming rapid heart rate naturally",
    "True wellness is not merely the absence of illness but dynamic state of physical mental emotional and spiritual vitality",
    "Setting healthy personal boundaries allows individuals to protect their emotional energy and nurture relationships that truly enrich their lives",
    "A mindful morning routine of silent meditation gentle stretching and mindful warm tea sets a grounded peaceful tone for the",
    "When confronting complex challenges in inner peace one must inhale every serene breath with rigorous discipline and patient determination",
    "The integration of serene breath within modern inner peace enables practitioners to inhale critical milestones without sacrificing enduring quality",
    "Throughout the evolution of inner peace master practitioners learned to inhale the most intricate serene breath through persistent dedicated effort",
    "Developing comprehensive understanding of inner peace demands that professionals inhale each serene breath with profound analytical rigor and integrity",
    "When confronting complex challenges in breathwork practice one must restore every tranquil vitality with rigorous discipline and patient determination",
    "The integration of tranquil vitality within modern breathwork practice enables practitioners to restore critical milestones without sacrificing enduring quality",
    "Throughout the evolution of breathwork practice master practitioners learned to restore the most intricate tranquil vitality through persistent dedicated effort",
    "Developing comprehensive understanding of breathwork practice demands that professionals restore each tranquil vitality with profound analytical rigor and integrity",
    "When confronting complex challenges in mental clarity one must rejuvenate every mindful serenity with rigorous discipline and patient determination",
    "The integration of mindful serenity within modern mental clarity enables practitioners to rejuvenate critical milestones without sacrificing enduring quality",
    "Throughout the evolution of mental clarity master practitioners learned to rejuvenate the most intricate mindful serenity through persistent dedicated effort",
    "Developing comprehensive understanding of mental clarity demands that professionals rejuvenate each mindful serenity with profound analytical rigor and integrity",
    "When confronting complex challenges in physical vitality one must center every restorative meditation with rigorous discipline and patient determination",
    "The integration of restorative meditation within modern physical vitality enables practitioners to center critical milestones without sacrificing enduring quality",
    "Throughout the evolution of physical vitality master practitioners learned to center the most intricate restorative meditation through persistent dedicated effort",
    "Developing comprehensive understanding of physical vitality demands that professionals center each restorative meditation with profound analytical rigor and integrity",
    "When confronting complex challenges in mindful living one must meditate every holistic balance with rigorous discipline and patient determination",
    "The integration of holistic balance within modern mindful living enables practitioners to meditate critical milestones without sacrificing enduring quality",
    "Throughout the evolution of mindful living master practitioners learned to meditate the most intricate holistic balance through persistent dedicated effort",
    "Developing comprehensive understanding of mindful living demands that professionals meditate each holistic balance with profound analytical rigor and integrity",
    "When confronting complex challenges in restorative calm one must nourish every calming clarity with rigorous discipline and patient determination",
    "The integration of calming clarity within modern restorative calm enables practitioners to nourish critical milestones without sacrificing enduring quality",
    "Throughout the evolution of restorative calm master practitioners learned to nourish the most intricate calming clarity through persistent dedicated effort",
    "Developing comprehensive understanding of restorative calm demands that professionals nourish each calming clarity with profound analytical rigor and integrity",
    "When confronting complex challenges in inner peace one must unwind every grounded mindfulness with rigorous discipline and patient determination"
  ]
};

export async function seed() {
  return await upsertCategoryAndSentences(category, sentences);
}

if (process.argv[1]?.endsWith('wellness.mjs')) {
  seed().catch(console.error);
}
